### ISSUE TITLE
Vanity URL

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1013]
**Problem**
GO URLs are data-driven but quite difficult to remember.  It would be ideal if there was a way to create 'vanity' URLs to then be able to more easily redirect users verbally or without a hyperlink.

**Proposed solution**
Ability to give a name to the emergency page as a manual override to the sequential numbering, e.g. https://go.ifrc.org/emergencies/COVID

![COV-snip-URL](https://user-images.githubusercontent.com/7791954/76711142-9fb69400-670d-11ea-9f84-63d859a265db.PNG)

**Comment by GregoryHorvath** [comment]
@LukeCaley Would we want to expand this to the whole site or just emergencies atm?

**Comment by batpad** [comment]
What we should do:

 - Add a `slug` field to Emergency, where users can define a custom short name for the URL
 - Add the ability to query an emergency by `slug` in the API
 - In the frontend router, accept non-number routes for emergencies
 - When receiving a non-integer value in the route, fetch emergency by `slug`

We will probably need to do a bit of figuring out on the frontend to get this to work, but on the backend, this should be relatively straightforward.

**Comment by LukeCaley** [comment]
Great, thanks @batpad 
This should be extended across the site but starting with ad-hoc emergencies, country and regional office pages.  So, for instance, I'm quite sure Regional Offices would be keen to have their region title instead of https://go.ifrc.org/regions/1#operations for example, so that they could share this more easily offline.

**Comment by geohacker** [comment]
This is fixed through https://github.com/IFRCGo/go-api/pull/636. To test:

* Go to https://dsgocdnapi.azureedge.net/
* Edit an emergency, you'll see a `slug` field. Enter the vanity url slug 
![image](https://user-images.githubusercontent.com/371666/77154315-76a55300-6ac1-11ea-9021-630b3d39591f.png)

* Save
* Then go to https://dsgocdnapi.azureedge.net/emergencies/<slug-you-added>#details

cc @batpad

**Comment by LukeCaley** [comment]
Assigned @teklal for testing and Q/A please

**Comment by teklal** [comment]
Tested and works with limitations. @geohacker can you share (if known) what the limitations for choosing the slug are? 
Based on my testing I found at least these:
- the slug cannot start with a number 
- it is case-sensitive (would it be possible to make it not be case-sensitive, as I foresee this potentially causing a lot of confusion?)
- the slug cannot contain a # (didn't test other special characters. - and _ are fine, even at the start of the slug)

There is no error when choosing a slug that doesn't work - the site just won't load with that URL then but gives a blank page:

![image](https://user-images.githubusercontent.com/52411237/77160317-61bbc600-6aa7-11ea-96bb-c0785381512c.png)

With this in mind it would be good to know what the limitations are so that a small guide text/tooltip (or something like that) could be added next to the slug box in the backend. Or then have the backend give an error and not allow the user to choose a slug that won't work.

I only get an error when choosing a slug that has already been taken (that's good).

As a note, the URL to test if it works is actually: https://dsgoproxyapp.azurewebsites.net/emergencies/<slug-you-added>#details
(@geohacker correct me if I'm wrong, but I wasn't able to test it with the URL in the steps above) 

It also works without the #details at the and also with just dsgoproxyapp.azurewebsites.net/emergencies/<slug-you-added>

@geohacker I saw that so far this is only for emergencies, right?
@LukeCaley  based on your comment from a few days ago on this ticket, do we want at this stage this to also be possible for country and region pages?

**Comment by geohacker** [comment]
@teklal thank you so much for your comments. I'll address them by making these changes:

* [ ] Enforce lowercase
* [ ] Adding a help text that clarifies limitations regarding

This is currently only for emergencies. I don't know how much effort is it to extend to other pages, but if it's not urgent we can revisit that.

**Comment by geohacker** [comment]
![image](https://user-images.githubusercontent.com/371666/77315420-8e810f00-6d2d-11ea-9635-257f95abf9f4.png)

Addressed these in https://github.com/IFRCGo/go-api/pull/642

**Comment by teklal** [comment]
@LukeCaley how urgently do we need this feature to exist for other than emergency pages (country and region pages...)?

**Comment by teklal** [comment]
Hey folks, just took a look at this now on staging and having the text under the box is nice, thanks for that!

In my comment above I mentioned also that the slug can't start with a number. I tested this now and got some weird behaviour:
![image](https://user-images.githubusercontent.com/52411237/77422483-d35c8280-6dcd-11ea-953a-b33956f12b77.png)
![image](https://user-images.githubusercontent.com/52411237/77422561-f4bd6e80-6dcd-11ea-9e63-020035e05a8e.png)

A slug starting with a number does load an emergency page but not the correct one...?

Haven't investigated this now further but thought I'd flag.

**Comment by batpad** [comment]
@geohacker are you able to debug this one?

**Comment by geohacker** [comment]
@teklal @batpad @GregoryHorvath that's my bad, sorry! I just fixed to check that the slug doesn't start with a number and added a help text. https://github.com/IFRCGo/go-api/pull/644

**Comment by LukeCaley** [comment]
@geohacker to investigate time effort for this option to be extended to country and regional pages

**Comment by nanometrenat** [comment]
Hi team, re the vanity URL for emergencies, unfortunately it needs a little more work.
It works well to go to the main page of an emergency (e.g. https://go.ifrc.org/emergencies/covid-19 ) however when I navigate to the Additional Info tab (either by clicking through or by going directly to the URL https://go.ifrc.org/emergencies/covid-19#additional-info) the page says "No data to display."

There is definitely data in the snippets on the Additional Info page of that emergency.

However if I go via the old URL (with emergency number) then the snippets show correctly:  https://go.ifrc.org/emergencies/3972#additional-info

This will need to be fixed before we can issue the vanity URL in Prod (sorry)

**Comment by geohacker** [comment]
@nanometrenat thank you for catching that. I'm bummed I wasn't able to. Sorry!
I'll look at this first thing tomorrow morning.

**Comment by geohacker** [comment]
@necoline @batpad I looked at this a bit closer and not sure what's the best way forward. I'll outline all the options:

**1. Add an epic action** 
This would be the cleanest and edge-case free approach. Right now, we invoke all the event API calls at the same time using the URL match params https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/views/emergency.js#L112. 

Instead of invoking them at the same time, we could add another action `GET_EVENT_EPIC`. Then first dispatch `GET_EVENT`, set the state with the id of the event and then subsequently dispatch `GET_EVENT_SNIPPETS`  and `GET_SITREPS` to use the id instead of the slug.

I'm finding it hard to implement this though because the way API request is bound to dispatching one action in the same method. @necoline @batpad thoughts? I'm new to this pattern and not sure if it's possible to dispatch multiple actions right after the API request.

**2. Use history.push to change the URL**
Not very elegant and could potentially make the URL not useful because we would overwrite the slug with the id. This would also fire all the actions again (kind of like a reload).

**3. Make all API endpoints accept slugs**
This is probably not ideal and we shouldn't. It's definitely a lot of work because the slug isn't added as a foreign key and we'd have to do that.

**Comment by necoline** [comment]
Hey sorry for the late response,  it took me a second to figure it out. But I have a solution in mind. We won't need a new API request since we get the id and slug from `GET_EVENT`. Handling promises in redux is a bit of a pain (at least the way it is currently set up) so I think the best way forward will be to create child components for the tab content that require data from `GET_EVENT_SNIPPETS` and `GET_SITREPS` so we can create subsequent rendering through the react tree. I'll push up a PR for this first thing in the morning.

**Comment by necoline** [comment]
The issue should be fixed with the ☝️ PR

**Comment by geohacker** [comment]
Thank you @necoline! This is a really elegant way to solve the problem.

@nanometrenat @teklal this fix is deployed to https://ifrc-go-fix-1013-slug-requests.surge.sh/ for testing. 

cc @batpad @GregoryHorvath

**Comment by teklal** [comment]
I'm having trouble testing this because I can't directly by url navigate to any other page than  https://ifrc-go-fix-1013-slug-requests.surge.sh/ without getting the following screen:
![image](https://user-images.githubusercontent.com/52411237/77897305-c7fbd200-7279-11ea-9467-78735ca6a5b9.png)
![image](https://user-images.githubusercontent.com/52411237/77897398-e792fa80-7279-11ea-88f7-4382633ef7c2.png)

Is this just something I'm doing wrong / not understanding?

**Comment by batpad** [comment]
This URL is working for me now: https://ifrc-go-fix-1013-slug-requests.surge.sh/

Maybe it was a temporary blip? Let us know if it still does not seem to work and we can try and work out why this is happening.

**Comment by teklal** [comment]
Yes the main url https://ifrc-go-fix-1013-slug-requests.surge.sh/ is working fine but navigating to any other page directly by url gives the page in the screenshots. 

e.g. https://ifrc-go-fix-1013-slug-requests.surge.sh/emergencies/3786
https://ifrc-go-fix-1013-slug-requests.surge.sh/emergencies/af-floods

**Comment by geohacker** [comment]
Ah damn yes, sorry @teklal - this is because the permalinks are not routed properly because it's surge.sh isn't respecting the react router. The best way to test this to get it deployed on staging. 

@batpad @GregoryHorvath - if we can merge https://github.com/IFRCGo/go-frontend/pull/1063 and deploy to staging that will be great.

**Comment by teklal** [comment]
So it now works to access the emergency page and the "additional information" tab with the slug (e.g. https://dsgoproxyapp.azurewebsites.net/emergencies/af-floods#additional-info) but there are still problems with data (snippets in the additional information tab and situation reports) not showing when using the slug.

![image](https://user-images.githubusercontent.com/52411237/78017612-cf3fe000-734c-11ea-9260-37d38ec429c0.png)

![image](https://user-images.githubusercontent.com/52411237/78017670-e7176400-734c-11ea-846a-e4c715e39c61.png)

**Comment by nanometrenat** [comment]
As mentioned in the call, if this is going to require significant additional effort then we should put it on ice for now and pick up higher priority items - thanks for the effort so far ;)

**Comment by geohacker** [comment]
I think @teklal tested this on staging now and it's all good to go!

**Comment by teklal** [comment]
I'm getting a blank page when trying to access an emergency page using an URL with the slug, e.g. https://dsgoproxyapp.azurewebsites.net/emergencies/af-floods#details

Don't know if this problem is now somehow related to the changes made relating to the "Merge emergencies" ticket, because with developer tools I can see that there are errors such as `Uncaught TypeError: Cannot read property 'parent_event' of undefined...`

**Comment by geohacker** [comment]
This is now blocked by #1088

**Comment by GregoryHorvath** [comment]
@teklal @geohacker I deployed this to staging: https://github.com/IFRCGo/go-api/pull/661 so now it should be good.

**Comment by teklal** [comment]
The snippets/information on the Additional information tab now pull through correctly with the slug URLs. Thanks!

However there are a few problems with this still:
- when using the slug, appeal document and response documents do not show on the emergency page
![image](https://user-images.githubusercontent.com/52411237/78820877-d44e0080-79d8-11ea-8ce7-ed3805a79042.png)
- when using the slug Personnel deployments show up on the emergency page that should definitely not be there (wrong country and emergency)
![image](https://user-images.githubusercontent.com/52411237/78820764-a8cb1600-79d8-11ea-9879-4282869542fd.png)
in fact these same deployments show up for all emergencies - even ones that should not have any deployments associated with them at all e.g. https://dsgoproxyapp.azurewebsites.net/emergencies/_test#details

Another note: on the help text for the slug on the backend, change the wording of the last sentence
"Special characters like # is not allowed." to "Special characters like # are not allowed."

As has been discussed on the calls and mentioned by @nanometrenat a few comments ago, we have to consider if it is more worthwhile to focus efforts elsewhere for now if the remaining fixes are going to take up a lot of time. 

This is an exciting feature and thanks for all the work and effort on this thus far!

**Comment by LukeCaley** [comment]
@batpad We would have liked to get this over the line but it seems from the above that there are still complexities to resolve. Suggest only prioritising this one for @kamicut if estimated to be less than one hour.

**Comment by nanometrenat** [comment]
### note
The above "slug" work was rolled out for emergency pages (with a couple of things still to look at before being rolled out fully).

HOWEVER note it turns out that there are already "verbose URLs" available for country pages and regional pages - these were implemented in March 2019 under https://github.com/IFRCGo/go-api/issues/357 (details on that ticket)

**Comment by szabozoltan69** [comment]
We should use singular in URL, so .../emergency/nice-name
