### ISSUE TITLE
Creating new users not working

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#102]
@guipizzini @renecnielsen The new user workflow was deployed last week. Can you test this functionality and let me know if you are still having issues?

One thing to note is that we haven't had a chance to input the full list of allowed email addresses that @renecnielsen supplied in #71. So, you will need to supply the emails of two admins in order to test this workflow currently. Note that admins are anyone who has `is_staff` set to true in the admin, which is currently done manually.

**Comment by guipizzini** [comment]
@dereklieu it still is not working.

If I "Register" a new user (even if using the admin emails) on the front end, it will always ask me to add 2 validation contacts from the IFRC.

In addition:

1. Those two contacts, do not get any notification/request for approving the person registering.
2. The user gets created in the Admin Interface, but when trying to login on the front end it will say "Invalid username or password".
3. I can create the user from the backend.
4. I cannot change the password from the frontend or when mentioning you forgot the password, it will not work.
5. The details that are automatically imported in user account are different from what we ask people to register.
6. If a user is logged in, he/she cannot update his profile from the front end.

Hope this helps out.

**Comment by dereklieu** [comment]
Cool, let's go through this so I can get a better understanding.

### Always asks for 2 validation contacts

Right now it's always asking for two validation emails, since we haven't added the whitelist email domains, so that's to be expected.

### Contacts do not get notifications 

What two emails are you giving it? Currently, for the admin validation fields, the email field is the only thing that matters. Each of the two emails must belong to a different, admin-level account.

### User gets created in the admin but can't log in

This is because when creating a user from the front-end, the system creates the user but sets `is_active` to false. As an admin, if a user cannot complete the login flow but still needs an acccount, you can set `is_active` to true, and that should allow them to log in.

### Can't change the password from the front-end

This was just deployed today. Can you check it again? Also note it probably won't work if the user has `is_active` set to false.

### Details automatically imported are different from what you ask people to register

Can you give specific items that are different?

### Can't update profile from the front-end

We didn't have time to implement this in the front-end.

**Comment by dereklieu** [comment]
cc @guipizzini

**Comment by guipizzini** [comment]
Cool, let's go through this so I can get a better understanding.

**# Always asks for 2 validation contacts**
Right now it's always asking for two validation emails, since we haven't added the whitelist email domains, so that's to be expected.

**Noted. When are we planning to have the whitelist imported?**

# **Contacts do not get notifications**
What two emails are you giving it? Currently, for the admin validation fields, the email field is the only thing that matters. Each of the two emails must belong to a different, admin-level account.

**Gave my email and the one of René, with IFRC and Gmail**

# **User gets created in the admin but can't log in**
This is because when creating a user from the front-end, the system creates the user but sets is_active to false. As an admin, if a user cannot complete the registration flow but still needs an acccount, you can set is_active to true, and that should allow them to log in.

**noted, thanks**

# **Can't change the password from the front-end**
This was just deployed today. Can you check it again? Also note it probably won't work if the user has is_active set to false.

**It works fine, I get the email. However, when I click on the link in the email I receive - I am redirected to a page that gives an error.**

# **Details automatically imported are different from what you ask people to register**
Can you give specific items that are different?

**Will send you details on Slack, with screenshots.**

# **Can't update profile from the front-end**
We didn't have time to implement this in the front-end.

**Any timeline for this to take place?**

Thanks for all, @dereklieu

**Comment by dereklieu** [comment]
@guipizzini the white list is imported and deployed, it should be working now.

When you say you gave your email and Rene's, are these the emails that you used to register with DMIS?

**Comment by guipizzini** [comment]
@dereklieu awesome - will test.

And yes, the same ones we use for DMIS (IFRC account - not the Gmail)

**Comment by guipizzini** [comment]
@dereklieu works fine. Whitelist functions, and filters email domains. Infobox comes up saying that the request for validation has been sent - but yet, no email received with mine and René's IFRC and Gmail accounts.

**Comment by guipizzini** [comment]
@dereklieu adding here the different elements that appear on the user profile (image 1) that are not the available on the Django Admin (images 2 and 3) part when entering users manually.

**Image 1**
<img width="947" alt="screen shot 2018-01-19 at 14 29 25" src="https://user-images.githubusercontent.com/23258092/35153173-aad24efa-fd25-11e7-96f8-1c145a7031e9.png">

**Image 2**
<img width="627" alt="screen shot 2018-01-19 at 14 29 58" src="https://user-images.githubusercontent.com/23258092/35153194-c4d8ba14-fd25-11e7-993c-fca61bb654b8.png">

**Image 3**
<img width="855" alt="screen shot 2018-01-19 at 14 30 17" src="https://user-images.githubusercontent.com/23258092/35153206-cd2f8026-fd25-11e7-8234-89d324cbb29a.png">

I would assume elements / details should be aligned? As well, on the user account do we want the user to be able to update his/her profile from the frontend? Just asking, your thoughts would be appreciated.

**Comment by dereklieu** [comment]
@guipizzini Ah yeah, those details are under a different part of the admin. For that particular user, you can find it here: https://dsgocdnapi.azureedge.net/admin/api/profile/2229/change/

Django has built-in fields for users, and overriding the default has implications that we decided weren't worth the complexity. So we created a separate user profile table to store extra information.

This puts some slight inconvenience on the operator, but it buys us a lot of flexibility. It makes it trivial to add more fields to a user profile, for example.

I think updating user profiles from the front-end would be a great feature to include in the second phase of work.

**Comment by guipizzini** [comment]
I think we can close this one @dereklieu as all is working?
