### ISSUE TITLE
Import the ICRC Spatial Data

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#104]
Hey @dereklieu here you can find the data from ICRC to be used for all of the Maps on Go.

Data can be grabbed here:

https://github.com/GISupportICRC/ArcGIS2Mapbox/blob/master/ICRCMapboxStyle

**Comment by guipizzini** [comment]
@dereklieu any progress on this one?

**Comment by dereklieu** [comment]
@guipizzini hey, just had a chance to look at this. Some quick questions:

1. Can we directly use the Mapbox GL layers in GO? My impression was that we don't have an enterprise account with Mapbox and so couldn't use their hosting. 
1. If the answer to the first question is yes, can we also use the ICRC mapbox account to host our base tiles? This would make it much, much faster to change our tiles. Right now, since we host our own tiles, we have about a days worth of overhead every time we want to upload new tiles (for example, tiles with new boundaries) just in upload time. This doesn't include the time it takes to generate and validate. 
1. Have you had a chance to look at any of these layers? I noticed there are several different variations. Do you have any direction on which layers to use and which to avoid? For example I'm not sure what REX white or Grey CIM Com Digital refer to.

On implementation: there is still one main blocker here which is that we don't have any tabular data on the admin level 2 regions that are represented in these rendered layers. So even if we can render the regions, we would still have to have the region names and matching IDs (matching the Mapbox layers) that would allow us to create forms across the site and admin, so that users could actually tie an admin 2 region to a particular field report or emergency.

Last, the site and admin have admin level 1 as a primary assumption and switching that would be a serious undertaking. I don't think we have the time to do this and test it while wrapping up the main delivery. I think it should be the first thing we tackle in a new contract or extension of the existing one.

**Comment by guipizzini** [comment]
Had missed this one, sorry! Will give feedback on Monday on the spatial data.

**Comment by guipizzini** [comment]
Ok, moved this one to phase 2.0. Thanks.

**Comment by danbjoseph** [comment]
- using the ICRC Mapbox account for the tile services on our production site might have billing implications for them that they weren't considering when they gave us permission to use them
- if we were to use the ICRC tiles, i think we would want some sort of plan for knowing when they update the date behind them and what they change, so that we can make sure their updates don't break our stuff
- might be worth sticking with the current workflow, but asking for their geo-data to build our tiles? (and we can just have a schedule to get updated data from them as needed)

**Comment by dereklieu** [comment]
> might be worth sticking with the current workflow, but asking for their geo-data to build our tiles? (and we can just have a schedule to get updated data from them as needed)

This would be great if it's in their wheelhouse. The tile-building process is already scripted, and we could even run it from an Azure VM instead of a local machine, which might cut down on upload times. I think it'd be worth checking up on.

**Comment by ElsaRaunioIFRC** [comment]
@guipizzini @dereklieu @danbjoseph I propose using the ICRC tiles as they are very appealing and definitely fulfill the movement standards. I offer to do the work required to make this happen, starting from liaising with the ICRC.

**Comment by danbjoseph** [comment]
@dereklieu please correct me if i'm wrong. i don't think that the styling really factors into the decision. see the earlier comments from Jan 18 and Feb 19. it's more a matter of the hosting of the tiles and who controls how/when/if the tiles changes. we could easily use (if they're willing to give it) both the data for the vector tiles and the stylesheet for the vector tiles. for just directly using the ICRC tiles from their Mapbox account, then there are potential issues with terms of use for the ICRC account agreement with Mapbox. also, if they update their underlying data, it could then potentially break Go functionality, depending on how/if the Go site interacts with the data of the vector tiles themselves.

**Comment by dereklieu** [comment]
Yeah I think that accurately reflects the potential issues. The hard part is not the styling or hosting of the tiles, it's building awareness of them into the API and interface.

**Comment by ElsaRaunioIFRC** [comment]
@danbjoseph @dereklieu @guipizzini We have discussed this issue today with our new lead, Luke. We are taking a look at the possibility of having our own MapBox, MapTiler or other tile hosting service.

**Comment by dereklieu** [comment]
Cool. If that could remove the need for us to host our own vector tiles, it would drastically cut down on time to upload tiles and allow us more flexibility in map design. Currently it takes about a day to upload zoom levels 1 - 10 to Azure storage.

**Comment by dereklieu** [comment]
@guipizzini @ElsaRaunioIFRC Hey, to set us up for sprint 2, we need a vector dataset of ICRC admin level 1, so that we can process tiles and prepare the front-end and API. It's important that we get this data sometime in the next week, otherwise we won't be able to start this task on time.

Can we get an update on:

1. Who would have access to this data?
2. What format can we get it in? Shapefile is preferred.
3. When can we expect to get it?
4. What can we do from our side to speed this up? Is there someone at ICRC I can speak to directly, perhaps?

**Comment by ElsaRaunioIFRC** [comment]
Hi @dereklieu, I am so happy to hear that the mapping process is getting ahead. I will try to find time today to talk about the issues you raised and get back to you asap.

We are currently in possession of ICRC Shapefiles for Admin 0 boundaries, Admin 0 polygons and Admin 1 polygons. What kind of style files would you use for the shapefiles? In .qml? In this case, I can provide you with the style files as well.

**Comment by dereklieu** [comment]
Done!
