### ISSUE TITLE
3W: Total people targeted counted automatically 

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1047]
Automatically calculated total for both targeted and reached. Logic as follows

Automatic if male, female and other entered. If total is typed in, male, female and other cleared. If a segregated field is entered, all the segregated fields are required

**Comment by lauripynnonen** [comment]
I like this implementation more than the one I tried to describe. So good job! an issue:
- If you type a number to a segregated field (like people targeted male) and erase it, the last digit stays in the total field

**Comment by karitotp** [comment]
The total count works well!, but the last number or digit erased from the segregated fields is still in the total field.

**Comment by frozenhelium** [comment]
That's expected behaviour as per the method of implementation, because after removing the last field value, there will no longer be automatic calculation and hence the last digit remains in the total field. Fixing this behaviour is slightly complicated, so let's leave it as is for now. We'll revisit the logic if it creates significant impact on the UX or the workflow.
