### ISSUE TITLE
[PROD] On emergency page generated from field report Country and Region information is not displayed

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1122]
## Issue
When a user submits a field report, if it has not been linked to an existing emergency page, a new emergency page will be generated from the field report. For some reason the country and region information does not show on this page in the field reports section although this information is available in the backend.

E.g. emergency page created from a field report
![image](https://user-images.githubusercontent.com/52411237/79441531-a586ea00-7fd7-11ea-882f-aaa63cae937f.png)

backend of this emergency oage
![image](https://user-images.githubusercontent.com/52411237/79449920-5eebbc80-7fe4-11ea-9042-1557afefbbb8.png)

## Steps to reproduce
Either create a new field report in Staging and do not link it to an existing emergency and observe the emergency page that is created from it, or check in production e.g. the example of the above screenshots https://go.ifrc.org/emergencies/4092#details 

## Expected behaviour
The country and region information should show in the assigned columns.

## Related feature
Maybe #920 ?

**Comment by teklal** [comment]
This would improve practical navigation as well. xref #928

**Comment by LukeCaley** [comment]
Any update on progress for this issue @kamicut ?

**Comment by batpad** [comment]
So looking into this issue, in the countries and regions columns there, we are meant to show the countries and regions associated with each field report that is associated with the emergency (and hence not pull in values directly for the emergency itself).

Turns out this data is not coming through in the API currently. This is easy to fix for countries, just gets slightly roundabout for "Regions", since we'd need to fetch region for each country. Do we need the "Regions" for each Field Report in addition to the Countries column?

**Comment by LukeCaley** [comment]
Short answer is yes please :)
It looks odd to have these gaps so if there is a fix that does not take too much time then it would be great to implement.

**Comment by batpad** [comment]
This fix is on staging. @karitotp could you please test and verify? Thanks!

**Comment by karitotp** [comment]
Working good! the countries and regions section is being completed https://dsgoproxyapp.azurewebsites.net/emergencies/4041#details

**Comment by LukeCaley** [comment]
@teklal are you satisfied to give a go on the UAT?

**Comment by teklal** [comment]
This looks good- thanks!

**Comment by teklal** [comment]
Working now in PROD, fantastic, thanks so much!
