### ISSUE TITLE
3W: Finetuning Form - Default values on Form, Remove primary sector from tags, Project status, Other as last disaster type

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1147]
- [x] Reporting NS: Currently the first option seems to be Finnish Red Cross - can we get this from the user's own national society?
- [x] Region/Province: Countrywide - switch to a blank (either too easy that everyone chooses countrywide)
- [ ] Remove the selected primary sector from tags to prevent double choosing (and future double counting)
- [ ] Disaster type: move Other as last (otherwise nice that the list is in alphabetical order)
- [x] Project status is a dropdown even when the user cannot change its value. Should it rather be a, for example, a disabled text field?

**Comment by frozenhelium** [comment]
@lauripynnonen Removing selected primary sector from secondary sector is not feasible currently because we have different set of options for primary and secondary sectors and those which are common in both also don't have same IDs (since some of the options were added later). We have to implement it with a different approach for it to work and it'll also take some time to implement as well. Let us know how important this one is, and we'll proceed accordingly.

Moving `Other` option in `Disaster type` to last because its sorted alphabetically. I suggest not doing this because it requires manual intervention and will add some inconsistency.
