### ISSUE TITLE
3W: Multi-region

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1175]
Most projects and activities are split into multiple regions. Lets change
- Input form to allow multiple regions
- display activity on all listed regions
- the export region on table as comma-separated values

**Comment by lauripynnonen** [comment]
Forcing single region projects seems to be a showstopper. So this needs to happen. @LukeCaley if you give this a go we should move this into the To Do list

**Comment by LukeCaley** [comment]
@lauripynnonen as discussed on the call, this is a GO.

**Comment by LukeCaley** [comment]
@lauripynnonen @guipizzini  would one of you mind detailing here what will be lost in terms of data integrity as a result of the change, just for our future reference and to feedback to colleagues.

@frozenhelium thanks for the update on the call today and confirming that this should be ready for test this week - looking forward and let us know asap so we can prep for testing capacity.

**Comment by guipizzini** [comment]
@LukeCaley the logic on how the 3W was initially scoped out was not to capture budget details as well as people targeted / reached.

When we agreed to include those elements it was clear that to avoid overlaps in aggregating data points as well as to avoid double counting we would have to enter per each geographic layer one input that contained people targeted / reached and the budget so that we could have accurate figures by admin 1 within a given country.

Now with the current status of the 3W we have agreed to include "multi-region" selection but the option to report on people targeted / reached and the budget remains only 1 for the "multi-region". This means that we should be able to do the aggregation of those points only at the national level and that doing it at sub-national level will not be possible.

@lauripynnonen have I missed anything?

**Comment by frozenhelium** [comment]
Hi @lauripynnonen, to implement this we'll have to remove the "Countrywide" feature, at least from the selection of the districts. We'll have to put a separate checkbox if it is required (however, we suggest not to do so). Also on the details that pop up on the map when we click on a region, we'll have to exclude the detail of the project that belongs to multiple region since we won't have the budget associated with that exact region. Let me know if this sounds good.
CC: @guipizzini

**Comment by lauripynnonen** [comment]
@frozenhelium 
- Could we have a "select all" functionality?
- On the map if you click a region could we list the projects that take place in that region, but also list all the regions a project takes place in if it's more than one? This way we could still show the budget
![image](https://user-images.githubusercontent.com/8285694/81791932-a98b2680-9507-11ea-9205-95c4d4ae912e.png)

**Comment by frozenhelium** [comment]
*Note:* Project district is now a required field. The regions that don't have any district won't be able to have the project. eg: 'The Sahel Country Cluster'

**Comment by lauripynnonen** [comment]
I've tested this as much as I can, seems to work everywhere (bulk, new, duplicate, change, country view, regional view etc.)

**Comment by lauripynnonen** [comment]
This works as described if we need to fine-tune this then it should be done through a new feature request
