### ISSUE TITLE
Emergency Page and Affected Population

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#118]
<img width="947" alt="screen shot 2018-01-25 at 07 56 27" src="https://user-images.githubusercontent.com/23258092/35375097-00b50838-01a6-11e8-8b99-56a786e222e0.png">

<img width="1235" alt="screen shot 2018-01-25 at 08 01 39" src="https://user-images.githubusercontent.com/23258092/35375149-4a8134fa-01a6-11e8-8663-e971cf54a9f6.png">

In the emergency page, when an event is created we get the "Affected Population" figure.

In the page of the single emergency, we only have the "targeted population". Could we make sure that we have as well on that page the "affected population" first, then the "targeted population" and then the funding details? Targets and funding, would come from the appeals. While the affected population should reflect what is on the map on the emergency page as per "affected population".

Hope it makes sense.

**Comment by dereklieu** [comment]
@guipizzini I agree with you here. However, if we do this we should discuss how to set the affected population figure for historical disasters.

Since disasters are a new concept in this system, a figure for the total number of people affected in a disaster is also new. There's no record-keeping for this, prior. So we set the total number affected to equal the total number targeted, based on the attached appeals. 

This is highly inaccurate, but we needed this in order to size the map circles on the emergencies page. 

Going forward an operator will fill out this figure for new disasters, based on GDACS or other sources. For historical disasters we really have no other source that I can think of. 

I would recommend just leaving the affected population number blank for historical disasters. This means an operator would have to fill out that number manually for every disaster within the last 30 days (to populate the map), and of course for every disaster going forward.

From what I can tell, none of the historical charts use affected population. You would just see a `N/A` if you navigated to an old disaster's detail page.

We could also just scrap the number if that's going to be too much overhead, and fall back to using targeted population everywhere.

**Comment by guipizzini** [comment]
Hey @dereklieu true. Could we keep the automation for all "new" events and we just make the box for "old" events saying something similar like "this is a new feature in Go, and is not available for old events" or just mention "Not available for historic events". Or we just keep it "empty" and we can have someone in the team, going through all the GDACS or Field Reports and insert them manually. GDACS and the Field Reports would be our sources to be used. Makes sense?

**Comment by guipizzini** [comment]
So, we will update the "historic" data manually - so we can go ahead in porting the "affected population" card and make it available for all the new emergencies. Make sense?

**Comment by dereklieu** [comment]
@guipizzini so to recap, I will add a spot in the emergency detail page for Affected Population. In addition, I will no longer automatically set Affected = Targeted population, since this is inaccurate, and rely on operators to do this. Is this right?

**Comment by guipizzini** [comment]
Correct.

**Comment by guipizzini** [comment]
As well the following bug has been identified.

1. On the emergency map (image below) if we take "Mauritius" the country name appears. However, it states 0 people affected and that IFRC responded to the Emergency, which is correct. Could we make sure that the "people affected" reflects what is in the field report, and that correctly shows up in other parts of Go (see following points below?)

<img width="1242" alt="screen shot 2018-01-31 at 22 30 07" src="https://user-images.githubusercontent.com/23258092/35648570-74978200-06d6-11e8-9019-f8f5e3998880.png">

2. Now if I go the homepage, and check the "Ongoing Operations" Map (image below) and click on the yellow bubble equivalent to Mauritius I get the "null" value instead of the country name and get the figures for affected and funding requested/received. All this is correct, with the exception of the "null" value. Could we put the country name there, instead?

<img width="1243" alt="screen shot 2018-01-31 at 22 32 03" src="https://user-images.githubusercontent.com/23258092/35648666-bf6109fa-06d6-11e8-883f-79472c7d64d9.png">

3. Now, if I go back to the emergency map, click the bubble of Mauritius and the click on the country name Mauritius within the infobox I am redirected to the country page. Here all the values popup correctly but the map has a somehow weird format/layout (image below). Could that be structured better?

<img width="1248" alt="screen shot 2018-01-31 at 22 33 58" src="https://user-images.githubusercontent.com/23258092/35648743-03b9cc40-06d7-11e8-83d6-4abe897cdb48.png">

4. Finally, when scrolling down, I go see the field reports section when not logged in and I get the below message. Could we replace this by specifying something like we did in other parts of Go that you need to login to view the field reports?

<img width="1007" alt="screen shot 2018-01-31 at 22 36 27" src="https://user-images.githubusercontent.com/23258092/35648837-57761384-06d7-11e8-9106-04377a4a10aa.png">

**Comment by guipizzini** [comment]
<img width="1259" alt="screen shot 2018-02-05 at 08 37 49" src="https://user-images.githubusercontent.com/23258092/35792965-f762cf88-0a4f-11e8-9262-02288b6b72b1.png">

<img width="1254" alt="screen shot 2018-02-05 at 08 38 10" src="https://user-images.githubusercontent.com/23258092/35792971-fb02dc82-0a4f-11e8-99b2-b42daebb9f21.png">

The two "full screen" options for deployments and ongoing operation have a different formatting, any chance we could make them look similar in terms of graphic design/layout?

**Comment by guipizzini** [comment]
Especially the map format. The Ongoing Ops looks better.

**Comment by guipizzini** [comment]
Any chance we can get this one done on phase 1.0?

**Comment by guipizzini** [comment]
cc @dereklieu

**Comment by dereklieu** [comment]
I've stopped automatically setting number of people affected. Sorry, this is a pretty long ticket. Can you go over again what needs to happen here?
