### ISSUE TITLE
Translation: Find out all the static strings in all the views and components

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1239]
Ready for testing in the [Translation test site](https://ifrc-go-feature-translation.surge.sh/)

Things to be tested in [test site](https://ifrc-go-feature-translation.surge.sh/) vs [staging site](https://dsgoproxyapp.azurewebsites.net/):
* Nothing is visually broken and is similar to the staging site
* All the texts are in place and are same to that of the staging site

This applies sitewide. So, testing this will require navigating through and testing all the views in the site.

**Comment by frozenhelium** [comment]
Ready for testing in the [Translation test site](https://ifrc-go-feature-translation.surge.sh/)

Things to be tested in [test site](https://ifrc-go-feature-translation.surge.sh/) vs [staging site](https://dsgoproxyapp.azurewebsites.net/):
* Nothing is visually broken and is similar to the staging site
* All the texts are in place and are same to that of the staging site

**Comment by LukeCaley** [comment]
As discussed on the call today, could you @karitotp test according to the notes above. All should be self-explanatory but please reach out to @frozenhelium if any further detail required cc @batpad

**Comment by nanometrenat** [comment]
Hi, over to Karito for full testing but a couple of notes that I happened to notice just now:

- [ ] grey screen on Field Reports page (https://ifrc-go-feature-translation.surge.sh/reports/all and the various regional versions)
- [ ] homepage - maps - legend format strange (same for other maps e.g. emergencies page)
- [ ] homepage - paging buttons - showing vertically when should be horizontally (same in several places where paging buttons are used, on various pages)

Thanks

**Comment by karitotp** [comment]
Hey @frozenhelium @LukeCaley @batpad @nanometrenat, I gave a view to all page (I hope that I have not missed one) and generally the things look good, some things that I found that need to be fix is listed below:

- [ ] Home page: some other bad formats apart of the things that Natalie mentions above:

 - The legend for appeals and DREFs on the sadistic charts is displaying just in one column, while in the staging site it is displayed in two columns (This is happen in all pages where there are these charts).
![Screenshot from 2020-06-19 09-10-12](https://user-images.githubusercontent.com/11504548/85141893-21d2bf00-b20d-11ea-9dd3-3aad3e87b7da.png)

- In the footer, "© IFRC 2020" is on one line below, instead to be all footer text just in one line only (same in all pages)
![Screenshot from 2020-06-19 09-28-07](https://user-images.githubusercontent.com/11504548/85143788-d2da5900-b20f-11ea-9b30-7f6d92520252.png)

- [ ] Preparedness page:
 - The graph :point_down:  is located a bit more close to the text than on the staging page:
![Screenshot from 2020-06-19 09-21-23](https://user-images.githubusercontent.com/11504548/85142980-be499100-b20e-11ea-96e2-1d43d5b6fd7e.png)

- [ ] Account page: 
 - In account information tab, the section of OPERATIONS FOLLOWING and ACCOUNT INFORMATION is broke, there is no space between them and the first section have a bigger space from the tabs. https://ifrc-go-feature-translation.surge.sh/account#account-information. This is also happen whit the sections in Notifications tab.
- Also in the Account information section, all the contents even the button is displayed vertically.
![Screenshot from 2020-06-19 09-43-38](https://user-images.githubusercontent.com/11504548/85144853-5f394b80-b211-11ea-982a-22e2b184482f.png)

- [ ] Deployments page:
 - Some issues in spelling
![Selection_007](https://user-images.githubusercontent.com/11504548/85152040-2356b400-b21a-11ea-86d9-850d3de430c2.png)

- The drop downs button in the titles of this chart is not working.
![Selection_010](https://user-images.githubusercontent.com/11504548/85152051-26ea3b00-b21a-11ea-9448-8ce78890965d.png)

- This line of text is aligning to the left instead to right.
![Selection_011](https://user-images.githubusercontent.com/11504548/85152536-bc85ca80-b21a-11ea-8c15-012e8861f5b2.png)

- [ ] Emergency view: 
 - The buttons is located over the Emergency name: https://ifrc-go-feature-translation.surge.sh/emergencies/3995#details, this type of buttons is displayed in this position in other pages too where they are, E.g. Country page.
![Screenshot from 2020-06-19 10-02-52](https://user-images.githubusercontent.com/11504548/85147170-1636c680-b214-11ea-86e5-6ad93b66b5b8.png)

- [ ] Report view: 
 - In the numeric details, in volunteers number title is displayed as :point_down:, while in the staging page it is displayed correctly as "Volunteers"
![Selection_006](https://user-images.githubusercontent.com/11504548/85149120-8ba39680-b216-11ea-939e-497b335b2010.png)

- About the grey scream, it is  appearing when we want to see all reports,  all emergencies, all operations.

**Comment by frozenhelium** [comment]
@karitotp 

Update: This is now merged into develop and available in [staging site](https://dsgoproxyapp.azurewebsites.net/)

Focus of testing:
- Nothing is visually broken and works as intended (i.e. as it was before)

Note: Similar to the previous testing, this applies sitewide. So, testing this will require navigating through and testing all the pages in the site.

CC: @batpad @LukeCaley @guipizzini @nanometrenat

**Comment by nanometrenat** [comment]
@frozenhelium noting that several of the above problems are now present in staging so it would be great if you could please fix them up before @karitotp does further testing.  I think on the call you said it was something to do with styling needing manual intervention or something?  If the same fix is rolled out to staging and then documented (so that it is part of the release when it goes to Production) that would be great.  cc @batpad 

Thanks a lot!

**Comment by frozenhelium** [comment]
@karitotp @nanometrenat The issues mentioned above is now fixed!

**Comment by karitotp** [comment]
Hey @frozenhelium, all the above issues is fixed now, but what I found now is mostly differences in the icons styles and the alignment of the titles. Do not know if these are new required styles but some of them are causing that some details, titles and  buttons to not look good for some pages. Below some examples of this in the different pages.
 
- [ ] Home page
- The HIGHLIGHTED OPERATIONS section now is appearing at the last part of the page instead to be at the beginning of the page  and the icons and numbers styles are different to the previous.

![Screenshot from 2020-07-03 09-34-45](https://user-images.githubusercontent.com/11504548/86478840-a135b780-bd10-11ea-964b-724ec3fbe928.png)
_Current style_

![Screenshot from 2020-07-03 09-36-46](https://user-images.githubusercontent.com/11504548/86478907-c0344980-bd10-11ea-9a36-75a8db1bb600.png)
_Previous style_

- [ ] Country and Region page
- The title is aligned to the center of page and different icons style

![Screenshot from 2020-07-03 10-17-27](https://user-images.githubusercontent.com/11504548/86482558-d2fe4c80-bd17-11ea-9fd5-de1e4de0c392.png)
_Current style_

![Screenshot from 2020-07-03 10-17-46](https://user-images.githubusercontent.com/11504548/86481896-7a7a7f80-bd16-11ea-815a-521d3f8d8a07.png)
_Previous style_

- [ ] Deployments page:
 - The icons and style in the header look different to the previous ones. Also the title "Deployments" now is centered.

![Screenshot from 2020-07-03 09-11-15](https://user-images.githubusercontent.com/11504548/86477872-ed7ff800-bd0e-11ea-9284-a4f433040327.png)
_Current style_

![Screenshot from 2020-07-03 09-24-34](https://user-images.githubusercontent.com/11504548/86477950-0d172080-bd0f-11ea-8308-dc03a2adc346.png)
_Previous style_

- [ ] Emergency page: 
 - Same to the deployments, here also the icons and style in the header is different to the previous style and the title is centered too.

- [ ] Emergency view: 
 - The title and emergency overview details are centered, instead of lining up left.

![Screenshot from 2020-07-03 09-15-41](https://user-images.githubusercontent.com/11504548/86482705-1b1d6f00-bd18-11ea-9852-193a57575ba6.png)

- [ ] Report view: 
 - The title is centered and not in the left side.
![Screenshot from 2020-07-03 09-52-46](https://user-images.githubusercontent.com/11504548/86480127-07233e80-bd13-11ea-838a-01395d7929d9.png)

cc. @nanometrenat @batpad

**Comment by batpad** [comment]
Hey, thanks for this @karitotp ! So sorry I wasn't clearer on the multiple things merged.

On staging there is also the change to the Key Figures styling: https://github.com/IFRCGo/go-frontend/issues/1324 . I **think** most of these things are you noticing look related to changes @imohkay made to spacing and key figures styling, following the latest wireframes and designs.

@imohkay - could you please look through the things @karitotp has flagged above and confirm that they are to do with the design changes you've made. If anything seems unrelated to your changes, please flag @frozenhelium .

@imohkay could you also update https://github.com/IFRCGo/go-frontend/issues/1324 with changes made there and what @karitotp should be testing in terms of the frontend changes to Key Figures and other spacing / centering things. Thanks much!

**Comment by imohkay** [comment]
@karitotp @batpad 
So the changes I've made affect the following:
- The centered page titles. Yellow Umbrella indicated all the page headings (the main titles) should be centered.
- The key numbers, associated with #1324 have new styling requirements. I will assign #1324 to you soon. @karitotp 

I think many of the other changes are to do with the translation changes (pagination, issues on map legends, buttons dropping to next line, etc. due to the new float attributes)

**Comment by guipizzini** [comment]
This looks good to me, after testing. Icons have new restyling on the cards as pointed out by @karitotp

**Comment by nanometrenat** [comment]
Accepting risk, going to Production now

**Comment by nanometrenat** [comment]
Caused https://github.com/IFRCGo/go-frontend/issues/1508 (already fixed)
