### ISSUE TITLE
Field Report export - COVID FRs only - API but also UI

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1326]
## Issue
There are lots of people looking at and analysing COVID FRs.

We need an easy way to filter lists to only COVID-type field reports (i.e. is_covid_report = true).

- [x] On the API (https://goadmin.ifrc.org/api/v2/field_report/) we need to be able to specify is_covid_report as a filter parameter.

- [ ] On the front end, we need a button/selection option on https://go.ifrc.org/reports/all (and the regional variants e.g. https://go.ifrc.org/reports/all?region=0) to allow the user to specify if they want to export ONLY COVID-19 Field Reports.

Adding the ability to export only COVID-19 FRs will improve the user experience and also reduce the download size.

May also wish to consider adding a date filter for FR export (report date is already supported as a param in the API call just not on the front end export).

For consideration by @mariam-yu and @batpad as to front end implementation - but in the meanwhile @GregoryHorvath are you able to please do the honours re API query param?

Thanks a lot

**Comment by GregoryHorvath** [comment]
@nanometrenat The API (first) part is deployed to staging.

**Comment by batpad** [comment]
:+1: @mariam-yu going to await on design guidance here.

**Comment by nanometrenat** [comment]
API change was successfully deployed to Production last night, so now just the front end to do - thanks all

**Comment by nanometrenat** [comment]
Per today's call it was decided that rather than a COVID/nonCOVID button it should instead be a filter by Field Report Type (Early Warning vs "normal" (not sure what that should be called - @mmusori what do you think?) vs EPI vs COVID-19 types), so it is extensible.

Date filter to also be added please.  Thanks!

**Comment by batpad** [comment]
I like the idea of adding some more filters to the Export.

Just a couple things:

 - I would much prefer if we stick to the taxonomy in the database - so have filters for:
   - Status - i.e. `Event` / `Early Warning`
   - Disaster Type (where Epidemic is one of the options)
   - Is COVID Field Report as a separate boolean / checkbox
   - Date filters

Depending on urgency, I would perhaps still advocate for getting in just the `Is Covid` filter in first, and adding other filters subsequently (if time for both design and development will increase by a lot with the additional filters) - though, it would be nice to treat the `Is Covid` as a filter, i.e. a separate checkbox or so, instead of a separate button, so we can easily combine it with other filters in the future. I am hopeful, though, that if we have designs, we should be able to implement all the filters.

Secondly, would it be okay to move "Filters on Field Report Export" or so to a separate ticket, and reduce the scope of this ticket to just the API implementation? I'm happy to do that if that seems okay.

**Comment by nanometrenat** [comment]
Thanks @batpad will leave it to you-all to figure out best approach.  In terms of tickets, may we please keep this one for the UI (as the API change was just one step on the road to delivery, and the discussion is all on this ticket).  Thanks a lot!

**Comment by nanometrenat** [comment]
@mariam-yu @batpad @LukeCaley what do we need to move this forward?  Thanks loads!

**Comment by mariam-yu** [comment]
@nanometrenat Not sure if anything is expected from us, as I think the decision was to implement a Type dropdown, correct? We already had a Disaster Type on this screen: https://invis.io/76XXS0FGDFT#/359175153_1-1_GO_Home_Ops Does it cover it?

**Comment by nanometrenat** [comment]
Thanks @mariam-yu - from the COVID operation point of view my business requirement was to have a way (any way) to export COVID FRs - know others had stronger views about beat way to implement (balancing ideal design vs implementation practicalities).  I believe after today's call this one is now with @batpad ?  Thanks all!

**Comment by LukeCaley** [comment]
@batpad is this currently seen as in scope for 4.3?  If not, please elaborate the desired way forward and time estimate for future prioritisation

**Comment by batpad** [comment]
We have this in the API. On the frontend, the new designs tackle this in a more holistic way in terms of implementing filters for the CSV exports - unfortunately, the entire filters implementation did not come through in 4.3. It would be great to find time to work on the CSV filters in 4.4. We may want to reframe the ticket a bit as we would likely want to implement all the filters across all the CSV exports as a single feature.

**Comment by nanometrenat** [comment]
@tovari @anamariaescobar @ypyelab I am closing this ticket as I think you have been doing new thinking on export formats.  However feel free to re-open (or x-ref) if this ticket is in fact still helpful after all.
