### ISSUE TITLE
Export of field reports from the front end

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#1349]
If you are logged in, the "export all" functionality here:

https://go.ifrc.org/reports/all

Does not complete as expected.

However it works smoothly, once you are not logged in.

**Comment by nanometrenat** [comment]
Also works smoothly when logged in but just exporting region by region - i.e. it's due to data size.

There are 3 parts to the Field Report export work as far as I can tell:

1. making the export process **robust** no matter how much data is being exported (within reason) - generic to exports (i.e. including emergencies etc.), and may require infrastructural changes e.g. separate server/paging - tracked via this ticket, some related tickets include

- original build tickets 2018:  https://github.com/IFRCGo/go-frontend/issues/296 https://github.com/IFRCGo/go-frontend/issues/325 and particularly noting https://github.com/IFRCGo/go-frontend/issues/539 which includes the comment
> Yes, you are right, Derek: the "more human-readable" header is the main reason of the less performance (or the overuse of memory). If someone really wants to have an "all-in-one" .csv export for field reports, then the nice header should be omitted (or fix afterwards manually with an other tool).

https://github.com/IFRCGo/go-frontend/issues/539#issuecomment-445161510

2. allowing **filters** to reduce the size of exports by reducing the number of records included to be only what the user needs - tracked under https://github.com/IFRCGo/go-frontend/issues/1326

3. **content/structure** of the export in terms of how the csv export is laid out (rows/columns/wide/deep/JSON within fields or not etc.) - this needs to be a generic design pattern conversation and then any changes rolled out for each specific export as required - e.g. having a param to choose "full/detailed/extended" vs "normal" vs "mini" (or similar) could reduce amount of data returned in many cases.  Tickets include:

- original build https://github.com/IFRCGo/go-frontend/issues/364 including [comment](https://github.com/IFRCGo/go-frontend/issues/364#issuecomment-409082847)
- user request for long vs wide format https://github.com/IFRCGo/go-api/issues/768

@batpad @GregoryHorvath feel free to add/amend if your view is different re the work split!
cc @teklal @LukeCaley 

Noting also other tickets that aren't specifically to do with the above 3 items but relate to csv export in general so mentioning here:

- https://github.com/IFRCGo/go-api/issues/738 (blank pages when exporting csv from docs page)
- https://github.com/IFRCGo/go-frontend/issues/969 (date format in Excel)

**Comment by LukeCaley** [comment]
@batpad @GregoryHorvath to update on desired way forward and time estimate please

**Comment by batpad** [comment]
There has been work done improving performance of CSV exports for Emergencies and Field Reports. However, within the current architecture, doing an unbounded query for ALL field reports or emergencies in a single request will always be hard to scale.

We still have some work to do here to make things completely robust. Implementing filters will be one way of allowing users to easily fetch subsets of data, but we will need to think of an approach toward large exports, where as I see it, our options are:

 - Restrict the page size on the backend, and have the frontend paginate through responses and generate a consolidated CSV to the client.
 - Have a cronjob write a static file of all emergencies / all field reports every 30 minutes or so and have users fetch the flat file rather than querying the database for every request.
 - Now that we have `celery` setup to do Async job flows, setup CSV exports as async jobs where users kick off the job, get a token, and are informed when their "job" is complete - though this is not something I'd recommend due to added complexity.

@LukeCaley we have tackled a couple of things with regards to CSV exports in this phase:

 - Optimizing the database queries across the board, making CSV exports 2-3 times faster (still not good enough in some cases).
 - Worked on reducing the size of data returned in the CSVs, through normalizing multiple columns.

What we would still need to do:

 - Work on filters on the frontend #1326 
 - Figure out our caching / pagination strategy to tackle scaling of the CSV exports on the backend as per comment above.

Would still need some discussion to hone in on an exact plan here. Moving to 4.4.

**Comment by frozenhelium** [comment]
This is now ready for testing at the [staging server.](https://ifrc-go-feature-field-report-export.surge.sh/reports/all)

Changes:
- Reworked the download process
Previously, when `Export all` button was clicked, a request to the server was sent to fetch the whole CSV at once, which took a lot of processing in the server and it caused occasional failure of the download (due to the server timeout).
In the new approach, only 50 rows are fetched at once, until all the rows are fetched and merged together to create a single CSV file. This approach adds a bit of download time due to the multiple request but will work all the time (will not cause the server timeout due the excessive load).
- Added download progress

**Comment by batpad** [comment]
@frozenhelium - this is so good!

Tested it after logging in on the frontend and download worked perfectly (downloaded CSV with 9,000+ rows).

> This approach adds a bit of download time due to the multiple request but will work all the time (will not cause the server timeout due the excessive load).

Let's discuss this and figure out what a good middle ground for rows per page is -- my hunch is we could up this from 50 to 500 per page without causing issues to the server and significantly speeding up things on the frontend - however, the progress indicator is great and I think this is fine - but we can definitely consider increasing records per page if it seems too slow.

This looks excellent to me @frozenhelium - shall we ticket out implementing a similar mechanism for all the CSV downloads?

**Comment by frozenhelium** [comment]
@batpad Yep, we should experiment on the rows / page to balance out the download time / server load. I've setup a base framework for this kind of export. So, it should be fairly easier for other CSV downloads as well.
