### ISSUE TITLE
Add grid that is RTL friendly across the site

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1382]
Broader description available at #1364 
Create an SCSS grid using flexbox and equal horizontal padding to match the site requirements.
Test the new grid on the home page

TODOS (once the pages are complete)
- Add documentation in a markdown file which is linked from contributing.md
- Ensure all the float left and Jeet mixins, styles are removed, and remove the reference to the Jeet grids (at the very end)
- Remove all the masses of commented-out code, looking for trailing float left and float right, margin-right, positioning, etc which hamper RTL styling.
- Move to swapping out $global-spacing and margin with $spacing variables

**Comment by imohkay** [comment]
@frozenhelium for flexbox properties like margin-left: auto, do we need to replace margin-left with margin-inline-start ?

**Comment by batpad** [comment]
This is the list of changes and pages touched, to support the new grid for RTL languages, as well as ensuring consistency with regards to the new designs.

@karitotp it would be great to do a thorough test of these on staging.

### Not pushed for this release
- Matching filter styling for Tables to new designs

### Across the Site:

 - Since the site has a new grid, please make a note if the UI looks broken anywhere (like very tight margins, overlapping text, some items which were in 2 columns are now in 1 column, etc.)

 - Cross browser testing

 - Testing for RTL languages
    
 - Restyling of Key Figures to match designs.

   (Reference: https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ebd38896a3c2230f204bd5b)

 - Style search box in navigation according to new design (But the search dropdown is not styled for this iteration).

 - Restyling of Highlighted Operations to match designs
   - Add Follow button to Highlighted Operations with toggling

 - Restyle tables across the site to match designs
   - Add Progress Bar for Funding %
   - Restyle Pagination elements
   - Hide Pagination if not applicable

 - Update fonts across site

 - Update spacing between elements to match new designs

- Update tab styling across site:
  -- Tabs now have a full-width white background. Their font sizes and active state should match the designs on Zeplin. 

 - Update link styles across site
    There are now 4 styles of links (black with underline, black with underline and chevron, red with chevron, plain red)


 - Use responsive styling to greatly improve layout on mobile devices / smaller screens

### Home-Page

 - Move Key Figures above Highlighted Operations as per new designs
 - Margins, padding, shadows of elements to match new designs
 

### Emergencies Landing Page

- Page has been redesigned to broadly match Zeplin design (https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ef9f5c29230c610c93a7055)
- Highlighted Emergencies will not be added for this release


### Region Page
(Reference for 3W Tab: https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ef1e9737f5d6645f7dcacb9)

- Region page should broadly match the new designs. 

### Field Reports Page
(Reference: https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ec398120030012ff06b8ef1)

- This should broadly match the new designs with grey background and white boxes for the form elements, new styles for checkboxes, radio buttons


### Country Page
- Still a work in progress. Just ensure that the main styles are in place. We can revisit this soon.
- In the page header, the action button (Edit Country) should be inline with the Breadcrumb.

### Additional Pages
- Please check Deployments, Preparedness, Emergency Landing page, Account pages, Resources, Login pages for general consistency and to ensure nothing is broken in the UI.
- These pages don't have a design reference, so overall changes have been made for them to make them consistent with the new theme.
(Although the specific emergency page has been recently added to Zeplin, we may match it exactly for this iteration)

**Comment by GregoryHorvath** [comment]
Don't know if this happens only on Ubuntu because as far as I know the 125% DPI option is not yet fully supported, or on other systems too but this happened while using it - Emergencies page top part:

![hidpi_bug](https://user-images.githubusercontent.com/30079559/88178796-3b5f9000-cc2b-11ea-9218-5ec940052b27.png)

After switching back to 100% DPI it looks normal now (I guess), the whole list is in a white card and the Export button is inside the card.

**Comment by karitotp** [comment]
Hey @batpad, I gave a look to the all page in ubuntu, overall looks good and most of the things match with the design in zeplin, there are still some things that are different, some of them I comment below:  

- Home page:
 In the last part of the home page, in Staging site is "SURGE NOTIFICATIONS" instead the "LATEST EMERGENCIES" according to the stile in zeplin.

![Screenshot from 2020-07-22 14-52-52](https://user-images.githubusercontent.com/11504548/88222561-c771b780-cc2b-11ea-8f6c-ff084750e434.png)
_Staging site_

![Screenshot from 2020-07-22 14-52-33](https://user-images.githubusercontent.com/11504548/88222547-c476c700-cc2b-11ea-8ef6-925f6538f00f.png)
_Zeplin_

> Restyle tables across the site to match designs

In home page the table has some columns with different name than Zeplin, for example: Requested Amount instead Request Funding.
In emergencies page, in the table there are not Type neither Funding columns. Also in the field reports table, there is no the search field, filter dropdowns and the export button.

![Screenshot from 2020-07-22 15-54-29](https://user-images.githubusercontent.com/11504548/88227832-d8262b80-cc33-11ea-8ca8-f5629eb41952.png)


> Emergencies Landing Page
- The key numbers does not match with the style, in section of map and emergencies table the title is different, the map does not display any data and in the emergency table there are not the search field and dropdowns for filtering.

- When the user is not logged, can go to the admin site and edit the emergency, can edit a country too. Ex. https://dsgoproxyapp.azurewebsites.net/emergencies/3833#details


**Other things to take a look:**

- In language option, when the Arabic is selected all change the position and the text is aligned to the right and some things don't look good.
![Selection_001](https://user-images.githubusercontent.com/11504548/88235343-4d97f900-cc40-11ea-947a-ebb566470f62.png)

- In home page, the list in some dropdowns is not in alphabetical order.
![Screenshot from 2020-07-22 16-04-41](https://user-images.githubusercontent.com/11504548/88228767-44edf580-cc35-11ea-874c-bf50a3837b6d.png)

- The search is not finding any match.
![Screenshot from 2020-07-22 16-06-44](https://user-images.githubusercontent.com/11504548/88228830-5b944c80-cc35-11ea-9025-cd92e4320c13.png)

**Comment by imohkay** [comment]
@frozenhelium Hey, quick question: For certain properties, we may need special styling like for background-position.
In that case, I would guess doing something like this in Sass would be ideal. But this doesn't seem to work for me

```
.foo {
    background-position: left 44%;

    [dir='rtl'] & {
      background-position: right 44%;
    }
}

// OR THIS

[dir='rtl'] .foo {
      background-position: right 44%;
}
``` 
However, if I manually change the body tag to say `<body dir='rtl' ...>`, then that works. Right now, the rtl is being applied conditionally as an inline style.

Let me know your thoughts...

**Comment by imohkay** [comment]
@GregoryHorvath That's some old code using negative margin for the Export table button. Hopefully, all this will be sorted out once the table filters are implemented across the site, which is on the radar.

**Comment by imohkay** [comment]
@batpad some of Karito's observations may be for you...

**Comment by frozenhelium** [comment]
@imohkay I haven't changed the `dir` property of the `body` when switching to rtl language, I'll add that too. It should work as expected after that. If it works when you do `<body dir='rtl` ...>`, then it'll be good afterwards as well.

**Comment by imohkay** [comment]
@frozenhelium Sounds good. I made a PR for you with some changes for improvements in RTL styling.

**Comment by nanometrenat** [comment]
These changes are going to Production today however this ticket is staying open until it can be actually tested with an RTL language.

**Comment by batpad** [comment]
Marking this as done in favour of #1253 which we shall use as the main ticket to track styling of RTL languages across the site when an RTL language is available for testing. @nanometrenat feel free to re-open, thanks much for the ticket clean-up here.
