### ISSUE TITLE
Update of Emergency Map

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#141]
Hi Anna, on the map of the emergency page, the infobox should reflect the taxonomy used in the legend of the map, that was correctly updated.

<img width="978" alt="screen shot 2018-01-30 at 08 56 12" src="https://user-images.githubusercontent.com/23258092/35554310-88e00ac0-059b-11e8-8a3d-a0755f89029b.png">

**Comment by guipizzini** [comment]
As well, could you clarify what you related to with "Mixed level of response"?

**Comment by guipizzini** [comment]
The infobox, should have the same wording of the legend.

**Now we have:**

1 Emergency
1 with response
0 without response

**It should be:**

1 Emergency
1 Without IFRC response
0 With IFRC response
0 Mixed Level of Response

As well, could we add the source (Whether its coming from GDACS or Field Reports)?

Could we add a description of what mixed level of response means?

**Comment by dereklieu** [comment]
@guipizzini Sure, I'll update the text. The infobox can't say # of emergencies with a mixed response, since an emergency either has a response or it doesn't (an aggregate number of emergencies can have some with response and some without).

In this case a response denotes an appeal or dref being attached to the emergency. I think it does make sense to add a note on this.

**Comment by LukeCaley** [comment]
@guipizzini Not sure I understand (nor will 90% of other users presumably) what a 'mixed response' means.
