### ISSUE TITLE
admin1 shapefile has incorrect encoding for names

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1456]
## Issue
admin1 shapefile has several district names that aren't properly encoded. For example:

* `?smay?ll?` for `İsmayıllı`
* `Br?ko`
* There are a lot of these weird ones that make matching really difficult

cc @batpad @guipizzini @teklal

**Comment by jhenshall** [comment]
Had similar issue with the country dataset returning `CÃ´te d'Ivoire` and `Sao TomÃ© and Principe`. I've found that this is actually an issue with how Excel imports CSVs (it should use UTF-8 but defaults to Windows format). When viewing the CSV as text and/or importing as UTF-8, the accents are displayed correctly.

@geohacker - does this definitely address the issue you reported and any thoughts on a possible way around this? Assume there's not much we can do because it's an Excel issue, so just have to communicate it to API users? 🤷‍♂️

**Comment by geohacker** [comment]
This could be an Excel issue, as Excel is notorious for encoding related problems during export.  I think exporting as utf-8 should fix to a large extent, but really it's hard to say until we try.

It's also worth noting that this could happen from within in the shapefile. Depending on what software is used and how it's exported or saved.

The problem is a bit beyond just the users seeing garbage. We use the name as a key to match when adding new districts in the management command and it makes it difficult to find a proper match a lot of the times. Hopefully we can address them manually by editing in the django admin?

cc @batpad

**Comment by jhenshall** [comment]
The data seems correct in the backend and the shapefile and I can't replicate the issue anywhere except when opening the CSV in Excel (and even then it can be avoided by importing the CSV using UTF-8).

Do we not specify UTF-8 when exporting CSV from the API then? I know that they don't have a .csv extension, so I normally add it on manually, which might mean the wrong encoding is applied. As you say, would be great to try and see!

cc @geohacker @batpad

**Comment by geohacker** [comment]
@jhenshall if the shapefile you've seems correct then we don't have to worry. I ran into this with the shapefile I got from Guido and Tekla back when we did the first pass of geo data cleanup. 

The CSV exports definitely enforce utf-8, right @batpad?

**Comment by batpad** [comment]
The CSV export seems to be correctly utf-8 encoded, so I would put this down to likely an Excel issue using a different default encoding?

**Comment by jhenshall** [comment]
So this [seems to be a common issue](https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically) and I'm assuming there is no tech fix because working as expected on our end? Perhaps just user guidance for opening these CSVs with Excel as part of API documentation? Bit annoying but not sure what else we can do!

Technically, I guess we can just close this ticket @geohacker @batpad ?

 cc @JonathanGarro - as this might overlap with your API work?

**Comment by jhenshall** [comment]
As described above, this is an Excel encoding issue, so closing this. This limitation should be communicated.
