### ISSUE TITLE
Add `deprecated` field to countries and districts

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1547]
**Is your feature request related to a problem? Please describe.**

There are often cases when we need to deprecate countries and districts in the GO database. For example, sometimes new districts are formed by splitting existing districts, and sometimes the country boundary stances change. 

These situation poses a bit of challenge for existing reports. They should continue to work and the links shouldn't break. But we don't want users to add reports to non-existent districts anymore. 

**Describe the solution you'd like**
For this purpose, we will introduce a deprecated flag on countries and districts.

The country and district list endpoints will filter these deprecated entities out so the front-end always shows the most accurate information. The deprecate flag can be modified by super users in the django admin.

cc @batpad @jhenshall

**Comment by geohacker** [comment]
This is in staging now. cc @jhenshall would be great if you can try this out and make sure it's doing the right thing :) Thanks!

**Comment by jhenshall** [comment]
Initial check looks good @geohacker! But will dig in some more for edge cases and possible breakages of linked reports.

**Comment by jhenshall** [comment]
Just noting here that the country and district lists in the backend still show entries that have been deprecated. This may actually be desirable because it gives admin users the ability to link to old countries and districts if needed but I'm not certain there is a use case for that. Could definitely lead to confusion but guess not many people can/will be making changes directly in the backend. Open for discussion but putting here for reference. cc @geohacker
