### ISSUE TITLE
[PROD] Dashboard not publishing in Emergency page (Probs an RTE issue?)

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#1622]
## Issue
Having issues publishing a PowerBi dashboard in an emergency page, issue encountered by IM delegate in the field, I try to published the dashboard from my side which worked here https://go.ifrc.org/emergencies/3067#dashboards but not here https://prddsgoproxyapp.azurewebsites.net/emergencies/3067#dashboards, also, it seems I am the only one who can actually see the dashboard form the second link.

## Steps to reproduce
Go to https://prddsgoproxyapp.azurewebsites.net/emergencies/3067#details, click on edit event and try to add an iframe into the snippets section.

*If applicable, add screenshots to help explain your problem.*
PLeas enote the different urls in the screenshots:

![image](https://user-images.githubusercontent.com/69478743/94046106-8a16db00-fdd0-11ea-9ba4-bb389d5b44a4.png)
![image](https://user-images.githubusercontent.com/69478743/94046156-9b5fe780-fdd0-11ea-9c20-5eb58c706d0b.png)
![image](https://user-images.githubusercontent.com/69478743/94046207-b29ed500-fdd0-11ea-8374-b0fb057dbe42.png)

## Expected behaviour
The dashboard should be published.

## Related feature
*Please cross-reference the build item to which this relates, if known/relevant*

## Impact
I am not sure if the issue is only related to this emergency page or to all of them, so possibly all of the users?

## Severity
Functional impact to a field operation

## Is there a workaround?
No

**Comment by batpad** [comment]
@GregoryHorvath would you be able to take a look into this one?

**Comment by anamariaescobar** [comment]
Hi team!  I have been doing so more tests on this, and it seems that the dashboard only appears when you select Spanish as a language

**Comment by GregoryHorvath** [comment]
@anamariaescobar I've quickly checked the History of the record on the backend, and it shows to me that you removed the `<iframe>` around ~2:15PM yesterday (server time I believe) so that's why it's not showing up. I tried to reproduce but when I added the `<iframe>` via the Ember or Source Code insert features: 
![image](https://user-images.githubusercontent.com/30079559/94117625-bff9a500-fe4c-11ea-838e-8c60bcaa04b5.png)

it was showing up for me.

On a side-note I noticed some dev-text showing up after deleting a snippet instead of it being empty so I'll deploy a hotfix for that.

**Comment by GregoryHorvath** [comment]
> Hi team! I have been doing so more tests on this, and it seems that the dashboard only appears when you select Spanish as a language

Wow, nice catch, yea I see it working now in Spanish.

**Comment by batpad** [comment]
This was a really good catch and caught a bit of a fundamental problem with how we are managing translations for users working in the Admin area, due to us no longer doing automatic translations.

The problem is now that if you have a language other than english (eg Spanish) selected in the Admin, and don't click the Show All Languages button, it will save the data you enter as Spanish. Then, on the frontend, if you are viewing it in English, it will show up as empty since there is no data for English.

Per conversation with @GregoryHorvath @tovari and @guipizzini, what we propose to do here is two things:

 - Ensure that the API and frontend always fallback to whatever language data is available in. So, if a field has French data, for eg. but no other language, it will always show the French data to all users instead of empty.

 - Always show all language fields to users in the Admin, without the option to hide. This will make it more explicit for users which language they are saving data for, and allow the user to make their own choice around managing translations in multiple languages. Of course, users will always be able to leave translation fields empty, and then it would fall back to whichever language fields have data. (An exception being some fields like the Name of an Emergency requiring the `name_en` field to be filled).

Will update here when this is ready for testing. Thank you again for the catch @anamariaescobar 

cc @GregoryHorvath @tovari @guipizzini @LukeCaley @thenav56

**Comment by GregoryHorvath** [comment]
@anamariaescobar I believe this was fixed with some workarounds a couple of weeks/months ago? Sorry I'm not sure anymore if there are any more action points left to do here or if we missed anything, please confirm / close if possible.

cc @batpad

**Comment by anamariaescobar** [comment]
It was fixed, it was an issue with the translations, closing this ticket now.
