### ISSUE TITLE
[PROD] Registration error 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1645]
## Issue
*I cannot complete the registration of a non-whitelisted email as an error message states that I must submit 2 valid emails..*

## Steps to reproduce
*Try to register with a non-whitelisted email.*

![image](https://user-images.githubusercontent.com/68283148/95435449-e2aeb200-0952-11eb-8e9f-13809463e202.png)

## Expected behaviour
*It should complete the registration*

## Impact
*Not possible to complete registrations*

## Severity
*Severe*

## Is there a workaround?
*-*

**Comment by tovari** [comment]
The registration can be completed if the emails are written in lower-case letters. Emails shouldn't be case sensitive.

**Comment by GregoryHorvath** [comment]
Deployed the possible fix to staging.

**Comment by nanometrenat** [comment]
Hi, Nat here (hello!), just to say that whereas it USED to be that verifiers had to be people with admin site access (i.e. is_staff ticked, not necessarily IFRC staff though), I have just tried registering with two verifiers who are ordinary National Society users with no admin access and it let me proceed.

This might perhaps actually be too wide now - as it means that e.g. two volunteers with non-whitelisted email addresses can be verifiers for absolutely anyone else that wants to join.  But will leave it to you guys to consider the options.

FYI the reason I have noticed this is that whereas before (for quite some time) NZRC ITTERU volys couldn't register at all because no-one currently working at NZ Red Cross has GO admin access, now NZRC ITTERU volys can register by putting my personal (non-IFRC user) email address as one of their verifiers - so that is great to get them moving.

HOWEVER FYI the "Reference to approve an account" email that comes to verifiers says "Dear IFRC Staff, ..." - so this wording should probably be changed to "Dear GO user" because as stated it seems that the verifier doesn't have to be staff of anything (IFRC or NS) at all any more...

**Comment by GregoryHorvath** [comment]
@tovari The original thing in the ticket should've been resolved via 'Release/v4.4.6' where we made those email validations case-insensitive. What I understood from @nanometrenat's comment I got that's a separate issue/questions on how we want to handle those specific scenarios. I'd suggest we close this ticket and open another one by someone who can spec it out, please.

**Comment by tovari** [comment]
I close this as the requested update has been completed. We will consider Natalies notes when doing the registration process review.
