### ISSUE TITLE
Account page / Login / Registration UX/UI clean up.

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1663]
https://github.com/IFRCGo/go-frontend/issues/1336 
https://github.com/IFRCGo/go-frontend/issues/1337

UX/UI update of the Login / Registration / Account screens and flows, based on the current implementation.

**Comment by mariam-yu** [comment]
@LukeCaley @batpad @GregoryHorvath we updated the UI for Login/Register/Account flows. It's quite close to the current, with a clean up and UI upgrade. 

**Login flow**: https://projects.invisionapp.com/share/XGZAM2UYBDQ#/screens/436434660 (same PW) 
The key proposal here is to add a "Keep me logged in" and one "forgot password", since the username is the email.

**Register flow**: https://projects.invisionapp.com/share/XGZAM2UYBDQ#/screens/436434659
Cleaned up UI with split account and org. information. Also, as discussed email is now the username to login.

**Account flow 3 tabs**: https://projects.invisionapp.com/share/ZKZAM2CYCN4#/screens/436159218_7-1_GO_Account_Info
Account Information - updated layout for operations following and account information.
Notifications - updated UI 
PER forms - cleaned up UI with more organized sections (new forms, completed forms), as well as buttons to access the new forms. Click on the first one to see an example of how we propose to have the forms layout (similar to field reports).
Also proposing to make the countries under completed forms collapsible to make information more concise.

Please let us know your thoughts. @LukeCaley if all ok, we will add these screens to the main prototype and drop them to Zeplin. Thanks!

**Comment by LukeCaley** [comment]
Thanks @mariam-yu  - all looks great to me.

In terms of the shift to using `email` instead of `username` - we need to ensure that we are not changing desired behaviour without explanation or support.  _"I am used to logging in using my username - why have you changed this?"_ For instance, what happens if I enter my old username in the email field?

It would be good to know how complex some of the implementation is for the collapsible country checklist (if too significant let's not shoot too high for something which should be a one-time experience for users) but I like the idea.

**Comment by mariam-yu** [comment]
@LukeCaley Thanks for your quick feedback. Agreed with the comments.

For username, @batpad @GregoryHorvath could we use the same field (email / username) for login for a time being till we migrate and have users get used to it?

For the accordion, I'll let @batpad to react to. We do have a similar functionality on the 3Ws so may be we could reuse the component? Just a thought.

**Comment by tovari** [comment]
Thanks @mariam-yu, this looks good.
I think, its worth to review the UX workflows as well. E.g. The user should be able to get information about his registration process status (i.e. confirmation email has been sent/ not confirmed by the 2 RC users yet, etc). What happens, if the user doesn't receive the confirmation email, etc.?

**Comment by mariam-yu** [comment]
@tovari Makes sense to review those flows as well. I will add them to the backlog, and we will go through them as well.

**Comment by GregoryHorvath** [comment]
> **Login flow**: https://projects.invisionapp.com/share/XGZAM2UYBDQ#/screens/436434660 (same PW)
> The key proposal here is to add a "Keep me logged in" and one "forgot password", since the username is the email.

- Keep me logged in: I'm not familiar with how we manage the logins fully. I most probably encountered some parts of the code and vaguely remember seeing some function which refreshes a date with every login. I'll have to double check.
- Username/email: I'd say the best here would be to add the `email` *besides* the `username` as a valid login parameter instead of just switching straight to email.
If we really would want to deprecate the `username` that would be a bigger work (I could be wrong, but I believe in most cases we use the `username` to identify users) cc @batpad .
- Forgot password (and others): I also would like to keep the other functions, at least the "Re-send validation email" which came to be really useful if someone-somehow (by a bug in the code, or the exchange server, whatever) didn't get their registration validation email. If we deprecate the `username` obviously we won't need the "I forgot my username" one.

> PER forms - cleaned up UI with more organized sections (new forms, completed forms), as well as buttons to access the new forms. Click on the first one to see an example of how we propose to have the forms layout (similar to field reports).
> Also proposing to make the countries under completed forms collapsible to make information more concise.

This is the current version I have while rewriting the PER module:
![image](https://user-images.githubusercontent.com/30079559/98089088-90de4680-1e82-11eb-8921-29e9d46c36dd.png)

Now the Country (National society) selector is moved inside each New Form creation (Area X buttons). I believe this way it would be more clear for users that the dropdown is there to set the Form's country and not just a filter or something.
And currently a Form looks like this:
![image](https://user-images.githubusercontent.com/30079559/98089698-650f9080-1e83-11eb-812c-fecf4f9ba614.png)

@mariam-yu @tovari @batpad

**Comment by mariam-yu** [comment]
Thanks @GregoryHorvath Some comments below: (Also CC @batpad )

- For username and email could we use the same field? So, on registration part we remove the username so all the new users go with email. On the login screen we have one field for both (username/email) so the users can enter either or. Would that work? Sort of like this one (an example from molnix): 
<img width="307" alt="Screen Shot 2020-11-04 at 3 19 15 PM" src="https://user-images.githubusercontent.com/60006476/98558560-de551c00-22a5-11eb-9f32-1018bd7d6657.png">
- If that's the case, we can have the forgot username and password flows (both) for users who don't know, but may be one link for both? We can discuss those flows separately.
- PER: we talked about it, so will be sending you updated wires for the Account based on the discussion.

Thanks!

**Comment by mariam-yu** [comment]
@batpad Posting here, as it's sort of an update to Account page, even though related to PER. As Greg is off, do you mind taking a look to see if the flows capture what we discussed in our call? https://invis.io/79ZEX1DYX3A#/357319251_7-3_Account_PER

1 - Main PER Forms page is simplified with one button to one form-flow (Overview, Areas, etc.).
2 - The Completed PER Assessments section is simplified as we don't need to display the forms separately, but added a few more details about each assessment (e.g. date, etc.).
3 - The form itself has the following flow/logic:
- - - Starts with Overview and other tabs (Areas) are inactive.
- - - Click on the form to fill out critical information (e.g. NS, date, etc.); this will update the title with the country + date (we can have a standard format).
- - - Clicking Save and Continue (to make sure they don't lose the entered info on each step) activates all the Areas, since Overview is filled in. Now you can toggle back and forth between areas and enter whatever is needed. The entered ones will have a checkmark. (plz note we used a screenshot of the form for Area 1 to save time, but the styling proposed will be the same - similar to field reports).
- - - At the end when completed Submit and Close.

(cc @GregoryHorvath  cc @maisa-yu )

**Comment by GregoryHorvath** [comment]
> Thanks @GregoryHorvath Some comments below: (Also CC @batpad )
> 
> * For username and email could we use the same field? So, on registration part we remove the username so all the new users go with email. On the login screen we have one field for both (username/email) so the users can enter either or. Would that work? Sort of like this one (an example from molnix):
> 
> <img alt="Screen Shot 2020-11-04 at 3 19 15 PM" width="307" src="https://user-images.githubusercontent.com/60006476/98558560-de551c00-22a5-11eb-9f32-1018bd7d6657.png">

@mariam-yu Wow this is a great idea, I think we can totally go with this. I'll have to check around if there's anything that blocks this approach but there shouldn't be any.

> - If that's the case, we can have the forgot username and password flows (both) for users who don't know, but may be one link for both? We can discuss those flows separately. - PER: we talked about it, so will be sending you updated wires for the Account based on the discussion.
> Thanks!

Yep I think it would be better to discuss those separately, thanks.

**Comment by mariam-yu** [comment]
@GregoryHorvath Updated in this designs :) https://projects.invisionapp.com/share/F7ZFXL1NB9P#/screens/436434660_0-1-2_Login_3

**Comment by mariam-yu** [comment]
@GregoryHorvath As discussed, the UI for the wires: https://projects.invisionapp.com/share/T8ZFOR82PHZ#/screens/436159221 To summarize our discussion between you, me and Marco, the flow may change once we tackle the integration of the tool. For now the proposal is to have tabs for the form. You will see if this is challenging technically, then we can use your current version and improve on it later on. Thanks!

**Comment by GregoryHorvath** [comment]
@mariam-yu Thanks for summarizing these! I'll follow these as close as I can and once I'll have something up for testing we can improve from there I think.

**Comment by mariam-yu** [comment]
@GregoryHorvath The account page PER forms flow is added to Zeplin: https://zpl.io/2GrkpwW Let us know if you have any questions!

**Comment by GregoryHorvath** [comment]
@tovari A version of this is deployed to staging by now, which allows both `username` and `email` logins, and has the registration page changes.

cc @mariam-yu

**Comment by karitotp** [comment]
> @tovari A version of this is deployed to staging by now, which allows both username and email logins, and has the registration page changes.

It is working correctly.
