### ISSUE TITLE
Design changes for Deployments and Surge Alerts updates

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1666]
When we integrate with Molnix for Surge Alerts and Deployments data, we also want some design changes on the Deployments pages and sections.

Wireframes for the updated Deployments page: https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/432110770

@imohkay - am assigning this to you. Let's start looking at the wireframes and the existing site to map changes. Currently, on staging, we don't have data on Deployments and Surge Alerts to be able to see what it looks like currently. Am going to work with @anamariaescobar to try and get some test data in the system soon.

The only big addition here seems to be the chart next to the deployments table showing the timelines of various personnel deployments with the info on mouse-over. @imohkay - it may make sense to start looking around for a chart implementation that might fit this need?

@mariam-yu please add anything here that I may have missed re: design changes across surge alerts and deployments. Thanks!

**Comment by imohkay** [comment]
@mariam-yu Big hi! I had a few questions.

1. The Invision file doesn't show ERU DEPLOYMENT TYPES and NUMBER OF DEPLOYMENTS BY NS. Is that intentional?
2. Where should the link "Sign up for Surge Notifications" go to? @batpad 
3. The Deployment key figures have small info icons on the bottom right. Is there some specific info that needs to go there?

**Comment by mariam-yu** [comment]
@imohkay Big hi back! So, to be honest these wires are super old, and I was hoping to figure out some details with Ana Maria next week (as she is off this week). I don't think the changes will be big, but to figure out some details as you mentioned.

1 - Where would you expect to see ERU Deployment types and number of deployments? Or is this just the data you have?
2 - I think this would take to the notification page as there on the bottom we have surge notifications customization.
3 - The last graph for ERUs will change; so, if possible could you tackle that last after I discuss with Ana Maria?

Thanks so much!

**Comment by imohkay** [comment]
@mariam-yu Hey, so let me know once you figure stuff out with Ana Maria.
For point 1, the ERU deployment types, it currently exists on the site, so I was wondering whether we aren't showing that data anymore.

**Comment by mariam-yu** [comment]
@imohkay Yap! Syncing with Ana Maria tomorrow morning and then I think we have sync together in the afternoon. So, we should have this figured out by then.

**Comment by mariam-yu** [comment]
@batpad @imohkay Please see the wires for Deployment updates:
Surge Deployments page: https://invis.io/B3XKVKZJWY9#/361601984_5-1_GO_Deployment (p.s. kept a screenshot of the ERUs lower module as we won't be touching it this round).
Emergency page: Surge tab: https://invis.io/3QXKWXWTAHF#/414729370_4-3-4_GO_Specific-Emergency_Epi

@anamariaescobar could you please verify if all is correct as per our conversation? If so, we will quickly move to the UI (CC @maisa-yu )

Thanks!

**Comment by anamariaescobar** [comment]
@mariam-yu well noted! Having a meeting today with the Surge team to go over the wires. Will have the feedback ready tomorrow morning! maybe we should have a meeting about it?

**Comment by mariam-yu** [comment]
> @mariam-yu well noted! Having a meeting today with the Surge team to go over the wires. Will have the feedback ready tomorrow morning! maybe we should have a meeting about it?

@anamariaescobar Sure! let me know what you learn and we can hop on a call. Thanks!

**Comment by anamariaescobar** [comment]
Hi @mariam-yu and @batpad !  The Surge team was very happy with the designsss!! Some comments below:

**Deployments page:**

- The title and name of the tab should be only Surge.

- Can we add a Key figure with the # of NS providing RR personnel?

- In the graphs below the map, are these graphs related to RR personnel, right? The surge team would like to have this graphs cumulative for the present year (showing 2020 and not only active ones), also they want to clarify in the tittle that it reflect RR personnel and the timeframe.

- In the open alerts, on the surge type, it should be Rapid Response Personnel instead of Personnel or ERU.

- In the open alerts we should add a "status" column to indicate when an alert is being stand down.....Molnix is working on developing this option in their platform, so we aren't getting this data yet, but it is an important one.

- Surge overview by emergencies: We should change the title to Deployments overview by emergencies.

- Surge overview by emergencies: The link that says View Deployments goes to the emergency page? we should change the name to the actual emergency (just like in the open alerts).

- Surge overview by emergencies: just to check, this will only shows the active deployments and then if someone is interest in past deployments they could go to View all personnel and ERU deployed, right?

**Emergency page:**

- Can we add some Key figures at the beginning? Active Rapid Response Personnel deployed, Total Rapid Response Personnel deployed and # of NS providing RR personnel?

- Open Surge Alerts: There should be a View all open alerts for this section?

- Open Surge Alerts: Same comment as in the deployment page, can we add a "status" column to highlight the stand downs?

- Open Surge Alerts: Same comment as in the deployment page, surge type should be Rapid Response Personnel or ERU.

- Deployed Rapid Response Personnel: maybe changing the tittle to Rapid Response Personnel Deployed (I think it sounds better, but English is not my first language, so I don't know if its correct).

- Deployed Rapid Response Personnel: Change Deploying party to Deploying NS

- Deployed Rapid Response Personnel: Only active deployments should appear here, if someone wants to see all the historic should go to view all deployed personnel.

- Deployed ERU: There should be a View all open alerts for this section?

- Deployed ERU: Same as above, change the title to ERUS Deployed (?)

- Deployed ERU: Remove the Personnel and Equipment column.

@mariam-yu please let me know if you think we should have a call about this!

**Comment by mariam-yu** [comment]
@anamariaescobar All the comments look good. No big questions. A few things:
- We can change the entire section to Surge instead of Surge Deployments, but would it be as clear and explicit to outside people? I know this section is password protected, but wondering is Surge is enough.
- _Surge overview by emergencies: just to check, this will only shows the active deployments and then if someone is interest in past deployments they could go to View all personnel and ERU deployed, right?_
Yes, we can do that. The big list can go as far back as they have data. Basically, the front page will show aggregate by emergencies, but view all will show all deployments in detail across all emergencies. Hopefully, we can add filters to that section too, but not sure if that's for later.
- _Deployed Rapid Response Personnel: Change Deploying party to Deploying NS_
I think we initially name it party since there were some IFRC, ICRC, and not just NS. Is that the case?

Thanks! Should be able to update this tomorrow early on. @batpad so wires will be complete sometime tomorrow and UI on Friday. Is that fine? No big changes, so probably you could move forward with what we have now already. Thanks!

**Comment by mariam-yu** [comment]
@anamariaescobar One more question I missed: what does it mean "when the alert is being stand down"? We have application deadline, why do the users need to see when the alert will be removed? If I understood it correctly, it will only add to the confusion. Thanks!

**Comment by mariam-yu** [comment]
@anamariaescobar @batpad Wireframes updated, pending a few questions mentioned above:
Main Surge page: https://invis.io/B3XKVKZJWY9#/361601984_5-1_GO_Deployment
Emergency Surge page: https://invis.io/3QXKWXWTAHF#/414729370_4-3-4_GO_Specific-Emergency_Epi

**Comment by anamariaescobar** [comment]
@mariam-yu answers to your questions:

- We can change the entire section to Surge instead of Surge Deployments, but would it be as clear and explicit to outside people? I know this section is password protected, but wondering is Surge is enough. **Checked with the team, and Surge is enough.**

- Surge overview by emergencies: just to check, this will only shows the active deployments and then if someone is interest in past deployments they could go to View all personnel and ERU deployed, right?
Yes, we can do that. The big list can go as far back as they have data. Basically, the front page will show aggregate by emergencies, but view all will show all deployments in detail across all emergencies. Hopefully, we can add filters to that section too, but not sure if that's for later. **Amazing**

- Deployed Rapid Response Personnel: Change Deploying party to Deploying NS
I think we initially name it party since there were some IFRC, ICRC, and not just NS. Is that the case? **Checked with the team, Deploying Organization would be better.**

When an alert is being stand down it means that either they couldn't find someone that meet the requirements or that the emergency doesn't require that profile anymore. It is required to show this status.

Will review now the wireframes :)

**Comment by mariam-yu** [comment]
@anamariaescobar Thanks for your answers. The wireframes are now updated and should include all the things you mentioned. Regarding the status, though, I'm a bit hesitant (even though it's in the wires). What other statuses would it include? Would it be only Open or Stood Down (is this correct?)? I also assume stood down is not as common (?) so would it mostly be open? Alternatively, we can call the section Active alerts and have open, filled in, etc as statuses, but then it becomes blurry what active means. Anyway, thought I check. Thanks!

Surge page: https://invis.io/B3XKVKZJWY9#/361601984_5-1_GO_Deployment
Emergency Surge tab: https://invis.io/3QXKWXWTAHF#/414729370_4-3-4_GO_Specific-Emergency_Epi

@batpad wires are all good to go, aiming to send UIs to Zeplin tomorrow (CC @maisa-yu )

**Comment by anamariaescobar** [comment]
Hi @mariam-yu, the wires look good!
Regarding the status, yes, it will be Open or Stood down, actually stood down positions are a common thing, I guess at least a couple per each operation, Filled won't be an status as once the alert has been filled it will transition to deployed personnel.

Thank you so much for this!

**Comment by mariam-yu** [comment]
@anamariaescobar Great! Then the wires are done; we will be updating the UI today. I'll post it here.

**Comment by mariam-yu** [comment]
@batpad UI is completed for Deployments:
Specific emergency - Surge tab: https://zpl.io/adOPdRn
Surge tab on main nav: https://zpl.io/2GrMKB9

Let us know if any questions.

**Comment by batpad** [comment]
cc @imohkay ^

**Comment by karitotp** [comment]
- One of the header in the DEPLOYED PERSONNEL table is missing: https://dsgoproxyapp.azurewebsites.net/emergencies/4054#rapid-response
![Selection_004](https://user-images.githubusercontent.com/11504548/102151125-2d134a00-3e40-11eb-9697-008509d23b7d.png)

- Also there are some issues with Arabic language
![Selection_005](https://user-images.githubusercontent.com/11504548/102151592-2802ca80-3e41-11eb-9ea6-3176e258d9da.png)

cc. @batpad

**Comment by batpad** [comment]
@imohkay can we look at these? The table header I think we need to remove those two arrows and just leave it blank, and then deal with the RTL issues on Arabic.

**Comment by imohkay** [comment]
> * One of the header in the DEPLOYED PERSONNEL table is missing: https://dsgoproxyapp.azurewebsites.net/emergencies/4054#rapid-response
>   ![Selection_004](https://user-images.githubusercontent.com/11504548/102151125-2d134a00-3e40-11eb-9697-008509d23b7d.png)
> * Also there are some issues with Arabic language
>   ![Selection_005](https://user-images.githubusercontent.com/11504548/102151592-2802ca80-3e41-11eb-9ea6-3176e258d9da.png)
> 
> cc. @batpad

@karitotp Hey, for the Arabic issue, could you let me know which in emergency you are facing the issue?

**Comment by imohkay** [comment]
> > * One of the header in the DEPLOYED PERSONNEL table is missing: https://dsgoproxyapp.azurewebsites.net/emergencies/4054#rapid-response
> >   ![Selection_004](https://user-images.githubusercontent.com/11504548/102151125-2d134a00-3e40-11eb-9697-008509d23b7d.png)
> > * Also there are some issues with Arabic language
> >   ![Selection_005](https://user-images.githubusercontent.com/11504548/102151592-2802ca80-3e41-11eb-9ea6-3176e258d9da.png)
> > 
> > cc. @batpad
> 
> @karitotp Hey, for the Arabic issue, could you let me know which in emergency you are facing the issue?

Never mind, I found an emergency:)

**Comment by karitotp** [comment]
> - One of the header in the DEPLOYED PERSONNEL table is missing: https://dsgoproxyapp.azurewebsites.net/emergencies/4054#rapid-response
![Selection_004](https://user-images.githubusercontent.com/11504548/102151125-2d134a00-3e40-11eb-9697-008509d23b7d.png)
> - Also there are some issues with Arabic language
![Selection_005](https://user-images.githubusercontent.com/11504548/102151592-2802ca80-3e41-11eb-9ea6-3176e258d9da.png)

The above issues were fixed and all looks good now.

**Comment by anamariaescobar** [comment]
Hi @batpad, summary of our meeting last week:

- [ ] Change oh the graphics, already described in ticket #1833 
- [ ] Move deployed ERUS below Deployments overview by Emergencies
- [ ] Not show 0 deployments in Deployments overview by Emergencies and only show the active deploying organization, described in ticket #1836 
- [ ] Not show "hidden" positions coming from Molnix
- [ ] Cross check the list of NS between Go and Molnix
- [ ] Today line for rapid response personnel deployed in the surge tab of an emergency is not shown correctly, issue described in ticket #1837
- [ ] Fix the map (I dont remember if I should create a ticket for this one)
