### ISSUE TITLE
[PROD] Appeal Country info gets overwritten

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1671]
## Issue
The 'Central America - Hurricane Eta' appeal is incorrectly linked to Haiti. The country information can be updated though on the admin site, but gets overwritten again in a short time.
https://goadmin.ifrc.org/api/v2/appeal/?code=MDR43007

## Expected behaviour
*We should be able to update the Country information and keep this update. We would like to change the country to Panama in this case*

*
Data in Apple:
![MDR43007](https://user-images.githubusercontent.com/68283148/98809497-ecc64380-241d-11eb-9523-6e68b6fad4ce.PNG)
*

## Impact
*Currently a lot of attention is on the Eta related data.*

## Severity
*Severe - due to the user attention and expectations.*

## Is there a workaround?
*No*

**Comment by batpad** [comment]
This seems to be due to this mapping of `CAM` to Haiti: https://github.com/IFRCGo/go-api/blob/develop/api/management/commands/ingest_appeals.py#L25

cc @jhenshall @geohacker - I'm really not *sure* what we arrived at as the best way to handle things linked to regional offices, etc. - @jhenshall feel free to ping me on Teams if you have a minute to chat about this and figure out the best solution here.

**Comment by GregoryHorvath** [comment]
@tovari @jhenshall The above change from @batpad was merged into production some time ago, could you please validate if this is fixed?

**Comment by tovari** [comment]
Thanks @GregoryHorvath, it is definitely fixed.
