### ISSUE TITLE
Release 4.5.0 - mid-December, 2020

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1740]
Creating a ticket to try and bring all the small remaining action items for this release into a single place with clear assignees, and also to outline all the changes going into this release, to serve as the basis for the release notes and Changelog.

### Map Styling Updates: https://github.com/IFRCGo/go-frontend/issues/1202

Map styles and popups have been updated per design. Remaining actions:

 - ~~Remove the behaviour to highlight countries on hover (retain functionality to click on countries) - @geohacker~~
 - ~~Address @mariam-yu's feedback on Popup styling - https://github.com/IFRCGo/go-frontend/issues/1202#issuecomment-741780538 - @imohkay~~
 - ~~Adjust legend colours as per new colours on map / design (no need to adjust the legend design for this release, just make sure the colours are correct and correspond to the colours on the map) - @imohkay - to ask @geohacker for any clarifications.~~
 - Minor changes to map styles for disputed borders, etc. - @geohacker, is this actually pending?

### Geo-data Imports - https://github.com/IFRCGo/go-frontend/issues/1643

@geohacker and @jhenshall are working through CSVs and shape-files, mostly tracked here: https://github.com/IFRCGo/go-frontend/issues/1643#issuecomment-735389178

### Mapbox Vector Tile Update: https://github.com/IFRCGo/go-frontend/issues/1474

Backend work to generate tiles on Mapbox based on the spatial data in GO is complete and map tiles can be viewed on Mapbox. We will not make the frontend change to point production to the new tileset right away as it will need more validation, testing and approval. @jhenshall - it will be good if you could go through the generated tilesets on Mapbox and verify / confirm that the data is being output from GO correctly, and is complete.

### PER Refactor: https://github.com/IFRCGo/go-frontend/issues/1667

This has been a massive lift and @GregoryHorvath has led out completely re-writing the PER forms module, accommodating various changes to data structure and design based on feedback from the PER team. Basic functionality of filling in forms and saving, viewing and exporting has been tested. There are some remaining items TODO:

 - ~~Add subcomponents - @GregoryHorvath~~
 - ~~Add a permissions model so not all users can view all PER forms - @GregoryHorvath~~
 - ~~Fix styling for checkboxes - @GregoryHorvath to reach out to @imohkay with details of what is needed here.~~
 - ~~@GregoryHorvath - let me know anything else I'm missing and I'll add it here.~~
 - After above fixes in place, another thorough round of testing. - @karitotp 

### PER Dashboards: https://github.com/IFRCGo/go-frontend/issues/1669

I believe this is all done. @GregoryHorvath to update if there are any pending items, and ideally then assign them to @imohkay .

### Molnix Integration / Updates to Deployments and Surge Alerts - https://github.com/IFRCGo/go-frontend/issues/1638

Backend script to ingest data from Molnix is on staging. Final changes to handle Stand-Downs have been deployed as well and can be tested - cc @anamariaescobar 

Items remaining on the frontend:

 - ~~Deployments table with redesign on emergency pages (close to done) - @batpad~~
 - ~~Create table with grouping by emergency on the deployments page - @batpad~~
 - ~~Create simpler table view on All Deployments table - @batpad~~

###  Emergency Page Redesign: https://github.com/IFRCGo/go-frontend/issues/1243

This is ready to test on staging.

Pending items:

 - ~~Fix styling of Key Figures next to map when emergency does not have a map - https://github.com/IFRCGo/go-frontend/issues/1243#issuecomment-742259894 @imohkay~~

### Assorted Items and Bugfixes

 - ~~Bugfix for missing months on graphs on region pages: https://github.com/IFRCGo/go-frontend/issues/1398 - @kamicut DONE~~
 - ~~Add option to hide map on emergency page: https://github.com/IFRCGo/go-frontend/issues/1397 - @kamicut (Pull request awaiting merge, pending testing).~~
 - ~~Update footer styles: https://github.com/IFRCGo/go-frontend/issues/1706 - @imohkay DONE~~
 - ~~Surge Calendar link on Resources page: https://github.com/IFRCGo/go-frontend/issues/1723 - DONE~~
 - Fix field report table in Arabic: https://github.com/IFRCGo/go-frontend/issues/1616 - @kamicut 
 - ~~The collecticons trash-bin icon looks broken, can be viewed on Field Report Step 2 - @imohkay could you look at this? Happy to create a separate ticket.~~

@GregoryHorvath @geohacker @imohkay @kamicut - let me know if there's anything that is remaining for this release or that is in this release that I may have missed in the notes above, also if you need support with any of the things assigned to you in the above list.

@tovari @LukeCaley @mariam-yu - will be good to go through and check that we are not missing anything here that is expected or expected to be fixed for this release. The above looks like a lot, but it's mostly final touches pending. Will be good to go through, make sure we are able to start testing and providing feedback on everything that is on staging, and ensure that we are well placed to have these last remaining items in by Monday at the very latest, ideally as much as possible by end of day today (apart from the geo-data imports that may take a few more days, as discussed).

Thank you all for the incredible work and support over the past weeks - let's make this final push to get the final release of the year over the line.

**Comment by batpad** [comment]
@imohkay @geohacker - updated above with line item to adjust colours of the Legend on the map. @imohkay - please reach out to @geohacker if there's confusion on what those colours need to be, etc. Thank you!

**Comment by GregoryHorvath** [comment]
@batpad I'd say since the subcomponent changes are more of an import logic change so we shouldn't aim to push those to staging because it would mean a total wipe to test the imports (or we could do this on Monday and until that let the users test the current version).

The permission changes have been pushed to staging just recently.

**Comment by batpad** [comment]
@GregoryHorvath could you outline what those subcomponent changes mean for a user? i.e. like, expect X to not work correctly until this is done?

**Comment by GregoryHorvath** [comment]
@batpad 
Basically there's one exact component which is the number 14 on Area 3 which has these subcomponents indicated by letters from A-N. Each individual of those should have a benchmark (and EPI if ticked) question which won't be present on staging with the current setup.

The other one would be number 34 on Area 5, but those actually have no differentiation with letters and don't require individual benchmark / EPI questions. I was planning a manual update for these since all questions are connected to the main/first number 34 component. We could somewhat automate this in the import script but it would still be hardcoded and would also rely on having order of questions 110% correct in the CSVs.

**Comment by mariam-yu** [comment]
@batpad @imohkay (CC @maisa-yu ), for popups, a few minor things:
- The arrow looks off, would be good to use the one we have on Zeplin if possible.
- The font seems bigger (16 instead of 14).
- There is a separator line between various emergencies in the popup.
- At which height does a scroll bar appears? We have roughly 230px in Zeplin.
- The top part of the popup could be a tad smaller in height (before the country name).
- We still, I think, need to sync on font-weights across, as I'm not sure whether they match accurately Zeplin, but may be @imohkay and @maisa-yu an do a quick matching exercise and then we can have it standard across.

Thanks!

**Comment by imohkay** [comment]
> @batpad @imohkay (CC @maisa-yu ), for popups, a few minor things:
> 
> * The arrow looks off, would be good to use the one we have on Zeplin if possible.
> * The font seems bigger (16 instead of 14).
> * There is a separator line between various emergencies in the popup.
> * At which height does a scroll bar appears? We have roughly 230px in Zeplin.
> * The top part of the popup could be a tad smaller in height (before the country name).
> * We still, I think, need to sync on font-weights across, as I'm not sure whether they match accurately Zeplin, but may be @imohkay and @maisa-yu an do a quick matching exercise and then we can have it standard across.
> 
> Thanks!

@mariam-yu Could you check the popups now? Most things should be fixed. The only issue is the arrow. We are using the Collecticons chevrons across the site (top, bottom, right, left). Would it be okay to only have the chevron different for the map?
When I tried to extract that SVG on zeplin, it said it wasn't part of a component and I wasn't able to do so...

**Comment by tovari** [comment]
https://github.com/IFRCGo/go-frontend/issues/1243#issuecomment-744074699

**Comment by mariam-yu** [comment]
@imohkay Thanks for giving it a try. Consistency is more important; so, let's keep it as is, and we can address the overall icon styling later on across the site. Otherwise, looks good!

**Comment by tovari** [comment]
Ana Maria added new items to the UAT issue list about Surge:
https://ifrcorg.sharepoint.com/:x:/s/GOIVfordeveloperteam/ERfcR2RDUMJOiGg4cRBrGtUB2LRyXW0IrBuUS8MsYwg5Nw?e=IkOgoa

**Comment by GregoryHorvath** [comment]
@batpad just adding here the before/after-deploy TODOs for PER (as of now), just in case:
- copy CSVs to the production VM
- remove the current `Form`, `FormData`, `Overview` data from production
- `./manage.py per_import_old_data -t answers`
- `./manage.py per_import_old_data -t atypes`
- `./manage.py per_import_old_data ../per_import_csvs/areas.csv -t areas`
- `./manage.py per_import_old_data ../per_import_csvs/components_a1.csv -t components -a 1`
- `./manage.py per_import_old_data ../per_import_csvs/components_a2.csv -t components -a 2`
- `./manage.py per_import_old_data ../per_import_csvs/components_a3.csv -t components -a 3`
- `./manage.py per_import_old_data ../per_import_csvs/components_a3-2.csv -t components -a 3`
- `./manage.py per_import_old_data ../per_import_csvs/components_a4.csv -t components -a 4`
- `./manage.py per_import_old_data ../per_import_csvs/components_a5.csv -t components -a 5`
- `./manage.py per_import_old_data ../per_import_csvs/questions_a1.csv -t questions -a 1`
- `./manage.py per_import_old_data ../per_import_csvs/questions_a2.csv -t questions -a 2`
- `./manage.py per_import_old_data ../per_import_csvs/questions_a3.csv -t questions -a 3`
- `./manage.py per_import_old_data ../per_import_csvs/questions_a3-2.csv -t questions -a 3`
- `./manage.py per_import_old_data ../per_import_csvs/questions_a4.csv -t questions -a 4`
- `./manage.py per_import_old_data ../per_import_csvs/questions_a5.csv -t questions -a 5`
- `./manage.py update_translation_fields`
- update frontend translation strings
- add epidemic descriptions manually because they are formatted

**Comment by batpad** [comment]
Known issue on Emergency Page: Search for Response Documents does not work. I am working on a fix. cc @tovari @mmusori

**Comment by batpad** [comment]
> Known issue on Emergency Page: Search for Response Documents does not work. I am working on a fix. cc @tovari @mmusori

This should now work.

**Comment by batpad** [comment]
Release Pull Request is here: https://github.com/IFRCGo/go-frontend/pull/1766
