### ISSUE TITLE
COVID Field Reports improvements

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#1797]
**Is your feature request related to a problem? Please describe.**
A revision of the COVID-19 Field Report was conducted, these are the changes proposed per section:

**1. Context**
- [x] Change: Start Date * --> Start Date of emergency/outbreak

**2. Situation**
**2.1 Numeric details (people)**
- [x] Change: Cases --> Cumulative Cases
- [x] Change: Number of registered cases --> Number of registered cases since the start of the outbreak
- [x] Add: Number of New Cases since last Field Report
- [x] Add: Number of registered cases since the last field report (Description)
- [x] Change: Number of people confirmed dead --> Number of people confirmed dead since the start of the outbreak
- [x] Add: Number of New Deaths since last Field Report
- [x] Add: Number of confirmed dead since the last field report (Description)
- [x] Add: Text box, with this text as description (inside the text box): Notes: Please provide any additional details since the last field report about new geographic locations that are being affected, details on if certain population groups are being affected, and general perspective on if the situation is improving or deteriorating. 
- [x] Add: a Note below: Note that it is not required to put case numbers into your Field Report, but you can input them if you choose to.  WHO or your national Government authoritative figures should be used.
- [x] Change: Description of Situational Overview (inside the text box) --> Describe succinctly (bullet points, short statements) the primary and secondary effects. Please outline how the situation is evolving and what has changed since the last field report. Below are some guiding questions to help complete this section. These questions are meant to function as a guide only:
•	General: 
    o	How has the situation evolved since the last field report? 
•	Impact on NS:
    o	Since the last field report, how is the situation affecting your National Society and activities?
    o	Since the last field report, has this situation resulted in changes to the way your NS operates?
•	Impact on people and communities:
    o	Since the last field report, how has the population been affected? 
    o	Are particular groups or geographic locations being impacted more than others and why?

**3. Actions**
- [x] Add: A tooltip when hovered over Assisted by RCRC Movement --> Number of people who have received RCRC services to prevent COVID-19 transmission or provide healthcare, social, or economic services to reduce the impact of COVID-19. Note one person may receive multiple services.
- [x] Change: Number of NS Personnel Involved --> Number of NS Staff Involved
- [x] Add: A tooltip when hovered over Number of NS Staff Involved --> Number of people currently involved in the response (mobilized for this specific response).
- [x] Change: Number of Volunteers Involved --> Number of NS Volunteers Involved
- [x] Add: A tooltip when hovered over Number of NS Volunteers Involved --> Number of people currently involved in the response (mobilized for this specific response).
**3.1 Actions Taken by National Society Red Cross (if any)**
- [x] Change: Description: Select the activities undertaken by the National Society and briefly describe. --> Since the beginning of the response, what activities has your NS undertaken? Select the activities undertaken by the National Society and briefly describe. A short description is available for each activity and if your NS has been active in this area during this response, please select it by checking the box. There is a section to provide a description of the activities supported. In this section please focus on what is new since the last field report. 
**NS INSTITUTIONAL STRENGTHENING**
- [ ] Add: A tooltip when hovered over National Society readiness --> Includes adapting community preparedness, response and DRR measures in view of the pandemic safety measures, especially when they are dealing with compounding disasters. Also includes adjusting contingency plans, updating Risk assessments identifying the different services that will be provided during the current disaster and how do these services fit into the National contingency plans.
- [ ] Add: A tooltip when hovered over National Society sustainability --> Includes identifying Core organizational budget to maintain the minimum structure of a National Society, available unrestricted reserves and unrestricted income and developing and executing business continuity plans. 
- [ ] Add: A tooltip when hovered over Support to volunteers --> Includes providing insurance for volunteers as well as access to PPE for volunteers to safely fulfil their duties.
- [x] Add: Text box --> Description (inside the text box): If selected any of the activities above, please provide brief details as to how individuals were reached by the activities listed above. We encourage you to consult the previous field report and to note any changes in actions (have new activities started or concluded?). Please highlight any key successes or challenges or unique learnings.
**- HEALTH**
- [ ] Add: A tooltip when hovered over Epidemic control measures --> Includes testing, contact tracing and support for quarantine of contacts and isolation of COVID-19 cases not requiring clinical treatment.
- [ ] Add: A tooltip when hovered over Risk communication, community engagement, and health and hygiene promotion --> Includes approaches such as community-based activities, mass media (local radios, TV, press), social media outreach or face-to-face and interpersonal communication (door to door, community dialogues, community meetings) to promote hygiene and other risk reduction interventions.
- [ ] Change: Community-based surveillance (CBS) --> Community-based surveillance (CBS) for COVID-19
- [ ] Add: A tooltip when hovered over Community-based surveillance (CBS) for COVID-19 --> Includes staff and volunteers who have completed a training and who are actively reporting health risks through the RC/RC approach to CBS. It does not include point-of-entry screenings, call centers, active surveillance or contact tracing.
- [ ] Add: A tooltip when hovered over Infection prevention and control (IPC) and WASH (health facilities) --> Includes any form of infection prevention and control (IPC) support provided to health facilities. Support may include donation of personal protective equipment or medical supplies, or other medical, logistics, or coordination support, support for triage of COVID-19 cases, installation of WASH infrastructure to facilitate IPC best practices, and IPC training.
- [ ] Add: A tooltip when hovered over Infection prevention and control (IPC) and WASH (community) --> Includes community WASH activities such as establishing or rehabilitating a drinking water source, toilet, and/or a handwashing facility.  
- [ ] Add: A tooltip when hovered over Mental health and psychosocial support services (MHPSS) --> Includes direct mental health and psychosocial support services to community members provided through National Society volunteers or staff.
- [ ] Add: A tooltip when hovered over Isolation and clinical case management for COVID-19 cases --> Includes support to health facilities that are actively treating COVID-19 cases or providing observational support and care to COVID-19 cases in isolation. Support can range from donations to staff and volunteer support.
- [ ] Add: A tooltip when hovered over Ambulance services for COVID-19 cases --> Includes suspected or confirmed COVID-19 patients who have received ambulance transport services by the National Society
- [ ] Add: A tooltip when hovered over Maintain access to essential health services (community health) --> Includes supporting essential community health services that have been impacted/reduced as a result of COVID-19, such as community-based malaria interventions, NCD support, and immunization campaigns to counteract the reduction in community health services and/or increased need for community health services resulting from COVID-19.
- [ ] Add: A tooltip when hovered over Maintain access to essential health services (clinical and paramedical) --> Includes supporting health facilities supported to maintain routine essential services such as MCH, NCD, malaria treatment, and other essential services. Support can be through either physical or technical support of volunteers or staff, or support through PPE or medical supplies donation.
- [ ] Add: A tooltip when hovered over Management of the dead --> Includes direct burial or cremation of human remains of COVID-19 cases, and supervision of safe burial or cremation in the community.
- [ ] Add: Support COVID-19 Vaccination
- [ ] Add: A tooltip when hovered over Support COVID-19 Vaccination --> Includes activities such as service delivery, campaigns, or distribution
- [x] Add: Text box --> Description (inside the text box): If selected any of the activities above, please provide brief details as to how individuals were reached by the activities listed above. We encourage you to consult the previous field report and to note any changes in actions (have new activities started or concluded?). Please highlight any key successes or challenges or unique learnings.
**SOCIOECONOMIC INTERVENTIONS**
- [ ] Add: A tooltip when hovered over Community engagement and accountability (CEA), including community feedback mechanisms--> Includes systems and approaches to collect community feedback which could mean recorded /tracked suggestions, comments, complaints, concerns, perceptions, praise, question collected through feedback systems and/or through community perception surveys.
- [ ] Add: A tooltip when hovered over Livelihoods, cash support & food aid --> Includes immediate food assistance or measures to protect households’ livelihoods by provisioning for lost sources of income to meet their basic needs and avoid further assets depletion. This can include all types of cash assistance to address basic needs. Also, activities for skills development such as entrepreneurship, marketing and coaching. 
- [ ] Add: A tooltip when hovered over Social care and cohesion, and support to vulnerable groups --> Includes analysis of the specific needs of marginalized groups in the needs assessment, and/or following the PGI minimum standards and/or using equivalent guide on assessing and meeting the needs of marginalized groups.
- [ ] Add: A tooltip when hovered over Shelter and urban settlements --> Includes for example, household items to improve shelter conditions (clothing, bed linen, mattress, blanket, etc.), emergency shelter (tents or tool kits), accommodation in collective facilities (camps, collective centers or quarantine facilities), cash and voucher assistance to cover payment of accommodation (rent or loans), utilities and other related cost directly related with the accommodation.
- [x] Add: Text box --> Description (inside the text box): If selected any of the activities above, please provide brief details as to how individuals were reached by the activities listed above. We encourage you to consult the previous field report and to note any changes in actions (have new activities started or concluded?). Please highlight any key successes or challenges or unique learnings.
**3.2 Actions taken by the IFRC**
- [x] Add: Description (inside the text box): In this section you can provide details as to how you have been working with the IFRC in this operation. To help in completing this section some prompting questions are below which are meant to function as a guide only:
•	What role has the IFRC been playing in this operation?
•	What actions has the IFRC taken to support this operation?
•	What are the recent changes in the actions taken by the IFRC since the last field report?
•	Are there any areas where you hope IFRC can support with?
**3.3 Actions taken by other RCRC Movement**
- [x] Add: Description (inside the text box): We understand multiple partners may be present so please highlight the main partners you have worked with since the last field report. Below are some guiding questions to help complete this section. These questions are meant to function as a guide only:
•	Since the last Field Report who has your NS been working with and in what areas of support? 
•	Are there any interesting details about these RCRC partners that are not covered in the 3W?
•	Are there any new partnerships that your NS may be working with looking forward?
**3.4 Information Bulletin**
- [x] Add: Dropdown menu --> Information Bulletin? Description: Indicate if an Information Bulletin was published, is planned or if no Information Bulletin will be issued for this operation/disaster/hazard. Options: No / Planned / Yes / Published - **Not needed**
**3.5 Actions Taken by others (Governments, UN)**
- [x] Change: Who else was involved? UN agencies? NGOs? Government? Describe what other actors did. Also mention who the other actors are. -->Who else is your National Society working with? UN agencies? NGOs? Government? Since the last field report, outline the main actors your NS has been engaged with. We understand there may be many partners so please just highlight the main ones since the last field report.
- [x] Add: Dropdown menu --> External Partner Category. Options: UN, Government, NGO (Multiple Selection)
- [x] Add: Dropdown menu --> Details of Partner. Options: -	MOH, WHO, UNICEF, WFP, Other UN agencies, Civil Society and NGO partners (Multiple Selection) - **Not needed**
- [x] Add: Dropdown menu --> Supported/partnered activities. Options: 
> _Health activities:_
> COVID-19 testing
> Point of entry/ point of control screening
> Contact tracing
> Support for people in quarantine
> Support for mild/ moderate cases in isolation
> Risk communication and community engagement
> Health and hygiene promotion
> Surveillance, including active case finding
> Community-based surveillance
> Infection prevention and control (including WASH) in health facilities
> Community WASH activities to reduce the risk of COVID-19 transmission
> MHPSS support related to COVID-19
> Isolation and clinical case management of COVID-19 cases
> Support for COVID-19 vaccination
> Ambulance services for COVID-19 cases
> Maintaining non-COVID-19 ambulatory services
> Blood services
> Maintaining access to essential health services (e.g. routine immunization, malaria, elder care)
> Management of the dead
> _Livelihoods activities_
> Food and in-kind assistance
> Cash and voucher assistance
> Skills development for livelihoods / economic activities
> _Shelter_
> Provision of safe and adequate shelter and settlements
>Other
 (Multiple Selection)

**4. Response**
- [x] Add: A tooltip when hovered over Public --> Available to all stakeholders on the GO platform  
- [x] Add: A tooltip when hovered over RCRC Movement --> Available to those who have an IFRC GO login across the RCRC Movement
- [x] Add: A tooltip when hovered over IFRC Secretariat --> Available to only those with an active IFRC account. 

@tovari

**Comment by tovari** [comment]
Hi @mariam-yu,
I would like to ask your opinion, what would be the best way to implement the following type of descriptions:
"3.2 Actions taken by the IFRC
 Add: Description (inside the text box): In this section you can provide details as to how you have been working with the IFRC in this operation. To help in completing this section some prompting questions are below which are meant to function as a guide only:
• What role has the IFRC been playing in this operation?
• What actions has the IFRC taken to support this operation?
• What are the recent changes in the actions taken by the IFRC since the last field report?
• Are there any areas where you hope IFRC can support with?"

The description is long, it would not fit into the text box without scrolling, and it would disappear when starting to type. Would you suggest another solution? Maybe under the 'Actions taken by the IFRC' text, or as a tooltip? Or something else?
There are a few other similar updates as well in this request, so it would be good to have a generic solution.

Thanks!

![image](https://user-images.githubusercontent.com/68283148/105200480-2a42fd80-5b40-11eb-92bc-ddb7ce3b6ff6.png)

**Comment by mariam-yu** [comment]
@tovari So, here has been the logic so far (or what we should have aimed for):
- Description under the title = brief description of what the user should do
- Description within the box = should be usually an example of the text to be included

I know that with the latter it wasn't always an example, but I think we should go in that direction, otherwise it is duplicate info.

So, what we could do is:
a) Instead of the text you mentioned write an example matching that guideline and have it within the description box.
b) Have a brief guideline under the title with a tooltip which will show the full text. The only thing is we don't have tooltips currently in the forms, but we do have them across the platform. 

We could propose another option, such as "...description... _read more_" which would be the popup or expand option, but I'd be a bit hesitant to introduce this currently, as it would be a new thing, and I'm not sure how it would cascade down across the platform. The easiest would be a tooltip, though in this case we need to ensure the description itself is quite brief, followed up with a tooltip.

Hope this helps!

**Comment by GregoryHorvath** [comment]
@anamariaescobar I'll start to tick-off the things I'm done with locally so I/we can keep track better, if this is okay. I'll drop a comment whenever anything is pushed to staging.

**Comment by anamariaescobar** [comment]
That is perfect @GregoryHorvath thank youu!

**Comment by GregoryHorvath** [comment]
@anamariaescobar @mariam-yu Wondering if we should follow the same pattern for the tooltips as at other places, like this (don't mind the (i) icons are a bit off, their CSS will be fixed):
![image](https://user-images.githubusercontent.com/30079559/105975477-4b02da00-608f-11eb-8537-948760cecc52.png)

or if we really want hover-triggered tooltips here?

**Comment by anamariaescobar** [comment]
@GregoryHorvath from my side the easier and faster to implement, but I wonder what @mariam-yu thinks since we are adding the tooltips in a lot of places through the Field Report, for example the actions....

**Comment by mariam-yu** [comment]
@GregoryHorvath @anamariaescobar I think implementing tooltips works, but we probably should keep on click rather than hover to avoid having them too interactive when not needed. Also, do we need them in all the places? I agree that we should reduce the number. One way could be, for example in the image you sent, to combine the 3 into one and put next to the title, if the explanation is required for all. Hope this helps!

**Comment by GregoryHorvath** [comment]
@mariam-yu Oh damn that's actually the best idea. Thanks for the input, I'll keep them as clickables for the time being then and we'll see how it goes. I'll try to figure something out for the Actions parts when I get there.

**Comment by GregoryHorvath** [comment]
@anamariaescobar I deployed the ticked out stuff to staging.

### A couple of notes to take:
- Actions' tooltips can be set on the backend by filling their 'Tooltip text' field, and these are hoverable.
  - I didn't tick these out, because those tooltips are not autofilled. If we'll have all the tooltip texts for those actions we can think of having an import script for when we deploy these to production, but for now I didn't prefill them with any text.
- Wasn't sure about all the design elements, so please comment if anything is off or should look different.
- Wasn't sure what new things to add into the Field Reports' page (the details page, which is shown after one is created), so for now I didn't add anything. Please comment which should show up there too and where.
- The description fields are still missing from the different sub-categories at the "3.1 Actions Taken by National Society Red Cross (if any)" part. I'm still stuck with the implementation of these because the current data structure doesn't really have a straightforward solution to add these, waiting for some help from the guys.

cc @mariam-yu @batpad

**Comment by anamariaescobar** [comment]
Hey @GregoryHorvath!

Thanks for this, I have checked on staging and it looks great! (specially the tooltips on the actions, fantastic work!)

I have a couple of points to address:

2. Situation
2.1 Numeric details (people)

 

- [ ] Change: Cases --> Cumulative Cases
- [ ] Change: Number of registered cases --> Number of registered cases since the start of the outbreak (this is the description that goes underneath Cases)
- [ ] - [ ] Change: Dead --> Cumulative Dead
- [ ]  Change: Number of people confirmed dead --> Number of people confirmed dead since the start of the outbreak (this is the description that goes underneath Cases)
- [ ] Change: Description of Situational Overview
> Can we keep this inside the text box --> Describe succinctly (bullet points, short statements) the primary and secondary effects. Please outline how the situation is evolving and what has changed since the last field report. In the left are some guiding questions to help complete this section.
> And move this outside the text box under "Description of situational Overview" -->These questions are meant to function as a guide only:
> • General:
> > o How has the situation evolved since the last field report?
> • Impact on NS:
> > o Since the last field report, how is the situation affecting your National Society and activities?
> > o Since the last field report, has this situation resulted in changes to the way your NS operates?
> • Impact on people and communities:
> > o Since the last field report, how has the population been affected?
>>  o Are particular groups or geographic locations being impacted more than others and why?

3. Actions

- [ ] For the tooltips in Number of NS Personnel Involved, Assisted by RCRC Movement and Number of volunteers involved, can we loose the tittles? (ex. for Assisted by RCRC Movement, just have _Number of people who have received RCRC services to prevent COVID-19 transmission or provide healthcare, social, or economic services to reduce the impact of COVID-19. Note one person may receive multiple services._)
- [ ] Change the tooltip on Number of NS Personnel Involved -->Number of personnel from the NS currently involved in the response (mobilized for this specific response).
- [ ] For the description fields that are still missing from the different sub-categories at the "3.1 Actions Taken by National Society Red Cross (if any)" part, once you figured out how to do them (I am sure you will), will it be possible to make them appear only if one or more of the actions of that category is ticked? (this is a wish list one, if that means a lot of work, there is no need to address it)
- [ ] Actions taken by the IFRC --> Can we move the text inside the box to be description under Actions taken by IFRC? Just thinking that this is supposed to be a guidance and it doesn't do much if it disappears when they start typing.
- [ ] Actions taken by other RCRC Movement --> Same as the one above.
- [ ] Information Bulletin --> I just found out that the Information Bulletin are going to disappear, so it doesn't makes sense to add it now to the Field Reports, can we get rid of this one completely?
- [ ] External partner's categories --> Reviewing the logic of filling a COVID Field Report, this drop down doesn't add anything that the external partner drop down isn't giving us, so, can we get rid of this one?
- [ ] External partners --> The drop down is not populated yet, also, can we add to the dropdown options provided before "Other governmental agencies" ?
- [ ] Supported/partnered activities --> Still not populated.
- [ ] Since now we got down to 2 drop downs, can we make them appear in the same line? (again, wish list, so no need if that means extra work)

Please let me know if all of this is possible and sorry for some double work....

cc. @mariam-yu @batpad

**Comment by GregoryHorvath** [comment]
@anamariaescobar Again the checked out changes are out on staging.

I updated the descriptions/labels through https://dsgoproxyapp.azurewebsites.net/translation-dashboard which I forgot before

> Change the tooltip on Number of NS Personnel Involved -->Number of personnel from the NS currently involved in the response (mobilized for this specific response).

This I also updated through the translation dashboard with the value in the original comment. So I didn't change it to this, but kept the above one in the first comment.

> For the description fields that are still missing from the different sub-categories at the "3.1 Actions Taken by National Society Red Cross (if any)" part, once you figured out how to do them (I am sure you will), will it be possible to make them appear only if one or more of the actions of that category is ticked? (this is a wish list one, if that means a lot of work, there is no need to address it)

Can't really tell sorry, this depends on how we resolve adding the new fields in the first place.

> External partners --> The drop down is not populated yet, also, can we add to the dropdown options provided before "Other governmental agencies" ?
> Supported/partnered activities --> Still not populated.

Sorry forgot to mention these are fillable from the Django Admin, but the values are added by now so you should see those in the dropdowns.

> Since now we got down to 2 drop downs, can we make them appear in the same line? (again, wish list, so no need if that means extra work)

With the current design we seem to only have 1 label per line, so I'd say if we could have a combined label somehow here then this is doable. (you can see how this works for the Country and Region dropdowns in the form)

**Comment by GregoryHorvath** [comment]
@mariam-yu If you select Covid related event on the first step then you should see the changes on the staging site: https://dsgoproxyapp.azurewebsites.net/reports/new

Some of the relevant changes:
![image](https://user-images.githubusercontent.com/30079559/107378249-114cbd00-6aec-11eb-8028-2ae3aca67c78.png)

Hovering action tooltips and our standard way of clickable tooltips
![image](https://user-images.githubusercontent.com/30079559/107378451-4a852d00-6aec-11eb-96f2-494f47182f8a.png)

@anamariaescobar had a suggestion if we could have these in 1 line somehow?
![image](https://user-images.githubusercontent.com/30079559/107378628-73a5bd80-6aec-11eb-8578-eaeea13d94e6.png)

Grouped together tooltips for visibility
![image](https://user-images.githubusercontent.com/30079559/107378726-8e783200-6aec-11eb-803a-7afd26ec2f46.png)

**Comment by batpad** [comment]
@karitotp there are some things still remaining from this ticket, but for all the things checked off by @GregoryHorvath and for the functionality in the screenshots above, would you be able to start testing the field report on staging?

We should check that the above functionality all works as expected when the Field Report is a COVID field report, and also that nothing is broken for field reports that are not COVID reports. Please add any questions to the ticket or you can ask @GregoryHorvath or me in Teams. Thanks much!

**Comment by anamariaescobar** [comment]
@GregoryHorvath 

Sorry, I know we have change this text 3 times already, but just trying to make it as brief as possible! I promise this is the last time

- [ ] Change: Text outside the text box under "Description of situational Overview" -->These questions are meant to function as a guide only:
Since the last Field Report:
o How has the situation evolved?
o How is the situation affecting your National Society and activities?
o Has this situation resulted in changes to the way your NS operates?
o How has the population been affected?
o Are particular groups or geographic locations being impacted more than others and why?

- [ ] Change: Text under Actions taken by National Society Red Cross (if any) --> 
Since the beginning of the response, what activities has your NS undertaken? 
A short description is available for each activity and if your NS has been active in this area during this response, please select it by checking the box. 
There is a section to provide a description of the activities supported, in this section please focus on what is new since the last field report. 

Please let me know if I can help with translations, for the actions I will add them on staging for the first3 (first line under health) so @karitotp can test them and I can add them on the backend manually once we deploy to production,

cc @batpad @karitotp @mariam-yu

**Comment by mariam-yu** [comment]
> @mariam-yu If you select Covid related event on the first step then you should see the changes on the staging site: https://dsgoproxyapp.azurewebsites.net/reports/new
> 
> Some of the relevant changes:
> ![image](https://user-images.githubusercontent.com/30079559/107378249-114cbd00-6aec-11eb-8028-2ae3aca67c78.png)
> 
> Hovering action tooltips and our standard way of clickable tooltips
> ![image](https://user-images.githubusercontent.com/30079559/107378451-4a852d00-6aec-11eb-96f2-494f47182f8a.png)
> 
> @anamariaescobar had a suggestion if we could have these in 1 line somehow?
> ![image](https://user-images.githubusercontent.com/30079559/107378628-73a5bd80-6aec-11eb-8578-eaeea13d94e6.png)
> 
> Grouped together tooltips for visibility
> ![image](https://user-images.githubusercontent.com/30079559/107378726-8e783200-6aec-11eb-803a-7afd26ec2f46.png)


@GregoryHorvath Thank you for putting this together so detailed for me. It helped a lot to digest the changes. Here are a few comments. Hope it's clear, and I'm not missing anything.

**Situation: Numeric details - subtext**
I am not sure if we have a style for this, but I think the text width should be shortened and a bit of padding on top. 

**Situation: Number of new cases... **
Not sure what the changes are here, but looks fine. Overall, in our designs we propose some fields to be next to each other and shorter fields to be shorter, as having such a large field for just one number may be strange. Also, just a tiny note, if we capitalize all the words in the titles, we should do it across :)

**Situation: Situational Overview - subtext**
Also, on some other sections. This is super text heavy and will be very difficult to digest. probably better to split the text contextually. Have the minimum needed right up front and the rest (like examples) in a tooltip.

**Actions: Actions Taken by NS - checkmark hovers**
I find these hovers very confusing. Didn't know why they popped up, where, related to what etc. Why can't we use the same tooltips next to each item?

**Actions: External Partners / Supported partners**
We could have them side by side, like this:
<img width="1274" alt="Screen Shot 2021-02-09 at 11 47 55 PM" src="https://user-images.githubusercontent.com/60006476/107443745-4e876e00-6b31-11eb-815e-2386a91b3542.png">

**Response: Visible to - grouped tooltips**
This works. We'd probably need to "clean up" the style of the tooltip. The font doesn't need to be so bold and we could add some styling, but I guess for now works.

**General: tooltips**
This is probably a bigger site-wide conversation, but in general it may be a good idea to add a little x to close the tooltips (since it's on click) and to not have them overlap, if one is open the other closes.

**Comment by karitotp** [comment]
@batpad @GregoryHorvath, all the thing are working correctly for COVID field reports and for NOT COVID reports.
Some minor details  are:

> Hovering action tooltips and our standard way of clickable tooltips

For some reason in **Assisted by RCRC Movement** hovering text box does not disappear when I clicked on the other tooltips
![Screenshot from 2021-02-09 17-14-33](https://user-images.githubusercontent.com/11504548/107436068-09e0e000-6afb-11eb-9256-decbd217730e.png)

> - [ x] Add: Dropdown menu --> Details of Partner. Options: - MOH, WHO, UNICEF, WFP, Other UN agencies, Civil Society and NGO partners (Multiple Selection)

I did not find this

Also, In SITUATION section seems that the validation message is still displaying the previous titles of numeric details.

![Screenshot from 2021-02-09 21-35-23](https://user-images.githubusercontent.com/11504548/107456742-bd0f0080-6b1e-11eb-934e-dd0ffbb4e406.png)

**Comment by GregoryHorvath** [comment]
@anamariaescobar
Deployed the changes to staging, now the 3 "Notes" (since we already have "Description" fields for each Actions sections per organization, I called these "Notes") should show up. Also changed those descriptions you lastly mentioned.
For the tooltip translations we could use a CSV I guess, currenty I simply added the english versions in a script as hardcoded values.
```
[
      [
        'National Society readiness',
        'Includes adapting community preparedness, response and DRR measures in view of the pandemic safety measures, especially when they are dealing with compounding disasters. Also includes adjusting contingency plans, updating Risk assessments identifying the different services that will be provided during the current disaster and how do these services fit into the National contingency plans.'
      ],
      [
        'National Society sustainability',
        'Includes identifying Core organizational budget to maintain the minimum structure of a National Society, available unrestricted reserves and unrestricted income and developing and executing business continuity plans.'
      ],
      ...
]
```
Where the 1 lines between each `[ ]` is the Action name that we're mapping them to, and after the `,` comma we have the tooltip text.


@mariam-yu
- For the Fold's sub-text I used our pre-existing styling, but now added some padding-top to it
- Made "new cases" and "new deaths" into lowercase
- If I remember right I chose to use hoverable tooltips for the Actions because it would've been hard(er) to implement the clickable version, but I'll have to double check. But for sure having those (i) icons made them look pretty wild also.
- Some of the tooltips had bold description texts by accident, I fixed that now
- Thanks for the suggestion for the dropdowns, grouped them into 1 line now


@karitotp 
Big thanks for the testing.
- Yep the tooltips remain open unless you click away, I'd say let us handle this in a separate ticket, @mariam-yu also suggested to do something about these
- The "Details of Partner" dropdown was removed, since @anamariaescobar felt it was redundant, not sure if this request was captured here or was just in a Teams chat, sorry for that
- That validation message seems pretty off from reality, I'll look into that, thanks!

**Comment by tovari** [comment]
@GregoryHorvath, would you mind to remove the 'Description' text at 'Source (of figures) on the 2nd page? It is not required.
Thanks!

**Comment by karitotp** [comment]
I checked again  the functionalities for COVID FR and NOT COVID reports and all works good! Also checked the follow things:

- [x] For the Fold's sub-text I used our pre-existing styling, but now added some padding-top to it
- [x] Made "new cases" and "new deaths" into lowercase
- [ ] If I remember right I chose to use hoverable tooltips for the Actions because it would've been hard(er) to implement the clickable version, but I'll have to double check. But for sure having those (i) icons made them look pretty wild also.
- [x] Some of the tooltips had bold description texts by accident, I fixed that now
- [x] Thanks for the suggestion for the dropdowns, grouped them into 1 line now
- [ ] Yep the tooltips remain open unless you click away, I'd say let us handle this in a separate ticket, @mariam-yu also suggested to do something about these
- [x] The "Details of Partner" dropdown was removed, since @anamariaescobar felt it was redundant, not sure if this request was captured here or was just in a Teams chat, sorry for that
- [x] That validation message seems pretty off from reality, I'll look into that, thanks!
- [x] Would you mind to remove the 'Description' text at 'Source (of figures) on the 2nd page? It is not required.

**Comment by tovari** [comment]
Hi @GregoryHorvath, the new fields should be displayed on the page of the created FR as well. Currently, the page shows only the old fields only. Could you please add the new ones as well?
