### ISSUE TITLE
[PROD] Map legend displaying wrong taxonomy

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#1811]
## Issue

Map legend on GO maps refers to "people targeted" while the info box refers when clicking on the data points refers to "people affected".

This should be aligned with IFRC taxonomy

**Comment by jhenshall** [comment]
The language used in the appeal documents is 'People to be assisted'. The pop-up box is therefore wrong and definitely needs changing. Whilst the legend using '# of people targeted' is probably ok, I suggest we change this too, so that same language is used everywhere. Thanks @guipizzini for flagging.

cc @geohacker @batpad

**Comment by geohacker** [comment]
@jhenshall this might not be as easy as just replacing the map. There are several places 'People targeted' is used https://github.com/IFRCGo/go-frontend/search?q=people+targeted I defer to you, @tovari and @batpad. This will also have implications on translations so may not be quick.

**Comment by jhenshall** [comment]
Ah ok, good point @geohacker! In that case, I would just change the pop-up to also say 'People targeted' rather than 'People affected'. That's assuming that the popup is referencing the same attribute in the dataset that is used to scale the points.

![image](https://user-images.githubusercontent.com/6359748/108994074-408a2f00-7693-11eb-9f8d-fde55de9bbeb.png)

**Comment by jhenshall** [comment]
Done with March 2021 geo release!
