### ISSUE TITLE
[PROD] 3w bulk upload feature is incorrectly importing date fields

### ISSUE THREAD

**Issue by luisfanovich** [IFRCGo/go-frontend#1884]
## Issue
GO 3w bulk upload feature is incorrectly importing date fields. Start date and End date imports as day/month is mixed up. 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/35769672/115166292-0ed08b80-a078-11eb-90a3-dcd1449ec024.png)

**Comment by thenav56** [comment]
Hi @luisfanovich @tovari 
The current date parser in the 3W bulk upload can handle multiple date formats. Currently, the parse handles the input as
- '11/04/20' -> Y: 2020, M: 11, D: :4
- '22/04/20' -> Y: 2020, M: 04, D: 22 (Here 22 is not valid for a month so it will now use 22 as a day instead of the month)

I can change it to **day first** `DD/MM/YY` by default, but this will still take `MM/DD/YY` if month > 12.

If we don't need to support multiple date format then we can use a standard format `DD/MM/YY` only as well. 

let me know which makes more sense to fix this issue.

**Comment by tovari** [comment]
Thanks for explaining @thenav56.
I prefer to move to a fixed format to avoid ambiguity. I also will implement data validation in the template. I suggest to use the
DD/MM/YYYY
format to have a easy understanding.

**Comment by thenav56** [comment]
Thanks @tovari, I have created a PR with the fix.
https://github.com/IFRCGo/go-api/pull/1071

**Comment by thenav56** [comment]
The changes are [deployed](https://github.com/IFRCGo/go-api/pull/1071#issuecomment-841153922) to staging.
