### ISSUE TITLE
[PROD and SATGING] REgistration error - Country is missing

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1899]
## Issue
*New registration form cannot be submitted as it gives an error that the country field should be filled.
Both Staging and Production are affected.*

## Steps to reproduce
https://go.ifrc.org/register
https://dsgoproxyapp.azurewebsites.net/register

*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/68283148/117146082-2156fe80-adb4-11eb-9ffc-d6f4c0c4f57e.png)

## Severity
*high*

## Is there a workaround?
*only admins can create new accounts*

**Comment by szabozoltan69** [comment]
It's propably a frontend issue, because this 
![kép](https://user-images.githubusercontent.com/6050643/117151033-fa4efb80-adb8-11eb-892d-0a4c5a693381.png)
validation error arrives without backend communication. The only backend request is teh list of "white domains", but is is before the error arrives.
![kép](https://user-images.githubusercontent.com/6050643/117151166-19e62400-adb9-11eb-9432-b8ee8a988ac4.png)

**Comment by batpad** [comment]
@frozenhelium would you be able to look? It maaaaybe Select related?

**Comment by szabozoltan69** [comment]
It seems to be that a "No login token found" feedback causes the error.
Do we await a registering user to be logged in? :-)
![kép](https://user-images.githubusercontent.com/6050643/117155537-23718b00-adbd-11eb-8eff-09adc5913768.png)

**Comment by vdeak** [comment]
Did some investigation, the root cause is the following:

The register.js was changed

![image](https://user-images.githubusercontent.com/81553689/117253197-3c268300-ae47-11eb-8717-2d0f11682073.png)


Debugged the front-end code, found the following:

![image](https://user-images.githubusercontent.com/81553689/117253100-1f8a4b00-ae47-11eb-8ee5-9efe58a15779.png)

The payload.country set to undefined here:
payload.country = get(state, 'country.value') || undefined;

Since we do not have country.value, only country in the state, the country.value will be undefined.
It should be fixed.

**Comment by batpad** [comment]
thanks @vdeak .

@frozenhelium - yea, this does seem related to the changes for the react-select upgrade? Would you be able to look at this? Is there anything I can do to help ?

**Comment by frozenhelium** [comment]
Should be fixed by https://github.com/IFRCGo/go-frontend/pull/1901

**Comment by tovari** [comment]
Thanks, it works fine!
