### ISSUE TITLE
Multi-country ops in Open Surge Alerts (Molnix)

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#1988]
## Issue
When we have a multi-country operation, people can be deployed to different countries, as the Emergency in GO will be linked to only one country we need to find a way to show to which country is the alert for.

## Steps to reproduce

![image](https://user-images.githubusercontent.com/69478743/128373551-aa67fa06-2a53-49f5-87bf-ee300eca27d3.png)
 
In the picture we can see 3 Alerts for Public Health Offices and 2 for CEA officer, this are for different countries but as the country linked to the Emergency is Switzerland, all the alerts look like they are for Switzerland.

## Expected behavior
We could pull the country the alert is for from the Molnix system, I am contacting them to see if they have ISO codes or if we need to match the country names, Will update this asap.

## Related feature
#1965

## Impact
The alerts might seem like they are repeated, also the users wont know for which country is really the alert.

@batpad @tovari

**Comment by batpad** [comment]
+cc @willemarcel 

Currently, SurgeAlerts have a Foreign Key to Event (Emergency), and the connection to Country is made through the Event / Emergency. I.e. Surge Alert -> Event -> Country

So, currently, we associate Surge Alert to Event by using the `OP-` tag coming from Molnix to associate with an Event. Since the Event had a country association already, we are currently not processing the Countries that come from Molnix. As it turns out, often, the Country of the Alert is often not the same country the Event is associated with. This is likely due to it being a multi-country emergency.

The proposal here would be to add a Many To Many relation to Country on the SurgeAlerts table, allowing a Surge Alert to be associated with multiple countries, so we decouple the countries of the Surge Alert from the country of the Event the Surge Alert is for. So, what we would need to do:

 - Add a M2M relation from SurgeAlert -> Country
 - While parsing Molnix data, read the `countries` field for alerts, and import the country associations as the `countries` for the Surge Alert. Here, we need to check if Molnix returns ISO codes for countries, or if it's only strings with country names, deal with name matching of countries.
 - Add `countries` to the Surge Alerts APIs
 - Display `countries` from the `countries` field on the Surge Alert on the frontend, rather than the country of the Event that the Surge Alert is associated with.
