### ISSUE TITLE
[PROD] Snippet files not showing up

### ISSUE THREAD

**Issue by k-som** [IFRCGo/go-frontend#1993]
_Same for staging and production:_

I've added a couple of PNG files under snippets for [this](https://go.ifrc.org/emergencies/5473#general-information) operation but they don't seem to be reflected on the emergency page (only text is visible), though in the backend I can still see them being added.

**Comment by tovari** [comment]
The workaround is to use the rich text editors insert image functionality.

**Comment by szabozoltan69** [comment]
I suppose this is solved – recently there are nice PNG pictures on https://go.ifrc.org/emergencies/5473

**Comment by tovari** [comment]
Well, the problem here is that the option for adding Images on the admin page at the emergency snippets doesn't work:
![image](https://user-images.githubusercontent.com/68283148/132829037-66803f89-afcb-41f7-a1c0-90b6140c4eb6.png)

Inserting images directly to the text is a workaround, but we have this image attachment option on the admin page which doesn't work. It makes confusion.

**Comment by szabozoltan69** [comment]
Now it is possible to upload images, please check https://dsgocdnapi.azureedge.net/en/api/event/4470
![kép](https://user-images.githubusercontent.com/6050643/166257440-26a81db5-37e3-4714-a1d3-a9fa5d97f0ff.png)
Please check the uploaded file:
https://dsgofilestorage.blob.core.windows.net/api/emergencies/4470/tulipanfa.jpg
On the "Additional information" page it can also be seen:
https://dsgoproxyapp.azurewebsites.net/emergencies/4470#additional-information
