### ISSUE TITLE
Increase upload size limit for reports

### ISSUE THREAD

**Issue by k-som** [IFRCGo/go-frontend#206]
Under "Bangladesh - Population Movement" (Home>API>Emergencies>) I've managed to upload only 10 situation reports, trying to add more causes error 413. I have 80 more to upload...

cc: @guipizzini

**Comment by k-som** [comment]
Update: doesn't matter how many files I try to upload, there are some certain files that cause this error (no idea why, uploading only pdf and doc files...).

**Comment by dereklieu** [comment]
@k-som 413 means the upload size is too large. I can increase the size limit. What's the maximum size in megabytes of a file that someone would upload?

**Comment by k-som** [comment]
@dereklieu thanks, that explains everything - one of these files is 9MB and the other almost 12 MB. Most often the size is max 2MB (word/pdf report), and only sometimes we upload some simply visualizations and maps.

**Comment by dereklieu** [comment]
@k-som I've updated the API to accept files up to 50mb in size, can you test and confirm that the files you couldn't upload before now can?

**Comment by k-som** [comment]
@dereklieu still the same, error 413

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 There has not been complaints about the upload size issues lately. What is the current upper limit for an upload? If it is 50 MB (as suggested by Derek above), I think we can close the issue.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Well, this is an unsolved issue yet. I tried to set the 50 MB, but my config change is not enough. It is (~)impossible to test it on local development environment, even with the Azurite module. Derek suggested to set up a (non staging, but really testing) environment with real Azure storage, but this request was postponed for the next (budget) year, because it needs about 8 hours to set up everything. So, please keep this issue open. This testing environment would be really good for other purposes also.

**Comment by szabozoltan69** [comment]
Done. Check https://dsgocdnapi.azureedge.net/admin/api/situationreport/100 as a proof.
