### ISSUE TITLE
Surge URL doesn't have "staging site" orange banner

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#2121]
Hi, I'm testing in https://ifrc-go-feature-dref.surge.sh/ and it doesn't have the orange banner to indicate that it's not production.

Whereas https://dsgoproxyapp.azurewebsites.net/ does have the orange banner.

Looking at original ticket #888 the orange banner was meant to apply to all non-production sites - can you please take a look?

![image](https://user-images.githubusercontent.com/33625192/142561833-9777135d-82f4-45a0-bc9a-d39fe0abb81e.png)

See below from #888:

> Checked on one separate testing URL and the banner shows up saying "Staging site". Based on @GregoryHorvath's above comment, this will be the case for all surge URLs from now on, so in that case this ticket is now tested and it works.

_Originally posted by @teklal in https://github.com/IFRCGo/go-frontend/issues/888#issuecomment-611132592_

**Comment by szabozoltan69** [comment]
I think this issue should be assigned to the dref-developers, who deploys ifrc-go-feature-dref.surge.sh.
On the other hand, anyone, who clicks this not-very-well-known link, surely knows that it is just a demo page of a still-deployed feature.

Anyway, the quick-and-dirty temporary solution would to remove the 'development' condition from here, because (by my opinion) this site is a development site:
https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/EnvironmentBanner/index.js#L11
Or changing the definition of environment here: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/config.js#L1
