### ISSUE TITLE
Informal Update

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#2133]
New Report type moduled on the Field Report. It is a quick alert – to inform internal stakeholders and partners that we are monitoring an evolving situation. It enables recipients to quickly grasp the potential magnitude of the event, as well as possible RCRC engagement. Informal updates are issued for disaster and crisis events that are considered to have public interest, strategic interest or operational interest. By sharing with PNS and other partners demonstrates the value-add of the Emergency Operations team as a source of critical information, and ‘unlocks’ knowledge that was previously generated and held within IFRC.
The design  and documentation are available in the prototype. 
The form: https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=3557%3A96977

The report: https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=636%3A15756

**Comment by tovari** [comment]
Comments from DFS:
https://docs.google.com/document/d/1LHctkW3Q6NHoyXl_oTrPIuvuTxA7PNo2ZPQjZGp0h6M/edit

**Comment by suraj-ram-shrestha** [comment]
**INFORMAL UPDATE REQUEST**

**UI SIDE CHECKLIST**
- [ ] Add "Informal Update Request" item in "Create a Report" dropdown
- [ ] Create a landing page for "Informal Update Request" when clicked on a dropdown item
- [ ] On a landing page, display title, description, sliding bar, and buttons as in wireframe
- [ ] When clicked on the tab of the slider bar, the related page should be open
- [ ] When clicked to Continue if no error on the page should go to next page
- [ ] When clicked to Back should go to the previous page
- [ ] When clicked to Save and Close, all changes should be saved and redirect to 
- [ ] On a landing page, Create a component for the "Context" page 
- [ ] Add section fields as shown in wireframe for "Context" page
- [ ] On the title field, The title must be automatically pre-populated with the country name and the hazard type
- [ ] Add Map section field to upload/drag & drop Map related image
- [ ] Add Graphic section field to upload/drag & drop the related image
- [ ] Add section fields as shown in wireframe for "Actions" page
- [ ] Add section fields as shown in wireframe for "Focal points" page

**Comment by tovari** [comment]
I have got the following error after submission:
{"url":"api/v2/informal-update/","status":500,"requestOptions":{"method":"POST","body":{"country_district":[{"country":82,"district":1190},{"country":82,"district":1190},{"country":82,"district":1188}],"hazard_type":14,"title":"Hungary - Hungary - Hungary - Cold Wave  2 / 2022","situational_overview":"Firefox laksjds \n\nASD ads\nASDA DDFDSF dg\n fg\ndfgdfgdfgdfg \n","actions_taken":[],"originator_name":"TD","originator_title":null,"originator_email":"tovari@gmail.com","originator_phone":null,"ifrc_email":null,"ifrc_name":null,"ifrc_title":null,"ifrc_phone":null,"share_with":"rcrc_network","references":[{"date":"2022-02-15","source_description":"ref 1","url":"ref1.com","document":64},{"date":"2022-02-23","source_description":"ref 2","url":"ref2.com","document":63}],"map_files":[{"id":61,"caption":"map1 "},{"id":62,"caption":"map 2"}],"graphics_files":[{"id":60,"caption":"caption"}]}},"error":"Request rejected by the server","responseText":"<h1>Server Error (500)</h1>"}

**Comment by szabozoltan69** [comment]
According to the error log the problem was:
django.db.utils.IntegrityError: duplicate key value violates unique constraint "informal_update_informal_informal_update_id_count_024d4ea9_uniq"
DETAIL:  Key (informal_update_id, country_id)=(10, 82) already exists.

So this should be (?) unique: **informal_update_id, country_id**

**Comment by mmusori** [comment]
Informal update testing:

Great work a few remarks. 
Input template
1.	The title should not have Request at the end. It should be Flash Update. 
 
![image](https://user-images.githubusercontent.com/7780809/154954200-07ed51e0-5a45-44e7-b496-317e4f4b738c.png)

2.	I cannot add more regions/provinces
 
![image](https://user-images.githubusercontent.com/7780809/154954225-5b4bf371-7820-49df-a594-7c722445a5a6.png)

3.	Automated Title is great but not editable? I need to test for the updated informal update.
 
![image](https://user-images.githubusercontent.com/7780809/154954286-a08e7d71-6e8a-4f3c-b2c1-4594d0145cd9.png)

4.	Situational Overview *
It does not have a rich text editor. It would be great to have this for formatting the free text. 
 

The Report https://dsgoproxyapp.azurewebsites.net/informal-update/11


1.	There is no situation overview
2.	The imagines are not showing maybe my internet

**Comment by frozenhelium** [comment]
Thanks @mmusori @tovari @szabozoltan69 !
We'll fix it ASAP!

**Comment by mmusori** [comment]
The label should be , " Select Region / Province" not only "Select Province". 
![image](https://user-images.githubusercontent.com/7780809/155143390-7cb5158b-0fa7-4ba1-a345-d865b6f86e42.png)

**Comment by tovari** [comment]
A few more notes:
- [ ] Subscription - we need a subscription option for Informal updates per region (Americas, APAC, Africa, Europe, MENA)
- [ ] Share button doesn't work at the moment
- [ ] Document download issue: 
![image](https://user-images.githubusercontent.com/68283148/155164114-1205bfd0-71f6-4953-a2ef-74a1e550d0de.png)
It results a page not found error.
- [ ] Situation overview is missing from the report page
- [ ] Donors - should be able to make custom groups of donors. E.g. 'MENA donors' would consists of donors that support MENA operations. These groups could be used while sharing the Informal update
Is this correct @mmusori?

**Comment by tovari** [comment]
A few more items to be updated:

- [ ] Please change the 'Foreign Society' to 'RCRC' on the form:
![image](https://user-images.githubusercontent.com/68283148/165103551-2d6b5186-6ab7-451e-91db-d27e3e235ebc.png)

- [ ] Notification emails are not submitted by GO.
- [ ] Notification emails should contain the 'Situation overview' section and then 
'The full report can be downloaded here: [link]'

- [ ] Text indenting doesn't work on the UI. See here:
![image](https://user-images.githubusercontent.com/68283148/165105433-7f3e182a-a34c-49e0-a124-e57d5deb753c.png)

![image](https://user-images.githubusercontent.com/68283148/165105562-0a6126ff-d66f-4465-a4d3-6eb957c9ac8e.png)

**Comment by mariam-yu** [comment]
@frozenhelium One more item/question (CC @mmusori )

**_Flash Update page_**
- [ ] We currently don't have an open input field from the front-end to share the page with anyone the user wants (open-ended). If it's possible to add, we may want to do that, given we can customize the sent out email notification, i.e. can we have the email that is sent out for Flash Update appear as if it's sent from the user? This way the users may read it rather possibly skip thinking it's a GO auto-generated email.

Thanks!!!

**Comment by frozenhelium** [comment]
@mariam-yu 

#### General
For the cancel button, I think we should do it together with other forms.

#### Context
We've put the first delete intentionally and disabled it because, it aligns with the list below. If we remove the first delete, it'll look a bit odd (i.e. first element in list will not align with the rest of them). Please let us know your thought, we can change it if necessary
![2022-05-13-121050](https://user-images.githubusercontent.com/4931541/168223899-803d0c40-ba47-4d39-8b16-d7c709de11c9.png)

#### Focal points
Since the button at to top says "Save", and the last button does the same action, so we thought it might be a bit confusing for the user (To have two buttons, "Save" and "Submit, doing the exact same thing). Please let us know your though, we can change it if necessary.

#### Flash Update page
We've update the UI to closely match the mock-up, except for the maps section. Since user can upload the maps of different aspect ratio, it'd be a bit difficult to implement how it is shown in the mock-up. Maybe we can discuss it further if necessary.

Regarding the direct sharing and to make email appear as sent by user, we need to discuss it further and also explore the possibility

**Comment by mariam-yu** [comment]
@frozenhelium thanks fo your feedback. A few comments:

1 - For the Cancel sounds good. Makes sense to keep it standard across.
2 - Delete button, I think it's better to remove, it's weird to have something that's not functional. 
3 - There should be difference between Save and Submit. Save is while in Progress, Submit is to say that I'm done. Even if in theory it's the same, since the user can edit after. I'd say we need to rename to Submit (CC @mmusori )
4 - Sounds good for the maps, no problem
5 - For sharing, yes, let's chat (CC @mmusori )

**Comment by tovari** [comment]
@frozenhelium, the form submission should be available only to users belong to the IFRC org. The option should be hidden for other users.

**Comment by tovari** [comment]
@frozenhelium, one more request about content visibility. As it should be shared within IFRC only, we don't need the visibility options. Its enough to indicate on the form that 
'Share with IFRC Secretariat
Clicking Submit will send an email notification with the Flash Update to the selected groups.'

**Comment by frozenhelium** [comment]
@tovari to summarize, there should only be one checkbox saying `Share with IFRC Secretariat` right?

**Comment by mariam-yu** [comment]
@frozenhelium @tovari I took the liberty of updating this quickly on the wireframes: https://www.figma.com/proto/uRgMamNHRi5KhhroYDwuxN/IFRC-GO---Wireframes?page-id=0%3A72&node-id=104%3A22613&viewport=42%2C322%2C0.02&scaling=scale-down-width&starting-point-node-id=111%3A0&hide-ui=1 How about something like this? Disclaimer that states the content will share with the secretariat only. Either way, it shouldn't be a checkbox, since it's not a selection but a default. Thanks!

**Comment by tovari** [comment]
Thanks, looks great already!
A few things could be improved in the pdf export and notification email:

- [ ] Notification email subject should be 'Flash Update: [Title]' e.g.: 'Flash Update: Albania - Serbia - Drought 06/2022' 
- [ ] Pdf export, Actions descriptions: somehow the new lines appear only on the site, but missing from the exports. See: https://go-stage.ifrc.org/flash-update/18/
![image](https://user-images.githubusercontent.com/68283148/172653130-6d8f3241-3942-4472-8af1-6c61391512c0.png)

- [ ] PDF export: Reference documents: we need to group the details of the references visually. Maybe line spacing could be decreased between date, title and url.
- [ ] Pdf export: Reference documents: Would be great to include the link to the reference document as well. E.g. [Download document](https://dsgofilestorage.blob.core.windows.net/api/flash_update/images/MDRBD018_1.pdf)

**Comment by tovari** [comment]
Thanks @frozenhelium, we are getting there.
I noticed an error in case a reference document is only mentioned, but not attached:
https://go-stage.ifrc.org/flash-update/19/
1. Can't make a pdf export (the Export button symbol rotates infinitely)
2. The url alignment is shifted to right:
![image](https://user-images.githubusercontent.com/68283148/174816390-bc81d5f1-e42a-412e-9a78-9654ca0cdd74.png)

**Comment by tovari** [comment]
Thanks @frozenhelium, it works now.
4 small things to update:
- [ ] Email notification title
- [ ] On the Flash update page, new lines are not visible, the whole text is in one paragraph:
https://go-stage.ifrc.org/flash-update/20/
![image](https://user-images.githubusercontent.com/68283148/175057138-58312f0e-d876-4823-83a1-70013518d5cb.png)
It is correctly displayed on the admin page, in editing mode on frontend, as well as in the pdf export
- [ ]  pdf export: Please change 'Graphics' to 'Graphics and Maps'
- [ ] pdf export: Please remove the 'url: ' prefix from the reference document url line

**Comment by tovari** [comment]
Thanks @frozenhelium, all these work as expected. One more small thing has been noticed:

- [ ] pdf export: The aspect ratio of embedded graphics and maps have been modified (squeezed to square). Compare: https://dsgofilestorage.blob.core.windows.net/api/flash_update/pdf/flash_update_j31mDvT.pdf 
https://go-stage.ifrc.org/flash-update/21/

**Comment by mmusori** [comment]
Thanks for the work on the informal update.  Just one last thing. 
**1. Rich Text editor**

- I used numbers which came out as bullet points in the report
- The indentation works in creating the report but it is not reflected in final product
- Not sure if headers (Paragraph) actually work. 
- Bold and italic work.

 Input
 
![image](https://user-images.githubusercontent.com/7780809/178484527-a3fc3fdc-d79e-448e-80c3-3d345f493bc1.png)


Output
 
![image](https://user-images.githubusercontent.com/7780809/178484527-a3fc3fdc-d79e-448e-80c3-3d345f493bc1.png)

2. We need to agree on the activities and come back to you.

**Comment by tovari** [comment]
> There is a subset of all the HTML tags that are allowed to show only. Can be more wide than now, if needed.

Yes, it would be good to allow those that are available in the rich text editor throughout the site.

**Comment by szabozoltan69** [comment]
Well, in this case it is questionnable that this kind of safety filtering (sanitizing) is really needed, what we use, if we really want ALL the available HTML tags (except the ones which are set in rich text config, e.g. opacity).

**Comment by tovari** [comment]
From user perspective, if we offer a functionality (e.g. numbered bullet points in this case) then it should work.
The other option (not sure, how feasible it is) would be to disable those functions in the rich text editor which don't work on the frontend.

**Comment by szabozoltan69** [comment]
Fair enough.
@frozenhelium – could you please extend this https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/RichTextOutput/index.tsx#L13-L24 list with the most frequent (and safe) formatting elements, such as dd, dt, ol? (Indentation and numbered list). I suggest also table, thead, th, tr, td (table formatting).

**Comment by batpad** [comment]
We should check a few things:

 - The configuration for the ckeditor allows users to add only some tags, and not the entire options. We should use the same options wherever we use ckeditor.
 - When outputting the result of the ckeditor on a page, use the RichTextOutput element AND ALSO make sure the CSS for the page is styling things as users would expect (i.e. `ol` ordered lists have numbers, etc.)

Unfortunately, we do need to maintain a whitelist of HTML tags and perform the sanitization, because otherwise we open ourselves up to a host of security issues. We should definitely ensure there is no mismatch - i.e. if we allow a user to mark-up text with some tag in the rich text editor, we should support it in the output: but we should limit the options in the rich text editor as well to not allow everything.
