### ISSUE TITLE
[PROD] Surge Emergency page country deployed to wrong

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2179]
## Issue
In the Rapid Response Personnel section in the Surge tab of an Emergency page, the Country deployed to is showing the country linked to the Emergency page, which is not always correct when we have multiple countries emergencies. We had solve this issue by displaying the country deployed to that was being pulled from Molnix, perhaps the las released set it back to before the fix.

![image](https://user-images.githubusercontent.com/69478743/148238199-464d05c3-ef74-4341-a38d-879c2f82485d.png)

## Steps to reproduce
Go to this Url https://go.ifrc.org/emergencies/5567#surge and hover the gant bar, this person should be deployed to Tajikistan and not Switzerland.

## Expected behaviour
The country the person is deployed to should be pulled form Molnix and not from the one associated with the Emergency page.

## Impact
All users trying to access the deployment information from operations with multiple countries.

## Severity
Functional impact to a field operation

## Is there a workaround?
There is no manual walk around this issue.

@tovari @batpad @szabozoltan69

**Comment by batpad** [comment]
> We had solve this issue by displaying the country deployed to that was being pulled from Molnix, perhaps the las released set it back to before the fix.

@anamariaescobar are you sure this was ever fixed? As far as I know, this was discussed, but we have not implemented this yet. Really sorry, this likely slipped through the cracks.

Right now the logic is still that Deployments are associated with emergencies, and the country is pulled from the country of the emergency.

The implementation could maybe use a bit of discussion, but I think there's roughly two options here:

### Option One: New Column

 - Add a new column to the PersonnelDeployment model like `molnix_countries` or so: https://github.com/IFRCGo/go-api/blob/develop/deployments/models.py#L137

### Option Two: Migrate country -> countries

 - The second option would be to change the existing `country_deployed_to` column on PersonnelDeployment to be a ManyToMany relation instead of a ForeignKey - so make it like `countries_deployed_to` and migrate the existing data, and all usage of this through the app to expect a list instead of a single country.

Option Two does seem better, but I'm a bit worried about how much we may need to change if we allow Deployments to be deployed to multiple countries - Option One does seem like a bit of a hack, but is likely easier to implement.

For either of the two options, we'd need to:

 - Modify the `sync_molnix` management command to read countries from the Molnix API, instead of reading from the emergency the deployment is associated with: https://github.com/IFRCGo/go-api/blob/develop/api/management/commands/sync_molnix.py#L148
 - Modify the serializers to output the details for the countries in the API
 - Output list of countries on the frontend

 @anamariaescobar sorry I've forgotten a bit what we had discussed around this - and couldn't find a ticket around this with any previous thoughts.

@szabozoltan69 let's catch up about this.

**Comment by anamariaescobar** [comment]
Hi @batpad, I am pretty sure we fixed this already when we fixed it for the alerts, see this tickect ##1988.

In the backend, for the deployments of the COVID-19 operation we have multiple countries being linked to the deployment:
![image](https://user-images.githubusercontent.com/69478743/148247198-347506c6-5f00-463f-b24e-004bfd62c399.png)

But now, all the deployments are being associated with Switzerland, so this means we did fixed it at some point.

**Comment by esario** [comment]
I'm not intimately familiar with Molnix and GO data models, but the second option does not feel correct to me: a single person would always deploy only to one country, not to many. For multicountry (and multiregion) emergencies, person A might get deployed to country X, while person B might deploy to country Y.

**Comment by batpad** [comment]
Ah, sorry, this was my misunderstanding - thanks @esario - I think it will be clear after speaking to @anamariaescobar - but to re-frame the problem based on my understanding:

 - Currently, if a Deployment is associated with an Emergency that is associated with multiple countries, it marks the Deployment toward the "first" country associated with the Emergency (the concept of "first" is slightly arbitrary).
 - Instead, we should explicitly store the country of deployment as comes from Molnix and not try and infer it from the connected Emergency.

This seems simpler to handle than my previous understanding of "a deployment can apply to many countries".

@anamariaescobar - right, it seems like we implemented a similar logic for Surge Alerts, but never for the Deployments. This seems reasonable to do.

In general, it seems like the root cause here again is our suboptimal handling of emergencies associated with multiple countries - there are many places in the system where the assumption is still made that an emergency will only be associated with a single country, even though we do allow a user to associate multiple countries with an emergency in the Admin (though not in the field report form). This is something we should generally ensure we handle better through the system - i.e. not assume that an emergency will be associated with a single country and ensure we handle all cases where an emergency can be associated with multiple countries (cc @tovari ).

Thanks much for the note and clarification here @esario .
