### ISSUE TITLE
[PROD] Multiple date formats from Field Reports

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-frontend#2340]
## Issue
Recently we use a reversion system (to keep tracking the different data sendings from frontend).
Due to this system we had to do a fix concerning dates: https://github.com/IFRCGo/go-api/commit/1d6dfd4c45b4102f857f9d941e6cf66e0fa2d496
In this fix I supposed that the send date is always in %Y-%m-%dT%H:%M:%S.%f%z format. It was a bad assumption, because from different non-English computers it is not true.
Frontend should convert any kind of date to that (or other, but fixed) format after reading from the user.
https://pastebin.com/6aDvmetG - error details.

## Steps to reproduce
Just send a Field Report from a browser where the operating system (!) language is Spanish/French. (It is not enough to change the language in the browser; in this case the bug is not reproducable.)

## Expected behaviour
Having a fix frontend-sent Field Report start date (not dependent from localization setting).

## Related feature
Maybe other date inputs could be consolidated as well.

## Impact
All the non-English users suffers from it, who does not use Google Chrome / Firefox / Edge / Vivaldi  browser.

## Severity
Moderate. Most of the non-English users use Google Chrome / Firefox / Edge / Vivaldi  browser.

## Is there a workaround?
Use a Y-m-d date localization operating system for FR sending.
Or use Google Chrome / Firefox / Edge / Vivaldi  browser.

**Comment by szabozoltan69** [comment]
Thanks for the thoughts of @thenav56 and @frozenhelium

**Comment by batpad** [comment]
@szabozoltan69 I am unable to reproduce this -- I tried using this plugin to change locale of the browser: https://chrome.google.com/webstore/detail/locale-switcher/kngfjpghaokedippaapkfihdlmmlafcc?hl=en-US

It's unclear to me how this can happen - I think it's pretty clear that regardless of the user locale, the browser will ALWAYS return `YYYY-mm-dd` as the `value` for an input type=date field: https://developer.chrome.com/blog/quick-faqs-on-input-type-date-in-google-chrome/

Also was unclear from your comment above: is this failing on Chrome / Firefox / Edge or working on these browsers? If it's working on these browsers, where is it failing?

Are you sure the correct answer here is not a backend fix of some sort? For eg. maybe the problem is that the frontend does not always send time-zone information, for example? So it's just `Y-m-d` but none of the `T:` stuff after? I tried many different combinations of locale, etc. locally and for the value of the date field on the frontend, always got back a consistent YYYY-mm-dd format.

Let know if there are clearer steps to reproduce this and am happy to look a bit more.

**Comment by batpad** [comment]
@szabozoltan69 ah, is this just an old version of Interner Explorer issue? I see that Internet Explorer does not support input type=date, so then it would just be whatever the user types into the box: https://www.hassellinclusion.com/blog/input-type-date-ready-for-use/

In general, I think for users of old versions of Internet Explorer, we probably just want to show an error and not display the website at all, rather than trying to fix these individual issues. If the issue is really only affecting older versions of Internet Explorer, I think let's make sure we are displaying a warning to these users and asking to use a different browser.

The other option / solution would be to add frontend validation for a YYYY-mm-dd format in case the browser does not support input type=date, but all reasonably modern browsers support input type=date and I think we have agreed that we cannot continue to support older versions of IE. So if this is the issue, let us look at the issue more like "Why are older Internet Explorer users allowed to get to the field report page at all" without a strong warning that their browser is not supported.

**Comment by szabozoltan69** [comment]
@batpad - on Chrome / Firefox / Edge / Vivaldi everything works fine, even in other language environment.
So I could not reproduce the bug.
Yes, Internet Explorer was the sinner in one case, surely.

**Comment by szabozoltan69** [comment]
Thanks for @ypyelab for helping reproduce the issue.
The other date (sit_fields_date) caused the trouble, which was not handled well (and is optional).
