### ISSUE TITLE
[Staging] RichTextOutput

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-frontend#2408]
We should use RichTextOutput field wherever we use the TinyMCE Rich Text Editor output (!), due to the mandatory useSanitizedHtml.
So this: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/views/FlashUpdateReport/index.tsx#L181
should be implemented somehow here also:

views/field-report.js:625:                <DisplaySection sectionClass='rich-text-section' ...
views/field-report.js:716:    const content = children || <p dangerouslySetInnerHTML={{__html: inner}} />;
views/Emergency/index.js:1328:                        sectionClass="rich-text-section"

(Some "dangerouslySetInnerHTML" are in "components" also, but they can be reasonable, e.g. in [components/RichTextOutput/index.tsx](https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/RichTextOutput/index.tsx#L66) or in [components/per-forms/per-form.js](https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/per-forms/per-form.js#L103) )

@batpad @frozenhelium – Am I right about it?

**Comment by batpad** [comment]
@szabozoltan69 yes, it's fine inside the RichTextOutput component because the value goes through the sanitizer here: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/RichTextOutput/index.tsx#L60 which is responsible for stripping away anything that could be malicious. So anywhere else, we should make sure we use this component to ensure the HTML is being sanitized before being output.

This would be good to fix as soon as possible.
