### ISSUE TITLE
[PROD] Surge map is very slow to load

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2419]
## Issue

The map on the Surge deployments is extremely slow to load. This seems like it's because this request is really slow to return from the backend: https://goadmin.ifrc.org/api/v2/personnel/?limit=1000&end_date__gt=2022-07-15T10%3A20%3A19.718Z

There are currently for eg. 109 "active" deployments, and this should ideally not be so slow.

It would be nice to inspect the queries generated on that endpoint, etc. to see what is slowing it down.

## Steps to reproduce

Go to: https://go.ifrc.org/deployments/overview

Expect map to load fast.
Actual is that map takes a very long time to load.

cc @tovari

**Comment by szabozoltan69** [comment]
Here is a database log of the sample query (made for another date) on the local database:

https://porgeto.hu/tmp/surgeMapSlow.txt – as http://localhost:8000/api/v2/personnel/?limit=1000&end_date__gt=2021-07-15T10%3A20%3A19.718Z

For a "count = 49" we have 226 queries, not simple ones. From api_fieldreportcontact, from api_country, from "deployments_personnel" INNER JOIN "deployments_deployedperson"...
The slowest one (according to DjangoDebugToolbar) is this: https://porgeto.hu/tmp/surgeMapSlowest.txt
Maybe an index would be fine for these?
..."is_active" = true and "deployments_deployedperson"."end_date" > ...

The api side code part is deployments.drf_views.PersonnelViewset, this:
https://github.com/IFRCGo/go-api/blob/develop/deployments/drf_views.py#L137-L254
(The longest part is the CSV output column definition, not relevant now.)

**Comment by szabozoltan69** [comment]
Thanks to @batpad it became clear that the unnecessary fieldreport queries makes this endpoint slow.
So instead of using ListEventSerializer a smaller serializer, SurgeEventSerializer was introduced.
(Also molnix_tags should be put into prefetch.)
Tested: the CSV output remains the same as before (!).
The Surge page load is decreased to 3 secs instead of minutes (as it was previously).
A lesson learned: Django Toolbar has great options to check the generated SQL queries.
