### ISSUE TITLE
Search result page

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2595]
The search result page will be loaded, when the user add search term in the Search field and also hits enter. Without hitting Enter, only the limited list of instant results pops up under the search field (as the current functionality).

The search result page design:
https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=9710%3A157300&t=iQmZepn0CI7aYqmC-0
wireframes:
https://www.figma.com/proto/uRgMamNHRi5KhhroYDwuxN/IFRC-GO---Wireframes?node-id=10393%3A31790&scaling=min-zoom&page-id=0%3A72&starting-point-node-id=111%3A0&show-proto-sidebar=1

https://www.figma.com/file/uRgMamNHRi5KhhroYDwuxN/IFRC-GO---Wireframes?node-id=10393%3A31790&t=BwQTdtSvakiHvZLH-4

The order of result lists per content type:
1. Country, Region
2. Emergencies
3. Appeals
4. 3W projects
5.  Surge Alerts
6. Surge deployments
7. Reports

Need to be able to search in the following attributes of each content type:
https://ifrcorg.sharepoint.com/:x:/r/sites/GOIVfordeveloperteam/Shared%20Documents/General/GO%202022/GO%20IM%20Sprint%20-%20September%20-%20Nepal/Search_functionality.xlsx?d=w90d23166bc544907868ed2f962fbf42f&csf=1&web=1&e=R4mPWr
![image](https://user-images.githubusercontent.com/68283148/228182029-85912338-9a8c-4122-9bff-8104e2051df7.png)

**Comment by udaynwa** [comment]
@tovari , could you please clarify what documents are to be shown in the 'EMERGENCY PLANNING AND REPORTING DOCUMENTS' section of the new Search results page? 
![image](https://user-images.githubusercontent.com/72339626/213356998-3c32a4b9-69b9-48ae-9ee4-5c707963b929.png)

cc @frozenhelium

**Comment by tovari** [comment]
As we discussed during the kick-off call:

- content type sections could be prioritized based on the relevance. E.g. if an Appeal is the most relevant then Appeals section will be on the top.
- in case multiple content types has the same relevance then the priority list (above) can be used to order the results. i.e. Country, Emergency, etc.
- if theres no relevant result for a content type, then the section can be hidden
- ordering within a section could be done by date (newest to oldest), or by relevance.
- 5 items per content type would be listed on the result page. If more results are needed, the user can open the whole list by clicking on the 'View all documents' link that will open the list on a new page

Anything to add @mariam-yu ?

**Comment by mariam-yu** [comment]
@tovari summarized perfectly!

**Comment by udaynwa** [comment]
Thank you for the summarization, @tovari.

**Comment by udaynwa** [comment]
@mariam-yu @tovari , is the expected behavior the same for both of the 'Search' bars? 
The behavior being; 
`'The search result page will be loaded, when the user add search term in the Search field and also hits enter. Without hitting Enter, only the limited list of instant results pops up under the search field (as the current functionality).'` 

If they're not, could you please elaborate the expected behavior of the lower search bar? 

![image](https://user-images.githubusercontent.com/72339626/214804786-744f39e6-b402-401a-a2c6-5693a9f8a924.png)

**Comment by tovari** [comment]
@udaynwa, as @mariam-yu explained to me, the purpose of this search field is to provide an entry field for modified/updated search terms. So the expected behavior:
- when the search page is loaded, the search string appears in that field, that was used for the search
- the user can update the string to modify the search term. when hits enter, the search page reloads with the results
- the 'x' at the end of the filed, erase the current string

@mariam-yu, should we also implement the instant search results in a drop-down just as in the top search field? We may start without this functionality, I think.

**Comment by mariam-yu** [comment]
@tovari Thanks for summarizing. I kept forgetting to respond to this, and the way you did it it's perfect. I think we can start without the type ahead. It may be later expected, since it's the same functionality as the nav search, but best to do step by step and test it out.

**Comment by frozenhelium** [comment]
Very initial version available on test server: https://ifrc-go-feature-search.surge.sh/

**Comment by tovari** [comment]
Thanks. A few notes:

- [ ]  search doesn't need to be initiated at each letter while typing in the long search field. only when the user hits enter. it would save a lot of resources.
- [ ] can't search for some specific attributes:
  - [ ] MDR codes of appeals (appeal code)
  - [ ] ISO3 codes 
- [ ] we need column headers also for the Report section (Date, Type, Title)
- [ ] the date formats needs to standardized
- [ ] at the Emergencies section please add the following columns: Country, Start date, Crisis categorization, Appeal type. Please rename the 'Active operation' header to 'Title'
- [ ] please apply the following columns at Open Surge Alert section: <html>
<body>


Alert Date | Duration | Start Date | Position | Keywords | Emergency | Country | Status
-- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

Thanks!
cc: @mariam-yu

**Comment by udaynwa** [comment]
@tovari , a quick question on 'Crisis categorization' in the Emergencies section. Is 'disaster_type' the 'Crisis categorization'? 

cc @frozenhelium

**Comment by tovari** [comment]
Crisis or disaster categorization is the 'ifrc_severity_level', which can be Yellow, Orange or Red:
![image](https://user-images.githubusercontent.com/68283148/222123184-af927a6b-61e5-4a55-8a42-fb0d11b2c6b5.png)

**Comment by mariam-yu** [comment]
@udaynwa @tovari A few comments on the Search page:

Designs: https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?page-id=0%3A4957&node-id=9710%3A157300&viewport=670%2C16539%2C0.4&scaling=scale-down-width&starting-point-node-id=0%3A4963&hide-ui=1

- In the designs, we have the search as an underline. Just to make it less boxy on the page. Thoughts on that?
- Page margins seem incorrect. Bigger than the rest of the site. Should align with the nav.
- The country or region boxes in the beginning, can we make like in the designs? The boxes take too much space, we just want a highlight of the country on top as a link. 
- For Emergencies table, View All should say All Emergencies and not Documents.
- Table design: I assume we haven't gotten to this component, so won't comment on it.
- Reports: View all, should say View All Reports
- Projects had the Emergency column empty, on purpose? And Start/End dates had weird lots of zeros.
- EMERGENCY PLANNING AND REPORTING DOCUMENTS always shows Appeal under Type. Does it say Appeal for DREF too? Also, i think we should rename that to make it simpler and not to confuse with "Reports". I suggest Emergency Documents. @tovari Thoughts?
- Was slower to load than usual for me.
- If no matches, should we say no matches for your search? Now, it's always showing something (@tovari what do you think?). May be a better direction would be to say No matches for your search, but still show some suggestions below, since I assume it's still pulling the closest match?
![screencapture-go-stage-ifrc-org-search-2023-03-06-21_30_49](https://user-images.githubusercontent.com/60006476/223223727-45ba0640-7066-4ab9-9a61-476a701ba791.png)
- No matches for MDR code (and may be let's avoid query? Sounds too dev. I'd say No matches for your keyword search, or something like that).
![screencapture-go-stage-ifrc-org-search-2023-03-06-21_31_37](https://user-images.githubusercontent.com/60006476/223224122-58be1f5f-4aaf-48fa-a18c-23fe0373e8bd.png)
- We normally have our links turn red on hover, but don't think it's implemented on the site.https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=499%3A6703&t=6VayYQTyZZDQHckL-4
- When I type, say, Madera, Reports come first, thought Emergencies should always be first, since multiple matches. Also, @tovari thoughts on Calling this operations instead of Emergencies?
- Shall we add some dates to the Emergencies table, since it's not clear how they are sorted within (I assume latest first).
- When on the page, the top nav search didn't work for me. The enter didn't work.
- The page title for some reason says 3W Details.

Also, as we are on the topic, a few comments for the main Search in the nav: 
- Why do we need the dropdown arrow? It's not really a dropdown, so we should remove that.
- When I type in Africa, it shows: Country: Afghanistan.

@tovari I think we should do a quick test with some users to get feedback. Also, think we may need to review the columns for tables and whether it's too table heavy, but otherwise, it's great @udaynwa and team. Super addition.

**Comment by tovari** [comment]
Thanks @mariam-yu for the review.
_> * EMERGENCY PLANNING AND REPORTING DOCUMENTS always shows Appeal under Type. Does it say Appeal for DREF too? Also, i think we should rename that to make it simpler and not to confuse with "Reports". I suggest Emergency Documents. @tovari Thoughts?_

DREF is technically an appeal as well. There might be documents at DREF, like Ops Learning and Final report. 
Honestly, I'm not sure, if the Emergency planning and reporting documents section is very useful at the moment. The related emergencies can be found anyway in the Emergencies section, so the user can easily navigate to the related reports. Secondly, there might be a lot of document at each emergency which makes the result list potentially too long and difficult to prioritize the most relevant docs. Thirdly, we don't have yet the capability to search in documents at all, not even for tags, so it won't be able to bring additional value. 
I think, we should ask more people about this. 

_>If no matches, should we say no matches for your search? Now, it's always showing something (@tovari what do you think?). May be a better direction would be to say No matches for your search, but still show some suggestions below, since I assume it's still pulling the closest match?_

I like this idea, would be great to see some close results even when there is no exact search result.

_> * When I type, say, Madera, Reports come first, thought Emergencies should always be first, since multiple matches. Also, @tovari thoughts on Calling this operations instead of Emergencies?_

For some reason the score is higher for FR, I guess. I tend to think that we should follow the pre-defined order of sections. Not sure though.

> 
_> @tovari I think we should do a quick test with some users to get feedback. Also, think we may need to review the columns for tables and whether it's too table heavy, but otherwise, it's great @udaynwa and team. Super addition._

Indeed. I suggested already a few updates on the table columns to match tables on other GO pages. I assume, it would bring the most relevant ifo and consistency.

**Comment by batpad** [comment]
> They're sorted on the basis of their score. Not the latest first.

> I like this idea, would be great to see some close results even when there is no exact search result.

> For some reason the score is higher for FR, I guess. I tend to think that we should follow the pre-defined order of sections. Not sure though.

Sooo ... this scoring, relevance and ranking of results is going to be a long rabbit hole and lots of tuning we can do. The "relevancy score" calculated is all a bit of magic, and django haystack / ElasticSearch gives us a lot of levers to turn to tune relevancy of matches, but that will likely be a constant process that we improve, and we shouldn't try and get the relevancy stuff to be "perfect" to deploy this. We should discuss this though: an alternate approach would be to not really use the relevancy score to order results, and just order by a pre-defined parameter for each section, like date. I kind've like the idea of continuing to use "score" and then continue to tweak parameters to make things we want to show up come up. Let's discuss on dev call a bit.

> When I type in Africa, it shows: Country: Afghanistan.

There's a few cases where you can search for something and can be unsure of why a result has appeared. This is because there are a lot of fields that we are using to search through, but are not displaying in the result. As far as possible, we should try and include all the fields that are being searched for an entity, in the result / display on the search results page. We should do this as a first step. As a next step, we might want to look into some helpers in django haystack that would allow us to pull up the relevant text where the search result was matched, show a snippet with the matched word AND highlight the matched word so it's very clear when viewing a result, why your search corresponds to a certain result. Again, getting to the "perfect" solution here is a bunch of work, so let's figure out a good in between to be able to release, and then ticket out improving things.

**Comment by mariam-yu** [comment]
@batpad and @udaynwa I was thinking that the tables are selected based on the score (i.e. first match is an emergency, so we show the emergencies table), but then we sort by date. Actually, by score and then by date. For example, if we search for something generic like Philippines, then the result can be equal across, since it's an equal match to emergencies, reports, etc. So, in this case the sorting should happen based on our list (i.e. emergencies first), and within emergencies table we sort by latest first, since all the operations will have "Philippines" in them.

However, when searching for a more specific combination, we can prioritize the score both in tables and within tables. Is this doable? (cc @tovari for your point too).

Then @tovari I think we still need the documents section, since I think people a lot of times will be looking for a specific appeal or DREF file and having it here will help them get to it faster, rather than through the EM page. But may be instead of EM docs we just show Appeal docs? not sure if anyone would be looking for other EM docs (they may though). It's just the Appeal type is not a useful column if it always says Appeal. I think it's the type of Appeal, is it DREF or others. Not sure if currently it has that categorization. Thanks!

**Comment by tovari** [comment]
- [ ] Emergency planning and reporting - Title - link is incorrect as it uses the appeal_id in the link instead of the emergency id

**Comment by udaynwa** [comment]
@tovari , for this;

> Flash updates are not searchable
The Flash updates are actually searchable at the moment. We have limited the number of results to 50, so the Flash Updates are not showing up in the results since Field Reports in the results have more scores than Flash Updates.

Here is an screenshot: 
![image (20)](https://user-images.githubusercontent.com/72339626/228437041-0784a2a6-4529-4560-be46-8cbc8d1d34bc.png)

And here is the link of the results: https://go-stage.ifrc.org/search/?keyword=Switzerland

cc @frozenhelium

**Comment by tovari** [comment]
A few more tiny updates before the release:
- [ ] Update the text under the search field: 'The search results page is new to GO. Can't find what you're looking for?'
- [ ] Crisis category indicator dot is orange, while the the hower text shows yellow
- [ ] EMergencies - https://go-stage.ifrc.org/search/?keyword=ukraine%20crisis - Country info list all countries without any separator. I suggest to display 'Multiple countries' without link

**Comment by udaynwa** [comment]
@tovari , we have implemented the above-listed updates. They can be verified on Staging.

For the 3rd point, we are now showing the countries like this in a pop-up;
![image](https://user-images.githubusercontent.com/72339626/229264694-17b5a43c-0e3f-4b40-8822-8965a24b5c44.png)

Let us know what you think about it. 

cc @frozenhelium
