### ISSUE TITLE
[PROD] All Surge Alerts showing as Open in All Surge Alerts table

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2612]
## Issue

If we look at the Open Surge Alerts table on this page: https://go.ifrc.org/deployments/overview - we see a limited amount of Surge Alerts that are Open - this table shows the correct Open Surge Alerts.

However, if we go here: https://go.ifrc.org/alerts/all you can see it is showing ALL the surge alerts as Open when they should not be.

## Steps to reproduce

Go to https://go.ifrc.org/alerts/all - see even Closed and Stood Down Alerts marked as Open when they should not be.

## Expected behaviour

The Surge Alerts should show their correct status. I think there's a `status` field in the db that we need to check, but we may need to confirm with @anamariaescobar exactly what should be the status displayed for the Alerts.

What I would suggest we do:

 - Look at the logic in the all surge alerts table. My guess is we are not really handling the status there and just defaulting to showing "Open".
 - Check the logic by which we decide that a surge alert is "Open" on the table at https://go.ifrc.org/deployments/overview and on emergency pages, since that logic is correct. Use that logic to mark alerts with the correct status on the All Alerts table. We possibly will need a call / clarifications from @anamariaescobar to know what the correct displayed Status should be for different logic for the Alert.

@szabozoltan69 does this give you enough to get started to look at this? Thanks!

cc @tovari

**Comment by szabozoltan69** [comment]
For the "overview" there is a "greater than" time limit:
.../api/v2/surge_alert/?limit=5&ordering=is_stood_down&created_at__gte=2022-12-25T00:00:00.000Z&is_active=true&offset=0
For the "alerts/all" page:
.../api/v2/surge_alert/?limit=50&ordering=is_stood_down&offset=0

**Comment by szabozoltan69** [comment]
Recently we have these statuses on prod (and the same ones on staging with different counts):
```
molnix_status|count|
-------------+-----+
             |  857|
unfilled     |  114|
active       |  551|
```

**Comment by szabozoltan69** [comment]
The definition on frontend: every Surge Alert is "Open" which is not "is_stood_down":
https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/connected/alerts-table.js#L230

**Comment by anamariaescobar** [comment]
Hey @batpad and @szabozoltan69, just to clarify the expected behavior for the Alerts:

the Alert should be Open y the current date is between the Open alert date and the Close alert date. Once the current date is outside that range the alert should be classified as Closed (unless the alert is being flagged by Molnix as stood down)

Does that makes sense? Let me know if we should jump in a call!

@tovari

**Comment by szabozoltan69** [comment]
(We should find the place where some job or other database trigger considers the expiration as "it's time to change it to Closed". Surely it exists somewhere.)

**Comment by batpad** [comment]
@szabozoltan69 I don't think we need to store this in the database and can just calculate it at request time. Am just not fully sure if we should do this filter / marking as "open" / "close" on the backend or frontend.

**Comment by szabozoltan69** [comment]
Just an example of emergency 5881. On https://go.ifrc.org/emergencies/5881#surge we can see:
![kép](https://user-images.githubusercontent.com/6050643/214598606-80207dce-4f90-4049-bc1b-cc6f7af0b6d6.png)
But this can not be seen on the [global overview](https://go.ifrc.org/deployments/overview). The reason:

There is a difference between the global overview and the 5881-emergency-related request.
The global one uses a created_at limit also: 
but the 5881-emergency-related page uses only these:
So, the created_at is earlier than 2022-12-26 (exactly 12-22), that is why we can not see it in the global page.

**Comment by szabozoltan69** [comment]
The is_active flag is set this way: https://github.com/IFRCGo/go-api/blob/develop/api/management/commands/sync_molnix.py#L199-L207

**Comment by tovari** [comment]
Is it a requirement to show open alerts from the past 30 days maybe? 
We use to show operations from the past 30 days earlier. Is this filter maybe taken from there during the implementation?
I don't see the reason for a time filter, but @anamariaescobar may have other toughts.

> 
> There is a difference between the global overview and the 5881-emergency-related request. The global one uses a created_at limit also:  ![kép](https://user-images.githubusercontent.com/6050643/214598945-aef6c6f4-8cfc-4202-b1d6-f11262643381.png) but the 5881-emergency-related page uses only these: ![kép](https://user-images.githubusercontent.com/6050643/214598995-f2db9c66-bba0-48e9-93de-6fcaf225aa63.png) So, the created_at is earlier than 2022-12-26 (exactly 12-22), that is why we can not see it in the global page.

**Comment by tovari** [comment]
Thanks @szabozoltan69! It looks good.
I couldn't find out though, how the alerts are sorted in the table (neither on prod). I think, they are in a random order.
Would you mind to sort them by alert date, while keeping the 'stood down' status alerts at the end of the list?

**Comment by szabozoltan69** [comment]
I will, and also @batpad suggested the consideration of the "end of mission" date, as they should not be shown as "Open", even if they are not stood-down.

**Comment by szabozoltan69** [comment]
So these are the 3 appearances of Surge Alerts:
 https://go.ifrc.org/alerts/all
 https://go.ifrc.org/deployments/overview
 https://go.ifrc.org/emergencies/5881#surge  e.g.
The Closed ones should be shown only on the "all" page (due to the name of the table is "Open"... on the two second pages).
The order should be what? Open, Stood Down, Closed?

**Comment by batpad** [comment]
@szabozoltan69 I think for order something like ORDER BY DESC by `open` date or so I think should be good.

**Comment by anamariaescobar** [comment]
yes @szabozoltan69, Open, Stood down and closed

**Comment by batpad** [comment]
> yes @szabozoltan69, Open, Stood down and closed

@anamariaescobar is that for the ordering? But on the all Alerts table, we might want them ordered first by Emergency or so? Or overall on the All Alerts table we should always display Open alerts on top, then Stood Down, then Closed? This would be across all events.

On the emergency and global surge pages, I think we already show Open alerts first, then Stood Down? So this is really a question for the All Alerts table of what the ordering should be..

**Comment by anamariaescobar** [comment]
Yes, for the emergency pages we are already orderind open and then stood down.

I think the All alerts table should follow the same logic, having Open on top then stood down then closed one (ordering by date inside the 3 groups). @batpad

**Comment by szabozoltan69** [comment]
Let's have a "golden mean" this time, which solves the original issue, for which this ticket was opened.
The reason is: it is not easy to create those 3 groups.
What I can offer now: make 2 groups: _Opens+Closeds_ and _Stood downs_, both are (descending) ordered by Alert Date.

To have 3 groups – it's a major work, to introduce a new entity on backend side (and to populate it in database).
@anamariaescobar @batpad?

**Comment by szabozoltan69** [comment]
Example:
![kép](https://user-images.githubusercontent.com/6050643/215771568-3c275df4-8ab3-428b-9f44-406c39093848.png)
... at the end:
![kép](https://user-images.githubusercontent.com/6050643/215771695-3dd0ac7a-80f9-4e7a-9319-f4a748e1c804.png)

**Comment by anamariaescobar** [comment]
@szabozoltan69 that works for me! :)

**Comment by anamariaescobar** [comment]
Tested in staging and working perfectly!!! Thanksss @szabozoltan69

**Comment by szabozoltan69** [comment]
The /alerts/all remained in that fashion, so that there is no time limit, just ordering: is_stood_down,-created_at
The other two tables (overview and emergency-wise), where it is said to be "Open Surge Alerts", these are the search parameters:
![kép](https://user-images.githubusercontent.com/6050643/216692224-722739c0-5b69-4509-a69b-1bc6105574c9.png)
![kép](https://user-images.githubusercontent.com/6050643/216692735-a3053276-6216-489b-bf06-0946fdb38697.png)
So we exclude the Closed ones this way in the overview and emergency-wise tables, where it is said to be "Open Surge Alerts"

**Comment by szabozoltan69** [comment]
Deployed to Staging
