### ISSUE TITLE
Determining a disaster's start date

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#27]
For the front end we will need to show aggregate statistics for the number of disasters in the last month (although since months vary in length, I would recommend using last 30 days instead of last month). I'm opening this ticket since I can't remember if we decided on what property to use for this.

I think the most straightforward would be to use the `start_date` of the earliest appeal and the `end_date` of the most recent appeal to determine when the disaster is active. If we used this, then a disaster would show up on the disasters page for 30 days after it's last appeal ended.

@ascalamogna @renecnielsen did we decide on this already, and if not, what are your thoughts on this approach?

**Comment by renecnielsen** [comment]
This is harder than I'd like to admit. Appeals are by design _not_ opened when the disaster strikes. Often a few weeks will pass between disaster and launch of an appeal. The start date for an Emergency should in our case come from GDACS or we could manually add it in the Emergency Page admin. I would also suggest that we ask for it in the Field Report (which could then be manually overwritten in the Emergency page admin). For example here: 
<img width="2368" alt="field_report_1__basics__pdf" src="https://user-images.githubusercontent.com/1473552/33578791-ff389d48-d947-11e7-8147-1e6f1d6df442.png">

Remember, we will use `Emergencies` from the last 30 days (fully agree on that) for an overview of what we need to consider responding to, whereas `Ongoing Operations` are an overview of what we currently responding to (DREFs and Appeals with `start_date` in the past or today and `end_date` today or in the future.

Does that make sense, @ascalamogna or @dereklieu?

**Comment by dereklieu** [comment]
Ok, this gives me enough info to know that the appeal start date should not correspond to the disaster's start date. I think for simplicity's sake, the disaster should have it's own start date that corresponds initially with the time the object is created, either via field report, admin, or by gdacs alert. Someone will have the option to change that start date when they go into add additional information through the admin.

**Comment by renecnielsen** [comment]
That would be ideal. Thanks!
