### ISSUE TITLE
Mapping emergencies should include 90 days and be better labeled

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#311]

**Comment by LukeCaley** [comment]
The labelling should be also point more clearly towards scale of emergencies.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Any chance of showing the emergencies for the past 90 days instead of 30 (both in the map and the tables). If not in this phase, let's move this to phase 3.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC So you mean the upper part, the map of the /emergencies page? (Because there is a "30 days" also at the lower part of the same page, with a table.)

Let's move this to phase 3. I found the relevant source (emergencies-dash.js) but the same "lastMonth" is used at multiple parts, and I may miss up things. (And I still don't see where this lastMonth is defined...)

**Comment by dereklieu** [comment]
Just ticketing the contents of an email I wrote to @szabozoltan69 on this topic, so that knowledge of it exists for future phases.

The map and the table on the emergencies page at https://go.ifrc.org/emergencies have different methods of determining the interval to show (ie last month).

For the map, it relies on a method that is only used by itself, and you can simply set the date differently in this method. I would leave a comment as to why the method named getLastMonthsEmergencies returns more than the last month.

https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/actions/index.js#L139

The table is trickier as it relies on a recentInterval method that is set to 30 days. This is used by ALL tables in Go where there is an option to only show a recent slice of the data.

Definition of the variable: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/format.js#L176
How it's used: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/connected/emergencies-table.js#L87

You could change only this table to use the 90Days variable instead, but it would change all emergency tables that show recent emergencies to show 90 days instead of 30. So, you should look everywhere that EmergenciesTable is rendered and make sure it's titled properly.

**Comment by szabozoltan69** [comment]
Thank you, Derek, for the relevant quidelines; so I change
getLastMonthsEmergencies to 
getLast3MonthsEmergencies everywhere, because this way I change only the emergency-dash ( = map and above it) properties and not the table. This ticket wants only this.
@ElsaRaunioIFRC please test it (after 11:00) and close this ticket, if fine.

**Comment by szabozoltan69** [comment]
Old an new view:
![em30](https://user-images.githubusercontent.com/6050643/49576631-eed81b80-f945-11e8-8acf-4bb5cc8b41c9.png)
![em90](https://user-images.githubusercontent.com/6050643/49576638-f3043900-f945-11e8-84c7-c5435f457982.png)

**Comment by nanometrenat** [comment]
Closing this ticket, any further work will be covered by #916
