### ISSUE TITLE
Table export button should directly execute a download of CSV data

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#325]
It's cumbersome to have users go to the DRF browsable API. The button should just download CSV data directly.

**Comment by LukeCaley** [comment]
The csv exported using the 'export table' button only exports for the currently viewed rows and not the entire table.  e.g. On Africa DREF page (https://dsgoproxyapp.azurewebsites.net/appeals/all?atype=dref&region=0 ) will only export the first 50 rows displayed.
The user should be able to acquire the full table from the export table or, if there is a risk that that might require too many resources, then be given an alternative method to get the full dataset.
Also, it would be good if the downloads were given appropriate names, although this is probably a nice to have rather than a must have.

**Comment by mmusori** [comment]
It  is now working  but, the file extension is not clear. With a proper extension then the computer can recognise which software to use to open.

**Comment by dereklieu** [comment]
@mmusori I think we can set an extension, although it would require a small hack. Unfortunately the browser treats CSV as plain text, and that's why it gets saved as such. 

@LukeCaley Currently we do offer an alternative method. Users can download the entire appeals dataset for example by hitting this link:

https://dsgocdnapi.azureedge.net/api/v2/appeal/?limit=9999

It's up to you how you'd like to make this knowledge accessible to the power users who would require such a dataset. 

Also, the export button will export the data that you're currently viewing. If you're viewing records 51-100, it will export those. If you apply a filter or a sort, the export will reflect that.

**Comment by dereklieu** [comment]
Ticket opened in #364
