### ISSUE TITLE
Misleading line graph

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#361]
The trend line on each of the operations line graphs appear to display a downward trend in the most recent month/year as this is not yet complete data.  Suggest to indicate this through use of dotted line for the final month/year.  

Could also provide a projection based on where we are in the month / year if well explained.

**Comment by dereklieu** [comment]
I'm not sure how difficult it would be to change the style of the line for the last (or current) month, since we're using a third-party charting library, so I'm assigning this a relatively high LOE. 

I think a projection would be prone to misunderstanding. An alternative is excluding the current month and just showing the last, complete month, which would be a 1 hr task.

**Comment by LukeCaley** [comment]
Agree that a projection could cause misunderstanding, even if a dotted line.  In which case can we just remove the most recent month.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Would it be possible to remove the current month from the graph?

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Well, I can try it. But – to tell the truth – I don't find it a good idea. To say a simile: it is like the usage of the hand brake in a car. We used to use it on a slope. We know it's role. The same is with these graphs: we know that the last month  is imperfect. It has some information-content (at least more than the nothing – if we remove it).

**Comment by nanometrenat** [comment]
@LukeCaley can you please confirm if this proposed change (to omit current month from chart) is still required and close if it's not?

**Comment by LukeCaley** [comment]
Not a priority at this stage.
