### ISSUE TITLE
Django Back End

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#385]
## Issue

The back end is not user friendly, when it comes to the deployments tab.

1. What is the difference between *Personnel* and *Personnel Deployments*?
2. Why is the *PNS Activities* in the "Deployment" section? As well, this should be renamed as PNS activities is wrong. I believe you had talked with this one with @LukeCaley 
3. What is the concept of the "PNS Deployment"?

As well, when looking into the ERUs - it is not user friendly to understand:

1. How to state availability versus the deployment;
2. What is the difference between *units* and *equipment units*? This is quite confusing.

As this section will be going to our National Societies to be used, I believe more clarity on naming standards and improved user-navigation/understanding should be done on the deployment section of the django framework.

**Comment by dereklieu** [comment]
1. Personnel are the individuals, and personnel deployments are groups of people deployed from a single country. They both concern the same data, but are different ways of organizing. A country director might have permissions to edit both individual personnel, and personnel deployment groups. An individual who is deployed might only edit individual personnel.
1. What should PNS activities be renamed to? I haven't discussed this with anyone prior. It is in deployments because it concerns PNS deployments.
1. The PNS deployment powers the information shown on country pages. Please speak to @LukeCaley about this for further clarification.

ERUs:

1. A check mark on the available column indicates it is available.
1. We added equipment units on request, however I also find it duplicative. This was to differentiate between personnel and equipment ERUs. I don't have enough organizational knowledge to say whether we should remove one or the other, however in the front-end we only visualize equipment units. Waiting on your input here.

**Comment by LukeCaley** [comment]
Re: 2: Why is the PNS Activities in the "Deployment" section? 
Agree that this is problematic from a back-end point of view as it seems as if it is driving the deployments page, when actually it is surfacing on other pages.  suggest creating a separate section titled '3W - who what where'.

**Comment by LukeCaley** [comment]
Re the front-end display of 3w.  There was discussion on this here: https://github.com/IFRCGo/go-frontend/issues/359 but no clear direction, sorry for that.  Essentially, we would like to change the PNS terminology for 'Movement Activities in support of NS'.  
Change 'PNS Activities' to 'Movement Activities in support of NS'
Change 'Activities by PNS' to 'Activities'
Change 'Type of activities' to 'Type'

**Comment by dereklieu** [comment]
Changing the section is unfortunately not simple, as the sections correspond to different applications. I was able to edit the name of the deployments to something more fitting:

![screen shot 2018-08-02 at 5 35 47 pm](https://user-images.githubusercontent.com/1590802/43612494-82b1e9aa-967a-11e8-8b0f-0d07cf92037b.png)

Ideally you would manage user permissions so that those responsible for inputting the PNS records would only have access to those, and thus wouldn't see the deployments-related items.
