### ISSUE TITLE
Country and Regional Page structure

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#386]
Can the structure of boxes be changed or is it too complicated?

**Comment by dereklieu** [comment]
Could you be more specific please? Generally we're not making layout changes at this point. Phase 2 has officially already ended, and we are just wrapping up bugs at this point.

**Comment by guipizzini** [comment]
Could we have the list of countries at the bottom, as a last section for the regional pages? Having it in the middle, makes it a bit blury in terms of understanding.

As well, the statistics (graphics) could be placed in a more user friendly and strategic way I would say.

@LukeCaley what are your thoughts?

**Comment by LukeCaley** [comment]
Agree that the natural order should be operations first and then country links afterwards.

However many users do navigate to the regions pages in order to jump straight into a country page so useful to add a banner link to country list as below:
![image](https://user-images.githubusercontent.com/7791954/44407880-75b3e480-a55f-11e8-9993-f369bcb19b76.png)

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC My problem is that the /countries itself does not show anything, we should find out the design of this page. It can be time consuming to figure out. Or can you suggest me an already existing URL which should be shown for the Countries menu item?

**Comment by teklal** [comment]
Closing this because there has been a restructuring of Country and Regional pages since last comment on this ticket.
