### ISSUE TITLE
Issue with the drop-down menu when associating a situation report with an event

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#412]
In the current drop-down menu, the reports seem not to be in any sensitive order.

![image](https://user-images.githubusercontent.com/31092591/44350170-fc54bd00-a49e-11e8-8636-114a69a6380e.png)

Would it be possible to add a main drop down menu with countries and another one with emergencies in that country? Or even more sophisticated levels such as:

1. Country
2. Type of Event
3. Name of the event

The current one is very difficult to use and as a result, new data is not being uploaded.

**Comment by dereklieu** [comment]
Hey @ElsaRaunioIFRC the emergencies are ordered chronologically, but I understand they aren't easy to locate. Since emergencies can have multiple countries, adding that as a field to the name is not straightforward to do. It's relatively easy to add the disaster type to the name, however. I can also make this a search field, as we've done in other parts for ie searching for countries, where you type to search.

However, I would strongly recommend going through the emergency page rather than the situation report page, since you can also add situation reports through the emergency page, and it's much easier to find them.

<img width="1401" alt="screen shot 2018-08-22 at 11 30 19 pm" src="https://user-images.githubusercontent.com/1590802/44489191-77ff6700-a663-11e8-8dc4-4b094d690384.png">

Thoughts?

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu Thanks for bringing up this more convenient way of submitting the report. Those who will be uploading the situation reports will be trained to use this method.
