### ISSUE TITLE
No deployment data on Regional Pages

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#414]
## Issue

Despite having deployments in Bangladesh, for example - when we go to the regional page for Asia Pacific the data is not showing up. This is quite important one to fix. Screenshot as a reference:

<img width="1132" alt="screen shot 2018-08-21 at 09 47 07" src="https://user-images.githubusercontent.com/23258092/44382776-6618a980-a527-11e8-9341-c71d72a88323.png">

**Comment by dereklieu** [comment]
@guipizzini so this chart was built in phase 1 to show ERU deployments, and we haven't touched it since. If it's problematic I can remove it and increase the operations chart to full-screen. We can also fit in time to visualize a different type of deployment, provided we can choose one of the following:

1. ERUs
2. Personnel
3. PNS activities

**Comment by LukeCaley** [comment]
@dereklieu @guipizzini Agree that of the three options 'Personnel' is most likely to have data worth displaying in a graphic.
