### ISSUE TITLE
titles on the home page legend

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#445]
One of the scale point titles in the Legend of the map on the home screen  has changed to' IFRC Operation request'

![image](https://user-images.githubusercontent.com/7780809/45476792-33d22480-b740-11e8-8fe4-88e1647d9865.png)

**Comment by szabozoltan69** [comment]
The change was on 2nd August, according to this: https://github.com/IFRCGo/go-frontend/commit/92a97368e8092fcb2909a7503f1ba39312a3dbeb#diff-21eb0dc441de340388b8a967f6322a07

The purpose of its change is widening the meaning content, because the original "Appeal/DREF amount" does not cover every kind of IFRC operations. By my opinion this issue can be closed.

**Comment by dereklieu** [comment]
Yeah this was a language change request that came through @LukeCaley.

**Comment by szabozoltan69** [comment]
Munu and Sune suggested to change it to 'IFRC Financial Requirements'

**Comment by LukeCaley** [comment]
As communicated on Slack I agree with the change to 'IFRC Financial Requirements' as much clearer.

**Comment by szabozoltan69** [comment]
Change done, on https://dsgoproxyapp.azurewebsites.net/ already can be seen, soon on production also.
