### ISSUE TITLE
Look into why Nigeria Flood appeal docs aren't pulling in

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#463]
## Issue

The Nigeria Flood emergency isn't showing both appeal docs.

## Steps to reproduce

https://prddsgocdnapi.azureedge.net/admin/api/event/3136/change/
^ shows both appeals, meaning they are attached

https://prddsgocdnapi.azureedge.net/admin/api/appeal/3124/change/?_changelist_filters=q%3Dnigeria%2Bfloods
^ does not show an appeal doc, in theory it should be attached

## Expected behavior

The emergency at `/3136` should display both appeal documents.

**Comment by szabozoltan69** [comment]
Issue text from Munu: The problem is that the Emergency Appeal (EA) document should be automatically pulled to this page https://go.ifrc.org/emergencies/3136 under Appeal Documents. But when you go to Appeal documents you only have the link to download the DREF and the EA document is not available. Essentially we should have at least two documents under this title not one. The emergency appeal is download able from http://adore.ifrc.org/Download.aspx?FileId=212605 and available on http://www.ifrc.org/en/publications-and-reports/appeals/?ac=MDRNG025

The Emergency Appeal (MDRNG025) has a different appeal code to the DREF (MDRNG024) so the issue is on MDRNG025. The operations page does not show the EA only the DREF.

**Comment by dereklieu** [comment]
@guipizzini @mmusori @LukeCaley @omniscjencja 

It seems the appeal document google sheet has been moved or no longer exists.

[This is the URL where it expects to find appeal documents at](https://proxy.hxlstandard.org/data.json?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1gJ4N_PYBqtwVuJ10%20d8zXWxQle_i84vDx5dHNBomYWdU%2Fedit%3Fusp%3Dsharing).

[This is the URL to the source Google sheet](https://docs.google.com/spreadsheets/d/1gJ4N_PYBqtwVuJ10%20d8zXWxQle_i84vDx5dHNBomYWdU/edit?usp=sharing).

Both currently return 404's.

This would explain why new appeal docs are not being added to Go.

For posterity and to inform IT, I will reply to this effect in the email thread as well. Please follow up in this github ticket with the new URL where we can scrape appeal documents.

**Comment by LukeCaley** [comment]
https://docs.google.com/spreadsheets/d/1gJ4N_PYBqtwVuJ10d8zXWxQle_i84vDx5dHNBomYWdU/edit?usp=sharing

**Comment by dereklieu** [comment]
The spreadsheet is back but I'm not finding the second appeal `MDRNG025` in it.
