### ISSUE TITLE
Total people affected by emergencies showing 0

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#518]
On the Emergencies page, the number of affected people shows 0 even though there are emergencies with specified figures (e.g. 900,000 for Israel).

![image](https://user-images.githubusercontent.com/31092591/48786909-12fdf080-ece8-11e8-8a66-5106fe31f610.png)

**Comment by dereklieu** [comment]
@szabozoltan69 the `emergencies-dash` component is not checking the `num_affected` figure in the latest field report attached to each emergency. So the number in the header is 0, but some emergencies in the table below show number affected.

As you can see here, [the table is checking the field report for `num_affected` if the `num_affected` on the emergency object itself is null.](https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/connected/emergencies-table.js#L167)

<img width="1137" alt="screen shot 2018-11-20 at 9 36 31 am" src="https://user-images.githubusercontent.com/1590802/48791944-db6f5400-eca7-11e8-91e2-b11f5f43cd09.png">

See: [Hurricane Gaja](https://prddsgocdnapi.azureedge.net/api/v2/event/?id=3369)

@ElsaRaunioIFRC I should note, the whole point of having a # affected figure on the emergencies is so that IM can set this and override the figure coming from the field report. If this figure isn't being used we should remove it to cut down on confusion.

**Comment by szabozoltan69** [comment]
Thank you, @dereklieu . Your words showed the direction. I had to change emergencies.js, so instead of the old const numAffected = records.reduce((acc, next) => acc + get(next, 'num_affected', 0), 0);
I had to test if there is no (non-zero) num_affected field in appeal, then get the most recent field_report belonging to it.
So in row 95...:
```
      appealNumAffected += Number(get(appeal, 'num_affected', 0));
     ...
    numAffected += (appealNumAffected > 0 ? appealNumAffected : Number(get(mostRecentReport(record.field_reports), 'num_affected', 0)));
```

**Comment by szabozoltan69** [comment]
Now it seems to be fine on production:

![affected1100000](https://user-images.githubusercontent.com/6050643/48835592-d6320800-ed80-11e8-8782-6ab7a2c75dc7.png)

Otherwise on staging it's a bit weird. But staging data should not be realistic...

**Comment by szabozoltan69** [comment]
There is something I don't understand (tested in staging).
@dereklieu maybe you know the solution.

In https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/reducers/emergencies.js#L89 if I give a console.log(records), it gives a bigger array (length 21). But if I give a console.log(record.name) inside the forEach (so in https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/reducers/emergencies.js#L91 ) then it writes only 7 names. Is there some kind of filter there which I should consider? This way I don't see in this list the 'Nicolette: Severe drought affecting 20 of Afghanistan’s 34 provinces' appeal, which has a biiig number of affected people, and it can't be seen in the summing statistics.
