### ISSUE TITLE
List of countries in the field report drop-down menu

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#530]
It looks like Republic of China (Taiwan) is still in the field report drop-down menu. Would it be possible to match the drop-down menu with the list of countries in the admin end?

**Comment by szabozoltan69** [comment]
Do you mean an already inserted field report? Because for new field-reports I can not see Taiwan:

![no_taiwan](https://user-images.githubusercontent.com/6050643/49087293-e3566780-f256-11e8-9c37-b42fadbdf5e9.png)

Please send me an example URL (in email).

For already inserted field reports a (one-time) database update can help.
(In the countries admin page there are only the "nice" countries... as usable entities.)

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Maybe you used the dev environment? There we can see Taiwan also. But not in production site.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Could you please send me (in email) the URL you used at the moment of the screenshot? Because it can not be the same as mine ( .../admin/api/fieldreport/add/ ), maybe it is on the frontend.

**Comment by szabozoltan69** [comment]
I see, it is on the frontend. I have to debug it why does it show more countries – maybe due to the already existing country entities...

**Comment by szabozoltan69** [comment]
There is a country list for the frontend itself: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/field-report-constants.js#L284 :-/
I shorten it in a minute...

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC You can test it now.

**Comment by ElsaRaunioIFRC** [comment]
It works now.
