### ISSUE TITLE
Error message when uploading second deployment

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#557]
## Issue

User reported receiving an error message when uploading additional deployments through Personnel Deployments page.
Initially when they log in to admin sit and click on ADD PERSONNEL DEPLOYMENT everything works fine, but when they click on ADD PERSONNEL DEPLOYMENT again and then click SAVE, they get a following error message.  

![1](https://user-images.githubusercontent.com/29458013/51113990-3636af00-1804-11e9-92b6-fdd1611ce2a7.jpg)

**Comment by szabozoltan69** [comment]
This CSFR error refers to an attack scenario (https://en.wikipedia.org/wiki/Cross-site_request_forgery).
 - A possibility is: after the first deployment-adding an attacker got some (cookie) information and tried to use it.
 - But it is much more likely, that the user tried to "step back" with the browsers "back" button and sent the same page as before. This is prohibited to avoid the above security issue.

The suggested way is to use always ("freshly") the upper right "add..." button (instead of stepping back).

I could not reproduce this error on my system.
