### ISSUE TITLE
3w: Frontend to display projects

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#641]
Relates to #640 

Design: see https://projects.invisionapp.com/share/P9SA110GT4S#/screens/356658484 in the `Movement Activities in support of NS` section.

There will be a map highlighting all the `admin1` areas in the country, allow the user to filter projects by various criteria, and clicking on an `admin1` on the map will show some data about Projects in that District:

 - No of Programmes / Projects
 - Summary details of all projects in that District / admin1 area.

Question: Is there a particular map style we wish to use for this?

cc @mankamolnar

**Comment by ElsaRaunioIFRC** [comment]
As my last assignment with the IFRC, I have [created the style for the 3W maps](mapbox://styles/go-ifrc/cjyo249oy42oh1cphwvxyb0z5), following the example set by the YU.

As with the Map Export tool, feel free to take over the style in order to make it compatible with the overall 3W tool.

Since I don't have many hours left with the IFRC, I'm handing over the map-related tasks to @LukeCaley.

**Comment by ElsaRaunioIFRC** [comment]
Here is the style for the 3W maps on MapBox, created according to the recommendations of the YU:
https://api.mapbox.com/styles/v1/go-ifrc/cjyo249oy42oh1cphwvxyb0z5.html?fresh=true&title=true&access_token=pk.eyJ1IjoiZ28taWZyYyIsImEiOiJjamlybHUzNmMwZDUxM3Fwa215YjJ1dzk5In0.OhqEybDX303sHjHzq3nFYQ#1.9/14.694911/14.129731/0

As with the Map Export tool, I give you the free hands to modify the styles so that they are compatible with the 3W features.

Since I don't have many hours left with the IFRC, the future questions about the map styles should be directed to @LukeCaley.

**Comment by szabozoltan69** [comment]
Nice, thanks Elsa!
