### ISSUE TITLE
Data Bank: Implement frontend for Country Data Bank

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#644]
We need to implement all the frontend charts and data visualizations for the country data that will be imported via the `data-analysis` scripts. Backend ticket: https://github.com/IFRCGo/go-api/issues/434

This will be the various country indicators under Country -> Overview - https://projects.invisionapp.com/share/P9SA110GT4S#/screens/356658486

@guipizzini will help us to map the various charts and visualizations on the frontend to data points on the backend.

**Comment by guipizzini** [comment]
Feedback on the "mapping" how each data point relates to the graphics and charts was done already several times and @batpad is aware of this and has the file.

The issue is that the development of the graphics and charts does not match the user requirements outlined in the UX/UI wire frames.

@nanometrenat For your information - Action required: Ensure that the staging environment has the graphics, charts and export options available with good quality as outlined in the UX/UI work done by Yellow Umbrella.
