### ISSUE TITLE
Login button inconsistency

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#785]
When a user is not logged into GO there is a login button on the top-right corner of the front page (as there should be).
However, when this same page is viewed with a narrow window width, the respective 'button' on the dropdown menu says 'Logout' although it should say 'Login'

Below screenshots of the same window in these two different window width scenarios.

![gologin](https://user-images.githubusercontent.com/52411237/63928286-9b67a980-ca4f-11e9-8ad0-efaa1e5eae8d.PNG)

![gologout](https://user-images.githubusercontent.com/52411237/63928287-9b67a980-ca4f-11e9-8494-42d5f677b974.PNG)

**Comment by batpad** [comment]
@teklal thank you for the catch.

This is a pretty serious issue.

The problem here is that we have two different header components based on whether the user is on mobile or desktop.

For mobiles, this header component is used: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/mobile-header.js

One can see the account links are hard-coded, as the current user login data is not being passed down to the mobile header: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/mobile-header.js#L118

So we need to ensure the users current login details are correctly passed down to the mobile header, and then write the conditional code to handle displaying Login / Logout, etc. based on the user's login state.

@necoline let's talk about this, and see if it might be something you're able to dig into.

**Comment by necoline** [comment]
Sounds like a plan.

**Comment by guipizzini** [comment]
@batpad and @necoline if you can share any update or feedback on your discussion that would be very useful. thanks friends

**Comment by batpad** [comment]
This was fixed in #805 and is ready for testing @teklal @guipizzini .

Thanks @necoline for the fix!
