### ISSUE TITLE
Add RC to Homepage link on country page

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#795]

**Comment by guipizzini** [comment]
@LukeCaley our team suggestion is to only have the links to ifrc.org and reliefweb page of the country but not to the link of the NS website.

These are often not updated or existing and it would be a huge task to ensure quality and regular updates of those links.

Here is an example:

https://uniregistry.com/market/domain/caribbeanredcross.org?landerid=www5d6fa2c42768f1.02713158

Otherwise, functionality works fine at present - good to go from a UAT point of view. Reopening for your validation @LukeCaley of what proposed.

**Comment by LukeCaley** [comment]
After discussion with Sune, we propose to keep links, even if these are not always pointing to a functioning URL.  From a principle point of view we should provide the user the option to find the National Society website if it exists.  Agreed that this will take some maintenance but this is something that we should take as a task for the IM team to clean up the list in the first instance and the focal point for maintaining GO at NS level should also have the rights to amend.

**Comment by batpad** [comment]
:+1: Marking this as closed.
