### ISSUE TITLE
PER language forms to be hidden

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#808]
## Issue

PER forms were translated by the PER Team. However, due to last minute fixes on the forms and due to the fact the rendering of the front end of GO is in English only - we had agreed to keep the functionality so we can easily make the translated forms available - but to **hide** the forms from the user's front end for now.

## Steps to reproduce

Check the screenshot - the highlighted dropdown menu - needs to be hidden.

## Expected behavior

Forms available only in english for PER.
<img width="1264" alt="Screenshot 2019-09-08 at 12 14 10" src="https://user-images.githubusercontent.com/23258092/64486859-fc9f3200-d232-11e9-9391-ed3fc2ab39c0.png">

**Comment by batpad** [comment]
I'm having a hard time getting to these forms to be able to test them (I think my test user may not be setup with the correct permissions.)

I'm going to push some untested code that I *think* should work and merge to develop, but @guipizzini @teklal will be great if you guys are able to test - and ideally tell me how exactly I'd test this. Thanks.

**Comment by teklal** [comment]
@batpad What test user are you using? Your user 'sanjay' should have the required permissions to get the same view as on the screenshot above.

**Comment by batpad** [comment]
@guipizzini @teklal - have hidden the language form entirely now (deployed to staging).

One suggestion is to, instead of hiding the form entirely, just make it Disabled - i.e. the form would show up with English selected, and the user would not be able to change it. This way, we don't change the UI much, and there's also an indication that this feature will be available in the future. Let me know if that sounds like a good idea and we could then make the drop-down disabled instead of hiding.
