### ISSUE TITLE
Better error handling support for network requests

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#861]
The currently available network request utils, eg: `fetchJSON`, `postJSON` does not support the status for the network failure.

**Comment by necoline** [comment]
## Rationale
Better error handling would provide more descriptive messages regarding why something went amiss. This is helpful for developers to more quickly resolve problems, but it also provides a better user experience because it can provide immediate feedback for why something is not working as expected which can alleviate frustrations on the part of the users by keeping them informed as to what caused the error.

**Comment by nanometrenat** [comment]
@frozenhelium @batpad @tovari is this still required or was it covered off as part of the rewrite?
Not sure if related to https://github.com/IFRCGo/go-web-app/issues/515#issuecomment-1947129466

**Comment by frozenhelium** [comment]
@nanometrenat this is resolved now

**Comment by nanometrenat** [comment]
Brill, closing!  Thanks
