### ISSUE TITLE
Handle different view on staging

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#888]
Right now, the site shows a discoloration on the staging site, and it makes the whole site look very different, making it harder to test some pieces.

Ideally, we should remove this huge discoloration, and just make an obvious change to the logo, or a space near the logo to clearly say `Staging` or `Testing` or `Alpha` or so.

TODO:

 - [x] Figure out how exactly the current setup is working / where the conditionals to swap styles out on staging are.
 - [ ] Remove the current conditional.
 - [ ] Agree on a much simpler indication of "Staging"
 - [ ] Implement the simpler indicator of "Staging"

cc @frozenhelium @necoline @LukeCaley

**Comment by nanometrenat** [comment]
Not sure but this might perhaps be where the config points are for grey background, if that helps with step 1?:

https://github.com/IFRCGo/go-api/issues/518

https://github.com/IFRCGo/go-api/pull/538/commits/cf9dd9cb6a7528bca4d773d587a1e95ef4eb4756 https://github.com/IFRCGo/go-api/commit/cf05d70e0ff3146339046bbcd65f935d561113c6

**Comment by batpad** [comment]
Thanks for digging that up @nanometrenat !

It maybe nice to streamline how we do this a bit, @thenav56 - is there a better pattern you'd suggest for doing this?

Next steps:

 - [ ] Design an element that we can toggle on / off with `display: none` or so to only show on the staging site. @nanometrenat are you able to help with a quick visual mockup (it can be very rough) of the desired behaviour here? i.e. how we want to indicate staging in the logo or so? (We can then adapt it to fit implementation)
 - [ ] Replace the logic in the build steps identified above to toggle the new element on / off instead of changing the background colour.
 - [ ] Look into improving how we do this conditional behaviour, it seems like the current way could be simplified and made a bit more obvious in configuration.

**Comment by thenav56** [comment]
@batpad 

> Ideally, we should remove this huge discoloration, and just make an obvious change to the logo, or a space near the logo to clearly say Staging or Testing or Alpha or so.

I would also recommend this. Another will be using a bar fixed in top indicating server type.

We are using something like this in DEEP.

![image](https://user-images.githubusercontent.com/7059255/72072273-b1e31300-3315-11ea-911e-2c41353bd47b.png)
![image](https://user-images.githubusercontent.com/7059255/72072280-b3acd680-3315-11ea-820d-4b7aefab443c.png)

**Comment by nanometrenat** [comment]
Thanks @thenav56 and @batpad 

Our critical requirements are:
* User must be able to see at all times that that they are in staging site (i.e. should be visible even when they scroll up/down or left/right) – e.g. like the Cookie warnings you often see, that stay in place when scrolling
* As you have identified, there may be several different non-Prod environments (staging vs test etc.) so the banner would need to adapt to specific envt.

Suggest a banner similar to the one you have shown for The Deep above BUT at the *bottom* of the screen rather than the top, so when doing screenshots for documentation etc it's easy to trim the screenshot if needed.

Cheers!

**Comment by teklal** [comment]
Will this banner show up on the separate testing URLs as well?

**Comment by GregoryHorvath** [comment]
> Will this banner show up on the separate testing URLs as well?

At the moment it won't, but we can adjust so it does though I don't know if any confusion would arise from it saying 'staging' on those temporary sites. Should alter the text too for them?

**Comment by teklal** [comment]
I think it would be good to have for consistency and clarity a banner on anything that is not the production site.

Re https://github.com/IFRCGo/go-frontend/issues/888#issuecomment-573457851

> As you have identified, there may be several different non-Prod environments (staging vs test etc.) so the banner would need to adapt to specific envt.

So I'd suggest on the testing environments/urls have the banner say "Testing" or something like that.

**Comment by teklal** [comment]
Also for consistency can we make the text on the backend be the same size as the frontend?
![image](https://user-images.githubusercontent.com/52411237/78647987-9e672a00-78bb-11ea-956f-7dac85d7d3e5.png)

**Comment by LukeCaley** [comment]
@GregoryHorvath to investigate how much extra work to identify the branch.  If significant, just to notfiy on staging is fine for now.

**Comment by GregoryHorvath** [comment]
If the production (frontend) server has a `NODE_ENV` variable set to "production" or something, then this can be done in ~15 minutes including self-testing. I just need to know how to check those ENV variables or need someone to check.

**Comment by teklal** [comment]
Checked on one separate testing URL and the banner shows up saying "Staging site". Based on @GregoryHorvath's above comment, this will be the case for all surge URLs from now on, so in that case this ticket is now tested and it works.
