### ISSUE TITLE
[PROD] Funding information incorrect on country page card

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#915]
The funding coverage card on the country pages is not showing the DREF fund coverage info.

![image](https://user-images.githubusercontent.com/52411237/70695711-965afd00-1cc2-11ea-85f3-a69657cefd87.png)

On the emergency page the cards do show the information correctly.

![image](https://user-images.githubusercontent.com/52411237/70696198-7ed04400-1cc3-11ea-8ccf-8e5a6c5bed9b.png)

Based on another country page's information it seems the problem indeed is in just the DREF funding coverage. As below, the funding requirements are a sum of both the DREF and the Emergency Appeal but the coverage takes into account only the EA.

![image](https://user-images.githubusercontent.com/52411237/70696974-023e6500-1cc5-11ea-9a41-0e8bd3282a9b.png)

Could we fix this so that it shows also the DREF funds info on the coverage card?

I noticed this on a country page, but I guess we may have the same problem/effect on the regional pages and potentially the home page cards as well?

**Comment by nanometrenat** [comment]
Potentially related to changes made under https://github.com/IFRCGo/go-api/issues/536 ?

**Comment by GregoryHorvath** [comment]
@nanometrenat So it won't add together the Funding for the highlights for DREF Appeals: https://github.com/IFRCGo/go-frontend/blob/866c5f490513465396daa79628af779a111fbe3a/app/assets/scripts/reducers/overall-stats.js#L52

@necoline (FYI) related commit: https://github.com/IFRCGo/go-frontend/commit/24ff1bc109fd8a0f6ae54a9675bf98f24560cd6f

**Comment by necoline** [comment]
I went through past commits to see if somehow this data point was lost in past work on this feature.
It turns out that there was only ever one [endpoint](https://github.com/IFRCGo/go-frontend/blob/6217edd140a5c32cb06d905a0804f8e35097ed60/app/assets/scripts/actions/index.js#L151) provided for this feature ( #847) 

Since this data for this point on DREF Appeals is missing, we should look to the backend to see where this data is being supplied and find out why it is not available on the same endpoint with the rest of the data.

@GregoryHorvath 
   Do you have insight into why DREF Appeals are not coming through this endpoint? 
   Is there a reference point where the funding coverage for DREF Appeals is coming through where I could alternatively pull this data from?

**Comment by GregoryHorvath** [comment]
@necoline This should be query firing (except the `time` part of it):
`/api/v2/appeal/?end_date__gt=2020-03-23T00%3A00%3A00.000Z&country=109` which gives me back both `amount_requested` and `amount_funded` when I tested locally. Though I see 0% Funding Coverage too, but I haven't checked the frontend side of this.

Natalie above referred to another ticket which could be related in some ways, but I made those changes on the frontend: https://github.com/IFRCGo/go-frontend/commit/4bf1f4673559f75e3623d9629fb8cf51c8ba845f

**Comment by necoline** [comment]
@GregoryHorvath  thank you for highlighting this piece of code, I seemed to have missed this in my past review of the issue. My PR above contains details on the fix

**Comment by nanometrenat** [comment]
Hi @necoline just to confirm - the business logic is not that Appeals and DREFS should be treated separately - in actual fact if there is an Appeal it can often require the DREF to be repaid.

See Tekla's comments in ticket go-api#536 that I referenced above, also quoted here:

> Currently for operations where initially a DREF was requested but later an Emergency appeal (EA) is launched, the funding information on the emergency page sums the "Amount requested" and "Amount funded" for these two appeals, as well as the people targeted ("Num beneficiaries" on the backend).

The way it works though is that after an EA is launched, the DREF money that was allocated to that operation, becomes a loan for that EA and is merged into that funding. So for these operations the information we need to display on the GO emergency page is the funding information of just the Emergency appeal. So the information in the Emergency Appeal is "more up-to-date" and is the one we should be pulling from.

It is absolutely critical that this calculation is correct, and the change will need to be fully tested with a number of scenarios, so please check with @teklal and @mmusori  if any additional info is required re the business logic here.

Thanks cc @LukeCaley

**Comment by necoline** [comment]
I am a bit turned around on what the original problem was and what the desired solution is. 

2 years ago, a set of business logic was written to aggregate the and display sumsat that adds together the `amount funded` only for  appeals and does not account for the `amount funded` values available for DREFs. 

The change in the PR removes the conditional the limits the calculation of `amount funded` to appeals so that the the country key header includes all `amount funded` values in its calculation of funding coverage. 

My understanding is that this would address this issue as originally defined. However it appears that in addition to this change, there is additional logic that needs to be applied. 

>  if there is an appeal as well (as a DREF) then the calculations are different (depending on whether the funding amount is sufficient to repay the DREF)

**How is an emergency appeal marked in the appeals list? Is there a specific `atype` assigned to it?**

**How should DREF funding be calculated into the `funding coverage` in the various cases stated above?**

**If we have two appeals and one is an emergency appeal and one is not, should the emergency appeal replace the standard appeal on the backend? **

**Comment by batpad** [comment]
If the figures are still wrong, we should definitely get to the bottom of this. Currently awaiting clarity in terms of what these numbers need to be and how these calculations should be derived, exactly. Would be great to spend some time speccing out exactly how the Key Figures numbers need to be derived, and then ensuring that we are doing the right thing. Moving to 4.4.

**Comment by nanometrenat** [comment]
@mmusori @anamariaescobar is this working as desired now?  Or still more work required?
