### ISSUE TITLE
Emergencies page: Inconsistencies/confusing information regarding number of emergencies

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#916]
On the [Emergencies tab](https://go.ifrc.org/emergencies) on GO the figures for the number of emergencies in the last 30 days is inconsistent.
On the top of the page it currently shows that there would have been 129 emergencies in the last 30 days:

![image](https://user-images.githubusercontent.com/52411237/70700992-eab6aa80-1ccb-11ea-8dd6-0186b1686ebd.png)

But a bit further down on the page (below the map) it states that ther would have been 31 emergencies:

![image](https://user-images.githubusercontent.com/52411237/70701726-256d1280-1ccd-11ea-8006-2ff17b8d0e6a.png)

On the map on the [Emergencies tab](https://go.ifrc.org/emergencies) e.g. Chile appears to have 13 emergencies:
![image](https://user-images.githubusercontent.com/52411237/70701390-9102b000-1ccc-11ea-92c2-ffc43b445355.png)
But on Chile's country page it shows only 2:
![image](https://user-images.githubusercontent.com/52411237/70701468-b394c900-1ccc-11ea-85a0-2e816f406b50.png)

It could be that the map and top panel (cards/key figures and graphs) show the emergencies from a longer period of time than 30 days?

Could we also change the default scaling of the points on the map to be according to 'Number of emergencies' instead of 'Number of people affected' as many emergencies do not have the information about affected people?

![image](https://user-images.githubusercontent.com/52411237/70701041-face8a00-1ccb-11ea-8269-4b4954d0b62a.png)

**Comment by nanometrenat** [comment]
Potentially related to https://github.com/IFRCGo/go-frontend/issues/311 ?

**Comment by GregoryHorvath** [comment]
@LukeCaley So the top part on Emergencies main page was changed to use 90 days instead of 30 days via: https://github.com/IFRCGo/go-frontend/commit/be39039f864b724f773bcfae78cb87790a9592dd

I couldn't reproduce the other issue with the discrepancy between the listed Emergencies on the map and on the Country's page, but I saw it happening on production with Philippines for example. In the code the same filters are applied as far as I checked to both the map and the list, @batpad please could you check on this and see if you can find something? 

Related files:
* [/app/assets/scripts/components/connected/emergencies-table.js](https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/connected/emergencies-table.js)
* [/app/assets/scripts/views/countries.js](https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/views/countries.js)

Branch for these fixes: https://github.com/IFRCGo/go-frontend/tree/fix/emergencies-last-30

**Comment by GregoryHorvath** [comment]
Reopening because the second part is still present.

**Comment by teklal** [comment]
Closing this as the second part has been moved under #1079
