### ISSUE TITLE
PER: list of NSs incomplete and contains non-existing NSs

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#918]
For a PER super user (having access/rights to submit PER forms for any NS) the drop down list of National Societies isn't complete and stops at Red Cross Society of China (alphabetical list). There are also National Societies that do not exist, such as Antarctica NS, and it should not show Country Clusters.

![image](https://user-images.githubusercontent.com/52411237/70812570-2b93e980-1dc8-11ea-95b0-70aa13182517.png)

I tested and for users that have the PER rights only for a certain NS that doesn't appear on the superuser's dropdown, it does still work normally and that NS appears for that user (tested with Lesotho).

Could this list be updated to be the correct one and also have the non-existing NSs removed?

**Comment by necoline** [comment]
Thanks for this catch @teklal I'll look into this to see why this is the case.

**Comment by necoline** [comment]
The request for PER countries was capped at 50. I raised the limit to 1000 in #893
![image](https://user-images.githubusercontent.com/20410256/72102980-3887f800-32f6-11ea-9db6-03917ff31ea4.png)

**Comment by teklal** [comment]
Hi @necoline , your screenshot looks great.

I'm still experiencing the issue of the list ending around letter "C" (probably the 50 NSs) in the testing environment 
![image](https://user-images.githubusercontent.com/52411237/72452175-66b97c00-37bd-11ea-9f2d-c5b4eae5ddfd.png)

as well as production
![image](https://user-images.githubusercontent.com/52411237/72452235-80f35a00-37bd-11ea-80fd-143f28aba6bc.png)

What is the timeline of having this working in the live environment?

**Comment by necoline** [comment]
This is fixed in the PER update that is currently pending a code review

**Comment by necoline** [comment]
I'm not sure if everything specified in this ticket is resolved. My fix removed the constraint on the number of options in the list, but I am unclear about the second request. @teklal you mentioned that non-existent national societies are appearing on the list. The data coming through to the frontend seems pretty uniform. I don't see any obvious way to identify the NS's that need to be filtered out. 

Perhaps this is something to be investigated on the backend? @batpad do you have any thoughts on this?

**Comment by nanometrenat** [comment]
Re non-existent NSs conversation:
I've had a look at this and it seems that the way this dropdown works is:
* get all items from the Country table
* if the "Society Name" field is blank, just put country name + NS in the dropdown
* if the "Society Name" field is populated, show that name in the dropdown.

SO Tekla's problem with additional countries appearing is a data issue in staging (rather than a code issue) because in Prod countries such as Antarctica are not present in countries table.

HOWEVER @necoline there is potentially still an action here to fix the dropdown - currently ALL items in the country table are showing (even if they are type=cluster or type=Country Office).  Will check with @teklal tomorrow as to whether there's any possibility that a non-NS might have to fill in a PER form, and revert as to whether these therefore do or don't need to be filtered out when the dropdown is populated.

**Comment by teklal** [comment]
Thanks @nanometrenat for expressing the findings/problem so neatly!

So indeed, the list should only have National Societies so the Cluster and Country Offices should be filtered out. I'll just reopen this ticket until that is done as well. 

Thanks for the work on this @necoline , this is great and super important for the PER team in order to be able to submit data.

**Comment by batpad** [comment]
@necoline how is this to do on the frontend? Let me know if it would help to have this as a filter from the backend when fetching the list of countries.

**Comment by necoline** [comment]
I added a filter on the frontend in the PR above. 
It might be worth noting that every option in the test data has a `result_type` of country (aside from `Nat Test National Society` which @nanometrenat helpfully added) which makes testing for an effective filter on the frontend a little less apparent.

**Comment by batpad** [comment]
@nanometrenat @teklal this is now merged and ready to test on staging

**Comment by teklal** [comment]
Tested and it works. Thanks @batpad and @necoline !

**Comment by batpad** [comment]
Marking this closed. Feel to re-open if something does not work as expected @teklal
