### ISSUE TITLE
3W: User feedbacks

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#925]
- [x] Budget currency
- [x] Required field indicators
- [x] Change donut chart to barchart
- [x] User permission for project add and edit
- [x] Filter `Current operation` list by the current country
- [x] Include project name in the listing
- [x] Empty string is not accepted by api (must be `null` to denote empty value)
- [x] Last update field in the project listing
- [x] Popup to show all the project details
- [x] Change `Type of operation and programme` to say `Type of operation / programme`
- [x] Option to add country wide project

**Comment by frozenhelium** [comment]
- [x] Budget currency
- [x] Required field indicators
- [x] Change donut chart to barchart
- [x] User permission for project add and edit
- [x] Filter `Current operation` list by the current country
- [x] Include project name in the listing

**Comment by frozenhelium** [comment]
Hi @batpad I didn't get what "Disclaimer on the status of the map boundaries" means. Can you give me an example or screenshot in any other place where it is implemented?

**Comment by batpad** [comment]
@frozenhelium if you go to an emergency with a map, like https://go.ifrc.org/emergencies/3931#details and then hit the Export Map button, it is the text that comes below the map on the exported image - let me know if this makes sense.

**Comment by frozenhelium** [comment]
Oh, I see, thanks!

**Comment by lauripynnonen** [comment]
Hi all, I went through the comments and tried to find what has been done, what's still missing and what is completely out of scope here https://docs.google.com/spreadsheets/d/1Il9SoHoAh6s0Kod2xwKzxNqpvv6ttffpx29xSAASR1g/edit#gid=133357161 (refactored sheet1)
- [ ] Budget currency to the form (lines 6,10,11,12,19)
- [ ] Disclaimer on the status of the map boundaries (39, 40)
- [ ] Children field changed to other (lines 20, 21, 22, 24,29, 31)
- [ ] Total people targeted counted automatically (with previous)
- [ ] Thousand-separator shows and undefined in submitted forms table (34)
- [ ] Decimal point in currency causes submit to fail without any error message (37)
- [ ] Selected country highlighted (53)
- [ ] Edit rights of own submits / to submissions from own national society (59)
- [ ] Decimals in number of people allowed (63)
- [ ] Copy button (72)
- [ ] Import spredsheet (template) (75)
- [ ] Visual consistency with bars project status/map (79)
- [ ] Last updated date (82)
- [ ] View details instead of just edit (84)
- [ ] Two different colors in the total budget under the map (86)
- [ ] Removal of finished activities (87)
- [ ] Visual indication of required field before submission (89)
- [ ] Rephrasing "Movement activities in support of NS" (90)
- [ ] Alphabetical drowdowns (92)
- [ ] History of edits (96)
- [ ] Current IFRC operation filtered to current country (97)
- [ ] "Type of operation/programme" (98)
- [ ] "Operation type" and "Programme type" texts above boxes in the "Type of operation and programme" section are confusing (99)
- [ ] Country and region / province - should not be mandatory to select a province - therefore need to add another item into drop down"Country-wide" (100)
- [ ] DRR Mapping compatibility edits (101)
   - [ ] Include “Multi-hazard” in the dropdown list
   - [ ] Include algorithms to calculate the breakdowns of expenditures or no. of people reached per sectors, based on the percentage of sectoral activities
   - [ ] define a mapping period, so that we can map the relevant data in a specific mapping year
   - [ ] Include a field for expenditure and algorithms to calculate the breakdowns of expenditures, based on the percentage of sectoral activities
   - [ ] Include algorithms to calculate the breakdowns of people reached, based on the percentage of sectoral activities; 
   - [ ] Include a field with donor information
   - [ ] Include a dropdown list with climate integration info – climate-not-considered; climate-aware; climate-smart; and not applicable
   - [ ] Include algorithms to aggregate the figures of expenditures and people reached at global, regional and national levels
   - [ ] allow IFRC to verify the inputs from PNSs or HNSs.
- [ ] sub-total by sector (at least for people reached) to facilitate congruence (and single source) with FDRS data NS will submit? (106)
- [ ] disability disaggregation function for people targeted and people reached (107)
- [ ] explanatory field to clarify the budget: field budget or total budget including supporting HR (108)
- [ ] explanatory field to clarify the people: direct beneficiaries or including indirect  (109)

**Comment by lauripynnonen** [comment]
@frozenhelium @batpad Could you make sure you commit the 3W changes to the staging environment so that we can look at what still needs to be changed within this version? Cheers!

**Comment by batpad** [comment]
@frozenhelium I'm going ahead and approving https://github.com/IFRCGo/go-frontend/pull/937 - if things feel ready for testing, we can merge this into `develop` and tackle the rest of the changes in a separate PR?

**Comment by frozenhelium** [comment]
:+1 @batpad Sure, I'll merge it to the develop

**Comment by lauripynnonen** [comment]
Still open (new issues/tickets from these?)
- [ ] Disclaimer on the status of the map boundaries (39, 40)
- [ ] Total people targeted counted automatically (with previous)
- [ ] Selected country highlighted (53)
- [ ] Decimals in number of people allowed (63)
- [ ] Copy button (72)
- [ ] Import spreadsheet (template) (75)
- [ ] Two different colours in the total budget under the map (86)
- [ ] Rephrasing "Movement activities in support of NS" (90)
- [ ] Alphabetical drowdowns (92)
- [ ] History of edits (96)
- [ ] Current IFRC operation filtered to current country (97)
- [ ] "Type of operation/programme" (98)
- [ ] Country and region / province - should not be mandatory to select a province - therefore need to add another item into drop down"Country-wide" (100) -- _How is this shown on the country page? and on the map?_

Need more details from IM (aka currently out of scope): 
- [ ] DRR Mapping compatibility edits (101)
   - [ ] Include “Multi-hazard” in the dropdown list
   - [ ] Include algorithms to calculate the breakdowns of expenditures or no. of people reached per sectors, based on the percentage of sectoral activities
   - [ ] define a mapping period, so that we can map the relevant data in a specific mapping year
   - [ ] Include a field for expenditure and algorithms to calculate the breakdowns of expenditures, based on the percentage of sectoral activities
   - [ ] Include algorithms to calculate the breakdowns of people reached, based on the percentage of sectoral activities; 
   - [ ] Include a field with donor information
   - [ ] Include a dropdown list with climate integration info – climate-not-considered; climate-aware; climate-smart; and not applicable
   - [ ] Include algorithms to aggregate the figures of expenditures and people reached at global, regional and national levels
   - [ ] allow IFRC to verify the inputs from PNSs or HNSs.
- [ ] sub-total by sector (at least for people reached) to facilitate congruence (and single source) with FDRS data NS will submit? (106)
- [ ] disability disaggregation function for people targeted and people reached (107)
- [ ] explanatory field to clarify the budget: field budget or total budget including supporting HR (108)
- [ ] explanatory field to clarify the people: direct beneficiaries or including indirect  (109)

**Comment by frozenhelium** [comment]
Hi @lauripynnonen can you create individual issue for the "still open" section above, need to discuss on those individually.
