### ISSUE TITLE
Back end deployment process improvement

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#933]
At the moment the deployment process for the Front End is fairly streamlined, however the deployment process for the back end requires significant manual work.

@szabozoltan69 can you please flesh out this ticket re the work that would be required to improve this process and enable others to run a deployment also.  Thanks!

**Comment by batpad** [comment]
@szabozoltan69 it would be great if you and @thenav56 could team up here to:

 - Document the current deployment process clearly (i think you mostly have this documentation @szabozoltan69 )
 - On-board @thenav56 to be able to run out deployments
 - Discuss with @thenav56 to suggest ideas for improving the deploy process / making it easier and more streamlined
 - Scope out and implement changes to deployment process.

@szabozoltan69 feel free to move this ticket to a more appropriate repository.

**Comment by szabozoltan69** [comment]
**The process of the go-api backend deployment in a nutshell**
We use an .env file for the environment variables (not public). In the first rows there is the aimed environment: export ENVIRONMENT=...
and also a row about the git tag (and docker image) number: export API_DOCKER_IMAGE=
These should be set correctly.
The CircleCI process is planned to push the created go-api backend docker image to github ONLY when a new git tag arrives to the repository.

# So the suggested steps are these:
cd to_the_git_root_directory
git status  # to be sure about git status, normally there are some changes waiting for commitgit commit -am 'Some verbose text about the last change'

# Then we do the git tag increasing in the .env file. You can do it mannually, or by using:
https://github.com/IFRCGo/go-infrastructure/blob/develop/bin/increaseenvversion.php
head -4 .env # Let's check the first 4 rows of the .env file (about environment and git tag nr)
git tag 1.1.X  # where X is the new git tag
# This new tag should be written into the [CHANGELOG.md](https://github.com/IFRCGo/go-api/blob/master/CHANGELOG.md) 2 places and main/[__init__.py](https://github.com/IFRCGo/go-api/blob/master/main/__init__.py) manually, or via
https://github.com/IFRCGo/go-infrastructure/blob/develop/bin/UpdateChangelog.php -t "verbose text"
grep X CHANGELOG.md main/__init__.py -4 # to be safe and check the changes
git commit -am 'Increase version to X'
git push origin --tags  # Important that the last commit should contain the tag number change.

# After this on github page we can check when the compilation and test (of the non-master branch) is done:
check https://github.com/IFRCGo/go-api/branches - shows also circleCI color

If it was successful, let's push the 'Open Pull Request' button at the branch name, then **after merging** let's wait again in the branches web page if the master branch compiles/tests fine:
check https://github.com/IFRCGo/go-api/branches
If ready, let's check docker hub page for the new docker image:
check https://hub.docker.com/r/ifrcgo/go-api/tags/

There should be seen the last github tag version flagged docker image – we shall use this for deployment to both staging and production (and other, if will be). Exactly the SAME image. :-)

Then comes the real deployment process. Instead of "source" we can use a single dot (.) also.
source .env # we read environment file
source login.sh  # https://github.com/IFRCGo/go-infrastructure/blob/develop/bin/login.sh

Password is needed for the key.
If there are multiple deployments on the horizon, it can be useful to load the key to the ssh-agent via ssh-add .tmp/key # then we don't need to write in the password multiple times.

source connect-api.sh  # https://github.com/IFRCGo/go-infrastructure/blob/develop/vms/connect-api.sh

After logging in, we can check "docker ps" the running docker, or give a ./d  to connect to docker entity, or give an apt upgrade for the new deb packages of the host system. But all of these are optional. The non-optional is the deployment step itself:
source init-api.sh # https://github.com/IFRCGo/go-infrastructure/blob/develop/vms/init-api.sh

This pulls in the required (and whose name was waterfalled from .env file) docker image from docker hub, and deploys it to it's first place, the staging area. Also the database migrations are done at this time (automatically).

(Then, optionally, is is good to log in again into the host machine and remove the **oldest** docker image, so that the size of this site should not grow into the heaven. Do it via ./r command.)

Then – if allowed – let's put the docker image to production site also.
Change the .env file ENVIRONMENT var to production manually, or via:
https://github.com/IFRCGo/go-infrastructure/blob/develop/bin/changetoproduction.php

Then again the same steps:
. .env
. login.sh
. init-api.sh
. connect-api.sh # (then ./r to remove the superfluous docker image)

After these it is worthy to check go.ifrc.org and put the .env file BACK TO STAGING manually, or via
https://github.com/IFRCGo/go-infrastructure/blob/develop/bin/backtostaging.php

(For safe we can git checkout master again and delete the used branch via git branch -d feature_branch.)

These steps should not keep in head, but better is to keep in a table.

**Comment by szabozoltan69** [comment]
Thanks @thenav56 for trying this out and for giving news about the success.

**Comment by nanometrenat** [comment]
Hi @GregoryHorvath @batpad can this ticket be closed now given recent work?  Or are there still outstanding actions here?

**Comment by GregoryHorvath** [comment]
@nanometrenat Actually we haven't been able to make any real progress with the improvement of the backend deployment process, although I'd say we could just save Zoltán's big description somewhere (maybe Teams wiki would be the best place?) and close this for now. But let's wait for @batpad to approve.

**Comment by szabozoltan69** [comment]
The back end deployment process improvement begun by Atos, and is not followed here.
