### ISSUE TITLE
GO Site Translations - options, scope and advise recommendations

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#934]
## Feature
Automatic translation of content on GO from English into Spanish, French and Arabic.    This includes static content such as navigational features but also dynamic such as key figure references, crisis summaries etc.  (read-only/write-also)

## Scope of this ticket
In the past there have been a number of conversations re potential approaches to translations - see below tickets for details of what has been discussed.

This ticket is to take a step back and prepare options around translation frameworks with estimates and costs.

Note: The issue of dynamically translating snippets outside of the GO application is one which is not expected to be solved in this development round.

## Previous tickets re translation
https://github.com/IFRCGo/go-api/issues/454 - lists some potential translation systems
#653 relates to was to handle other language formats (left to right)
#649 talks about frameworks

**Comment by batpad** [comment]
Thanks @nanometrenat for this ticket.

@necoline you mentioned you had been doing some research into translation frameworks / services as part of the PER work. Could you outline anything that maybe relevant to this discussion?

@frozenhelium @thenav56 - are there any paths forward that you would suggest here? Do you think it makes sense to go ahead and try out existing services like DeepL and / or AWS Translate?

**Comment by frozenhelium** [comment]
So, there are two type of common implementation for translation approach in the frontend. 
1. Generating different builds for different languages and serving over different URL
2. Switching language dynamically within the app

#### Approach 1
This implement will require to have different URL for different languages. For example for english it could be https://en.go.ifrc.org. The user won't have to add language prefix to the site, it will be automatically redirected to it according to the user's region and preferences. This approach is more common for the websites because we can easily share the URL for different languages.

#### Approach 2
The language switching will be done within the app itself, and the preferences will be handled by the application internally. This approach is more common in the apps where the URL sharing is not that common.

The tools we use to move forward highly depends on which approach we take. @LukeCaley @nanometrenat please let us know the prefered approach.

https://github.com/IFRCGo/go-api/issues/454 pretty much sums the required steps. Thanks a lot @batpad for the detailed research and summarizing it amazingly.

**Comment by LukeCaley** [comment]
Closing this ticket as we have broken this down into component parts - still useful for Xref but not actively being used.

**Comment by nanometrenat** [comment]
For the records:  Microsoft Azure translation https://learn.microsoft.com/en-us/azure/ai-services/translator/ is the tool that has been implemented on GO.  (IFRC ITD can help with set up if needed for other sites)
