### ISSUE TITLE
[Staging] Country Preparedness page does not render

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#950]
## Issue
Similar to #943 and #946 - grey screen - on Barbados country preparedness page (not a problem for all countries though - not sure if Barbados is due to dodgy data??)

## Steps to reproduce
1. Go to Barbados country page https://dsgoproxyapp.azurewebsites.net/countries/28
2. Click on Preparedness tab
3. Preparedness screen does not render (https://dsgoproxyapp.azurewebsites.net/countries/28#preparedness)

Several errors given - not sure what is causing this issue - e.g. Uncaught TypeError: Cannot read property 'name' of undefined

Some other countries' preparedness pages render fine - e.g. Afghanistan is fine:  https://dsgoproxyapp.azurewebsites.net/countries/14#preparedness

## Related feature
PER #865

## Criticality/Urgency
Important to ensure that all PER pages render correctly

(logging on behalf of @teklal )

**Comment by batpad** [comment]
@necoline I did a little digging around, but not sure the best way to fix this.

Seems to be getting tripped up here: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/country/preparedness-summary.js#L42

Because `getPerComponent` doesn't return anything for the values passed in for this form / country - somehow - the form code thing that seems to be causing it to fail is ` a3-2 c14q4` - and indeed, `c14` doesn't seem to exist inside a3-2: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/get-per-components.js#L121

It's a bit hard to confirm / deny whether the same issue exists on production since the state of the data is not the same - so I'm not sure whether this bug was caused by the refactor or has always existed. @necoline hoping you have an idea on the best approach to fix this.

**Comment by teklal** [comment]
So I've found another small "bug" that needs to be fixed and that may be causing this problem.

Currently in staging the forms "Area 3: Operational capacity" (components 15 to 23) and "Area 3: Operational capacity 2" (component 14) are component-numerical-order-wise the wrong way round. 

Confusingly their urls are the "wrong way round" in the live environment (screenshots below)

Form: "Area 3: Operational capacity"
![image](https://user-images.githubusercontent.com/52411237/73366671-9fbe1a00-42ae-11ea-800b-dedef86473c4.png)

Form: "Area 3: Operational capacity 2"
![image](https://user-images.githubusercontent.com/52411237/73366636-903ed100-42ae-11ea-81a7-316a56fe0e6f.png)

 In the staging environment the forms are in the right order according to url (but not component wise).

I don't know if I was able to explain the problem clearly, let me know if you have questions. Basically the Area 3 forms should be the other way around in staging and in their current order they are in a different order from the live environment (right order but urls inconsistent with form numbering).

**Comment by necoline** [comment]
The refactor wouldn't have affected any of this behavior. The cause behind this bug is two fold:
- There is hardcoding of values rather than the pulling from the backend. The refactor that I did eliminated some but not all of this in the PER component. If there are any changes on the backend, this middle layer of coded values also need to be manually updated on the frontend. The way the code is constructed makes this process difficult to detect and thus subject to quickly becoming outdated.
- When these hard coded values are called, there is no fallback in the case that there is no matching result.

A few options for a solution:
- add a fallback so the ui doesn't break when faulty parameters are used to retrieve hard coded values
  - will be available in a PR shortly
- add missing values to list of other hardcoded values
  - this would take a bit of time to identify all possible nonconforming parameters and identify the correct values to add to the list. It would also be an investment of time into adding to problematic coding practices and in no way make the live of developers in the future any easier.
- rewrite the code to pull values directly from the backend . 
  - Also a time consuming endeavor and likely something that we should allocate time for in the near future.

**Comment by necoline** [comment]
@teklal Do you mind moving your comment into a new issue so that we can address it in isolation to this bug? The issue that you are pointing out is something that _was_ caused by the refactor and I'd like to make sure to document that separately

**Comment by nanometrenat** [comment]
Hi @necoline regarding the fallback, it is great that the page will render but I am concerned if it renders with incorrect data - what kind of logging is in place so that we know there is an issue if faulty parameters are being used to retrieve hard-coded values?  From a business point of view the most important thing is that we ensure that in every case when users input data that data is correctly stored, retrieved and displayed.  @batpad maybe you can advise on this also?

Re moving @teklal's comment above, she is in a meeting just now but I will do that admin on her behalf.  Thanks!

**Comment by necoline** [comment]
@nanometrenat You make a great point that better error handling is missing in this solution. I added updated the fix to include an error message and default value in the case that a parameter does not match the possible values.

**Comment by nanometrenat** [comment]
Thank you @necoline - bearing in mind that the PER functionality is already being used with live data in current Production (i.e. data is already in existence in Live) we need to be sure that either the current code supports both existing/legacy data and future-state/newly entered data - or else that there is a migration pathway to convert existing Production data to the new structure.  Thanks again!

**Comment by necoline** [comment]
The current fixes implement best frontend practices to ensure a resilient UI regardless of the data that is coming through. It does not affect the data structure in any way. The core of the bug is rooted in data and is worth examining as part of a larger solution pertaining to the backend and a possible adjustment of the way the frontend receives data coming through. My understand that this type of effort is outside the scope of this bug fix.

**Comment by teklal** [comment]
I'm still getting a blank page when trying to navigate to the Preparedness tab of Bulgaria but weirdly am able to view the Preparedness page of Belgium. Haven't tested for others this time.

**Comment by batpad** [comment]
It seems like the current blank screen is actually the result of this backend change 3 weeks ago: https://github.com/IFRCGo/go-api/blame/a80f0223215d855ec4ee6ba7f13e208b1e71ad48/per/drf_views.py#L361

I'll do a bit more digging to figure out why that change was made and whether we should fix this by reverting the change or by changing the way the frontend deals with no results for the NS Per Phase API call.

But definitely reverting that change locally causes the blank screen to go away.

**Comment by batpad** [comment]
The backend fix has been deployed. @nanometrenat @teklal if we can confirm that the Preparedness page for countries no longer seems to crash, that would be great, to be able to move on to the other enhancements.

**Comment by teklal** [comment]
Great, this works now!

**Comment by nanometrenat** [comment]
Closing ticket based on Tekla's comment above
